sparklemotion/nokogiri

- ext/nokogiri/extconf.rb
This ensures that patching is successful even if the ROOT path contains spaces.
This is the same approach that mini_portile takes. https://github.com/luislavena/mini_portile/blob/v0.6.1/lib/mini_portile.rb#L256
> Escape full path when patching

- test/html/test_document.rb
- test/xml/test_builder.rb
- test/xml/test_document.rb
- test/xml/test_entity_reference.rb
- test/xml/test_node.rb
This resolves all the ruby errors that spit out when running the test suite. Minor, but annoying.
```
/Users/kylev/Work/nokogiri/test/html/test_document.rb:224: warning: ambiguous first argument; put parentheses or even spaces
/Users/kylev/Work/nokogiri/test/html/test_document.rb:239: warning: ambiguous first argument; put parentheses or even spaces
/Users/kylev/Work/nokogiri/test/html/test_document.rb:251: warning: ambiguous first argument; put parentheses or even spaces
/Users/kylev/Work/nokogiri/test/html/test_document.rb:252: warning: ambiguous first argument; put parentheses or even spaces
/Users/kylev/Work/nokogiri/test/html/test_document.rb:258: warning: ambiguous first argument; put parentheses or even spaces
/Users/kylev/Work/nokogiri/test/xml/test_builder.rb:17: warning: …
```
> Fix warnings in test suite.

- ext/java/nokogiri/internals/NokogiriHandler.java
Now this method always calls start_element_namespace (which may call start_element if not overridden).
> Quick documentation update at java NokogiriHandler

- ext/nokogiri/extconf.rb
Simply checking */usr/include* is no longer working on the latest versions of Xcode and OS X, because there is no */usr/include* anymore. On OS X 10.10 with Xcode 6, the header resides in */Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/iconv.h*
In addition to that, the simple check also ignores things like `--with-iconv-dir`, of course.
> Use have_header() to check for the existence of iconv.h

- ext/java/nokogiri/XmlDocument.java
- ext/java/nokogiri/XmlNode.java
- test/xml/test_xpath.rb
the reset is needed to associated the namespace info with the nodes
fixes #1180
Sponsored by Lookout Inc.
> reset the namespace cache when replacing the document's innerHtml

- patches/libxml2/0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
See https://bugzilla.gnome.org/show_bug.cgi?id=746048 for more information about this security issue.
> Add patch for unclosed comment uninitialized access issue

- Gemfile
- Rakefile
- ext/nokogiri/extconf.rb
Gem `mini_portile` will be renamed to `mini_portile2` for the next release.
Among other changes, `mini_portile2` takes `configure_options` literally.
That was already addressed in commit 6195f2bde4 .
> Switch to mini_portile2 for building dependent libraries.

- bin/nokogiri
Running an example command `nokogiri http://www.ruby-lang.org/` results with the following error
'open_loop': redirection forbidden: http://www.ruby-lang.org/ -> https://www.ruby-lang.org/ (RuntimeError)
As for the other example `curl -s http://nokogiri.org` returns
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
which (I think) has `h1` tag only by accident.
> Fix cli tool example links

- ext/java/nokogiri/XmlNode.java
- test/files/GH_1042.html
- test/html/test_node.rb
fixes #1042 the drop failed because the clone XmlElement was shallow
and calling certain methods resulted in NPE
Sponsored by Lookout Inc.
> overwrite dup() method to fill clone with content

- test/xml/test_node_encoding.rb
This fixes a test failure on Windows, that was caused
by loading a HTML document per File.read(). This function
returns a string in some cpXXX encoding on Windows, which
was used as the document encoding later on, so that the test
failed.
This fixes #1387 and obsoletes #1385 .
> Fix test failure when Encoding.default_external is not UTF-8.

- ext/nokogiri/xml_node_set.c
This stood up while reviewing https://github.com/sparklemotion/nokogiri/pull/1362#discussion_r47873435 . The speed-up is around 10%:
```ruby
xml = Nokogiri::XML.parse("<r>#{"<a/>"*100}</r>")
set = xml.xpath('//a')
st = Time.now; 1000000.times{ set.to_a }; Time.now - st
```
... changed from 8.2 to 7.3 seconds on my (slow) netbook.
> Simplify NodeSet#to_a with a minor speed-up.

- ext/nokogiri/extconf.rb
Deletion of these empty directories is flawed on docker with overlayfs, so we better avoid it. The build artifacts are still removed after gem install.
This fixes nokogiri issue #1370 . For further details to the root issue see: https://github.com/docker/docker/issues/19082
> Don't remove empty directories after build.

- ext/nokogiri/html_document.c
- ext/nokogiri/html_element_description.c
- ext/nokogiri/html_entity_lookup.c
- ext/nokogiri/html_sax_parser_context.c
- ext/nokogiri/html_sax_push_parser.c
- ext/nokogiri/xml_attr.c
- ext/nokogiri/xml_comment.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_encoding_handler.c
- ext/nokogiri/xml_entity_reference.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_processing_instruction.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_text.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
Ruby-2.2 changes the String handling in such a way, that strings can
no longer be expected to be zero terminated. When zero terminated
strings are expected in the C code, StringValueCStr() must be used.
See: https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L319
Using StringValuePtr() without a length check, can also become a
security issue, because it can leak the memory after the string.
This was already an issue in the pg.gem: https://github.com/ged/ruby-pg/pull/5
> Ensure strings are zero terminated, where C-str pointers are expected.

- lib/nokogiri/xml/node.rb
- test/html/test_node_encoding.rb
- test/xml/test_document_encoding.rb
- test/xml/test_node_encoding.rb
Fix encoding of keys returned by XML::Node#namespaces. The key parts were encoded like the document, but should be UTF-8 per definition. The value parts were already encoded as UTF-8.
Encoding of the various text returning functions was tested against the document encoding, but it should be UTF-8 per definition. The XML/HTML documents are now changed to a non-UTF-8 versions, to make the tests more meaningful.
This obsoletes #1385  - although the same content, the attached patches are better separated and so should be better to review, now.
> Fix encoding of xml node namespaces and improve encoding tests.

- .travis.yml
Rails added.
https://github.com/rails/rails/pull/22792
Travis has the issue on MacOSX.
https://github.com/travis-ci/travis-ci/issues/5361
> Add Ruby 2.3.0 to Travis matrix

- ext/nokogiri/extconf.rb
This is a clarification of why #1393 was needed. It's not that `rspec-rails` fails without this, but any installation where rubygems is not available (we deliberately do this on rspec's suites for speed reasons).  It would be better to ensure rubygems is available before using it's components.
> Dont assume rubygems is loaded before using gem command

- ext/nokogiri/extconf.rb
To use the same C compiler with the Ruby.
If they are different, it may cause an issue.
For example a FreeBSD environment which has gcc and libiconv from
pkg/ports, which are installed in /usr/local.
The normal Ruby installation uses cc (clang).
But when nokogiri runs extconf.rb, libxml uses gcc by its configure,
and it uses libiconv (-liconv), instead of FreeBSD libc's iconv
because port's gcc sees /usr/local by default.
Then extconf.rb runs have_library('xml2', 'xmlParseDoc', 'libxml/parser.h')
but it fails to find -liconv because extconf.rb's try_compile uses
Ruby's CC (cc) and which doesn't see /usr/local.
> Set CC as the RbConfig's one

- CONTRIBUTING.md
- lib/nokogiri/xml/parse_options.rb
Hello,
We were working with Nokogiri, when we found that the ParseOptions class was hard to understand. In the [documentation](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/ParseOptions), available methods were not documented, so we thought we can improve it. Hope you accept it.
Regards,
Shivasubramanian A
> Made documentation better for ParseOptions

- lib/nokogiri/xml/node_set.rb
There have been innumerable questions on Stack Overflow about `NodeSet.text` not returning the expected results of individual text elements from the NodeSet items. This change adds an example of the difference and references `Node.inner_text`.
> add example to NodeSet#inner_text

- README.md
The ```.png``` badge is not retina friendly on Mac. Instead, I changed it to ```.svg```, which Code Climate officially supports as well and has the same content.
> Change code-climate badge to make it retina friendly

- Y_U_NO_GEMSPEC.md
We added a missing word to correct ungrammatical sentence.
> Added a [probably suitable] missing word.

- .github/ISSUE_TEMPLATE.md
https://github.com/sparklemotion/nokogiri/issues/1504#issuecomment-231713864
In @flavorjones response to #1504, he describes the proper way to open a
Nokogiri installation issue.
In an effort to improve the quality of issues opened against the
repository, this commit introduces a [GitHub Issue Template][blog].
[blog]: https://github.com/blog/2111-issue-and-pull-request-templates
> Introduce a GitHub Issues template

- lib/nokogiri/xml/parse_options.rb
The &lt;code&gt; tags are not necessary to get code formatting - the spaces in front of the line are good enough.
> Removing unnecessary <code> tags

- lib/nokogiri/html/document.rb
- lib/nokogiri/xml.rb
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/node.rb
These conditionals don't seem to particularly care whether the value is a Bignum, so it looks like it's safe to just switch to Integer... the only result is that ParseOptions could see some additional unused bits set.
> Avoid Fixnum deprecation warning on Ruby trunk

- ext/nokogiri/extconf.rb
First PR for OpenBSD support. #1515 it was suggested that I should also create a PR for the documentation. I'll submit that to the other repo in a few minutes.
> Use egcc on OpenBSD to fix libxml compilation

- ext/nokogiri/extconf.rb
The OpenBSD system compiler (gcc 4.2.1) cannot compile libxml
without patches, but compiles nokogiri itself fine. If using
system libraries, there is no need to compile libxml, and
therefore the system compiler will work and should be used.
If not using system libraries, the code should stay so that
compilation of libxml will succeed.
> Only require ports GCC on OpenBSD if not using system libraries (Fixes #1515)

- ext/nokogiri/nokogiri.h
Was introduced in c24b3d7a19f but code changed in 55e4ad72646 so that it's no longer in use now.
Moreover MAYBE_UNUSED() is defined in ruby-2.4 as well, so that it causes compiler warnings.
> Remove MAYBE_UNUSED() macro, which is no longer in use.

- appveyor.yml
Appveyor has ruby2.3.3 Interpriter. Added it.
> add ruby 23 appveyor.yml

- Rakefile
... JRuby 1.7 is still supported but not in --1.8 mode
> gemspec for -java version of the gem should specify >= 1.9.3

- .travis.yml
I want to add `ruby-head` as allow_failures in .travis.yml.
I think this is useful.
Because we can prepare before next version Ruby 2.5 release.
We can support the next version as faster
I found the code in `rails` and `rspec`.
https://github.com/rails/rails/blob/master/.travis.yml
https://github.com/rspec/rspec-core/blob/master/.travis.yml
Thanks
> Add ruby-head as allow_failures in .travis.yml.

- ext/nokogiri/extconf.rb
The usual download path contains only the latest version of zlib
and older versions are available at the 'fossils' path only.
If a new version of zlib arrives, all current nokogiri source gems
are immediately no longer installable, when running on Windows.
Fetching the zlib tar from the fossils directory solves this.
The latest zlib version is available in both directories.
The downside is, that we need to have an eye on zlib updates,
because appveyor will no longer fail when newer versions were released.
However this is the same as with the other bundled tar files.
> Download zlib tar from 'fossils' directory.

- ext/nokogiri/xml_sax_parser.c
We know that it is a good custom to keep the scope of variables narrower.
But, sadly, Visual C++ does not support such style.
> get rid of C99ism

- lib/nokogiri/xml/node.rb
> Add missing closing parenthesis in rubydoc

- lib/nokogiri/xml/node_set.rb
- test/xml/test_node_set.rb
NodeSet#first did not perform the same as Enumberable#first
An example from ruby doc being:
%w[foo bar baz].first(10) #=> ["foo", "bar", "baz"] 
What was expected:
Nokogiri::HTML('<a></a><a></a>').css('a').first(3)
[#<Nokogiri::XML::Element:0x3fc3dfd5f1c8 name="a">, #<Nokogiri::XML::Element:0x3fc3dfd5f1b4 name="a">]
What was received:
Nokogiri::HTML('<a></a><a></a>').css('a').first(3)
[#<Nokogiri::XML::Element:0x3fc3dfd5f1c8 name="a">, #<Nokogiri::XML::Element:0x3fc3dfd5f1b4 name="a">, nil]
> Clamp results of NodeSet#first to length of NodeSet

- Manifest.txt
- ext/java/nokogiri/internals/NokogiriHandler.java
- test/helper.rb
- test/html/sax/test_parser_text.rb
- test/xml/sax/test_parser_text.rb
I've found an inconsistency between `c` and `java` version of html and xml sax parsers.
Let it be an html:
```
<p>
text 1
<span>text 2</span>
text 3
</p>
```
We can expect that our sax parser will receive the following information:
```
start_element "p"
characters "text 1"
start_element "span"
characters "text 2"
end_element "span"
characters "text 3"
end_element "p"
```
`c` version works perfect but `java` does not. I've found a `characterStack` in `ext/java/nokogiri/internals/NokogiriHandler.java` that is actually a bug. I couldn't understand the reason of using stack for characters.
I was thinking for a long time about this stack and I've found the only reason for it: we will receive a list of character strings anyway when xml or html syntax is broken at the end of the document. But …
> Replaced character stack with string buffer

- ext/nokogiri/extconf.rb
If the base compiler or compiler specified by CC is clang, then
don't require egcc.
Add /usr/local/include as an include directory when compiling.
With these changes, the current release of OpenBSD should be
able to install nokogiri using gem install without
--use-system-libraries.
> Fix a couple of issues on OpenBSD

- lib/nokogiri/xml/node.rb
- test/html/test_node_encoding.rb
- test/xml/test_node_encoding.rb
`Node#serialize` used to return UTF-8 if no encoding was given. However this got broken in commit 53f9b66ee6.
Since UTF-8 is the default in XML and HTML5 specs, it makes sense to use UTF-8 in `serialize` as well and enforce this in the tests.
Fixes #1659
> Use UTF-8 as default encoding for Node#serialize

- ext/java/nokogiri/HtmlSaxPushParser.java
- ext/java/nokogiri/XmlSaxPushParser.java
- ext/java/nokogiri/internals/NokogiriHandler.java
- test/xml/sax/test_push_parser.rb
This pr should fix #1710 and fix the differences in the push parser implementations on MRI and JRuby. Each change is split in its own commit along with the test that fails on JRuby.
> Bunch of changes to make XmlSaxPushParser on JRuby compatible with the MRI implementation

- .travis.yml
Travis tries to install jruby-9.1.15.0200, then test failed.
> v1.7.x: allow jruby failures on travis

- test/html/test_document_fragment.rb
> Older Ruby's don't have `encoding` on String constructor

- Rakefile
- ext/java/nokogiri/XmlSyntaxError.java
this change makes Nokogiri's JRuby ext backwards compatible as well as future compatible
see #1720 where JRuby (head) 9.2 had to work around 1.8 compat mode
> [fix] avoid potential (legacy) issues booting on newer JRubies 

- concourse/nokogiri.yml
- ext/nokogiri/extconf.rb
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_namespace.h
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_node_set.h
- ext/nokogiri/xslt_stylesheet.c
Trying to make compilation produce no meaningful errors. Would love to have a second pair of eyes on this.
> fix compilation warnings

- lib/nokogiri/xml/node_set.rb
- test/xml/test_node_set.rb
It's expected to have the same interface as Array#index.
> Enable Nokogiri::XML::NodeSet#index to pass a block

- CHANGELOG.md
- Manifest.txt
- patches/libxml2/0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
- test/html/test_attributes.rb
libxml2 >= 2.9.2 fails to escape comments within some attributes. It
wants to ensure these comments can be treated as "server-side includes",
but as a result fails to ensure that serialization is well-formed,
resulting in an opportunity for XSS injection of code into a final
re-parsed document (presumably in a browser).
the offending commit is:
> https://github.com/GNOME/libxml2/commit/960f0e2
we'll test this by parsing the HTML, serializing it, then
re-parsing it to ensure there isn't any ambiguity in the output
that might allow code injection into a browser consuming
"sanitized" output.
complaints have been made upstream about this behavior, notably at
> https://bugzilla.gnome.org/show_bug.cgi?id=769760
and multiple CVEs have been declared and fixed in downstream
libraries as a result, …
> revert libxml unescaped attrs

- CHANGELOG.md
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/node_set.rb
- test/xml/test_node.rb
- test/xml/test_node_set.rb
NodeSet has useful methods `#add_class` and `#remove_class`, but we don't have those in Node.
This PR adds the following methods for easy manipulation of the "class" attribute as a list of words:
- Node#classes
- Node#add_class(name)
- Node#append_class(name)
- Node#remove_class(name)
- NodeSet#append_class(name)
I carefully avoided deduplication because in HTML(5) a class attribute value is just a list of words and some may rely on the exact sequence of words in a class attribute value.
> Add methods for class name manipulation to Node

- README.md
Added at https://github.com/sparklemotion/nokogiri/pull/1031
Version Eye was shut down.
https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
> Remove Version Eye badge

- ext/nokogiri/extconf.rb
As the values of `RbConfig::MAKEFILE_CONFIG` are intended to use in Makefile and may contain make macros, so a path in it may not match `/gcc/`, nor cannot execute directly.
Use `RbConfig::CONFIG`, whose values are expanded, for such porpose instead.
> Fix misuse of MAKEFILE_CONFIG

- ext/nokogiri/extconf.rb
This PR makes it so the call to `libxml2`'s `configure` script is done with passing `RANLIB=/usr/bin/ranlib` when running on Darwin.
This makes building native extensions more robust to the target system in the following situation:
- the user is using macOS and
- the user has GNU binutils in her `PATH`
- or somewhat, GNU binutils are linked in `/usr/local/bin`
In particular, having `libxml2` build call GNU's `ranlib` instead of Darwin's `ranlib` fails building native extensions with very cryptic error messages. The root cause is far from being obvious and one can waste many hours on it.
As such, I suggest trying to spare users and maintainers' time (less issues opened) by helping `libxml2`'s build system a bit.
> On Darwin, ignore anything but system's ranlib. Fixes #1812

- ext/nokogiri/xml_document.c
- test/html/test_document.rb
- test/test_memory_leak.rb
DTD nodes added to a document are not freed when the document is freed.
Fixes #1784 
This supersedes #1791
> Free DTD nodes (fixes 1784)

- ext/java/nokogiri/XmlDtd.java
- ext/java/nokogiri/XmlElement.java
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/XmlNodeSet.java
- ext/java/nokogiri/XmlXpathContext.java
- ext/java/nokogiri/internals/NokogiriHelpers.java
- ext/java/nokogiri/internals/NokogiriXPathFunction.java
The current implementation suffers from having poor performance.  More
specifically, `op_or' is order of magnitude slower than the MRI version slows
down XMLNodeSet::xpath and XMLNodeSet::css significantly.  This
commit rewrites the class to manage its own internal array, similar to what
libxml does.
fixes #1795
> Rewrite XmlNodeSet (fixes 1795)

- ext/java/nokogiri/internals/XalanDTMManagerPatch.java
Looks like we replaced DOM2DTM with DOM2DTMExt when we fixed
https://github.com/sparklemotion/nokogiri/pull/1320 but forgot to replace it in
the DOM2DTM manager
fixes #1749
> Replace DOM2DTM with DOM2DTMExt the patched version of DOM2DTM (fixes 1749)

- ext/java/nokogiri/XmlNode.java
- test/xml/test_node_reparenting.rb
* ext/java/nokogiri/XmlNode.java (relink_namespace): Add a namespace attribute
to the new adopted node, if the current scope namespace URI or prefix don't
match the new node's namespace.
Fixes #1774
> Add namespace attributes when necessary (fixes 1774)

- ext/java/nokogiri/XmlAttr.java
- ext/nokogiri/xml_attr.c
- test/xml/test_attr.rb
previously was rendered as a boolean attribute. also allow for boolean
attributes by setting value to `nil`.
Fixes #1800.
> setting attribute value to blank in HTML doc now renders as blank

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- lib/nokogiri/xml/document_fragment.rb
- test/xml/test_document_fragment.rb
- test/xml/test_node.rb
See #1063 for background and why this is implemented for MRI and not JRuby. See related #1832 which is a placeholder for the JRuby work should we decide to do it.
> fix #1063: poor memory performance when `dup`ing DocumentFragment

- ext/nokogiri/extconf.rb
This is an attempt at fixing the issue discussed at length in sparklemotion/nokogiri#1801, which is caused by a of header files provided by the xcode command-line tools in Xcode version 10.
This fix resolves the build issue for me without resorting to the workaround described in the [release notes for Xcode 10](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624).
> Add SDK-specific include path for macOS Mojave

- CHANGELOG.md
- lib/nokogiri/css/xpath_visitor.rb
- test/css/test_parser.rb
> CSS selector `:has()` matches against deep descendants

- ext/nokogiri/xslt_stylesheet.c
- test/test_xslt_transforms.rb
otherwise trivial XML errors will silently result in NULL being
returned by xsltApplyStylesheet() and a subsequent segfault
Fixes #1802
> [#1802] ensure we trap XML errors while applying XSLT stylesheet

- Manifest.txt
- patches/libxml2/0002-Remove-script-macro-support.patch
- test/html/test_attributes_do_not_support_macros.rb
libxml2 added support for future script macros based on the below
specification
https://www.w3.org/TR/html401/appendix/notes.html#h-B.7.1
This syntax was reserved, but has yet to be defined. It is still unclear
how these macros will be used and what risks will be created if/when
implemented.
This PR removes support until more information is provided.
> Remove support for future script macros

- ext/java/nokogiri/internals/NokogiriHandler.java
- test/xml/sax/test_document_error.rb
- test/xml/sax/test_push_parser.rb
Patch for #1847 (JRuby implementation) -- ensures that exceptions raised from `#error` are not swallowed by `nokogiri.internals.NokogiriHandler`.  Includes unit tests to verify the new behavior (as well as avoiding regressions in the SAXPullParser implementation); tests were run under both MRI 2.5.1 and JRuby 9.2.0.0
> Rethrow exceptions caught by Java SAX handler

- CHANGELOG.md
- Manifest.txt
- patches/libxslt/0001-Fix-security-framework-bypass.patch
Related to USN-3947-1 and USN-3947-2.
Addresses #1892
No. Notably the upstream patch also has not added test coverage to libxslt. Imagine me making a judgmental face right now and you've probably nailed it.
This affects the C implementation, and only when installing with the vendored version of libxslt; but not the Java implementation.
> Backport libxslt patch for CVE-2019-11068

- CHANGELOG.md
- lib/nokogiri/css/xpath_visitor.rb
- test/css/test_css_integration.rb
- test/css/test_parser.rb
Adds support for CSS queries like `"a:has(> b)"`, `"a:has(~ b)"`, and `"a:has(+ b)"`.
Closes #688.
Yes, I think so.
No.
> Support direct combinators in CSS :has()

- lib/nokogiri/xml/parse_options.rb
Nokogiri.XML does not accept keyword arguments.
Resolves https://github.com/sparklemotion/nokogiri/issues/1902
> Fix ParseOptions examples

- ext/nokogiri/xml_document.c
- test/test_css_cache.rb
- test/test_encoding_handler.rb
If we don't manually mark members of the struct, they can move out from
underneath us.  For now lets just mark them so everything stays stable.
> Implement a mark function so we're compaction friendly

- ext/java/nokogiri/HtmlDocument.java
- ext/java/nokogiri/HtmlSaxParserContext.java
- ext/java/nokogiri/NokogiriService.java
- ext/java/nokogiri/XmlAttr.java
- ext/java/nokogiri/XmlAttributeDecl.java
- ext/java/nokogiri/XmlCdata.java
- ext/java/nokogiri/XmlComment.java
- ext/java/nokogiri/XmlDocument.java
- ext/java/nokogiri/XmlDocumentFragment.java
- ext/java/nokogiri/XmlDtd.java
- ext/java/nokogiri/XmlElement.java
- ext/java/nokogiri/XmlElementDecl.java
- ext/java/nokogiri/XmlEntityDecl.java
- ext/java/nokogiri/XmlEntityReference.java
- ext/java/nokogiri/XmlNamespace.java
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/XmlNodeSet.java
- ext/java/nokogiri/XmlSchema.java
- ext/java/nokogiri/XmlText.java
- ext/java/nokogiri/XmlXpathContext.java
- ext/java/nokogiri/XsltStylesheet.java
- ext/java/nokogiri/internals/HtmlDomParserContext.java
- ext/java/nokogiri/internals/NokogiriHelpers.java
- ext/java/nokogiri/internals/NokogiriNamespaceCache.java
- ext/java/nokogiri/internals/NokogiriXPathFunction.java
- ext/java/nokogiri/internals/ParserContext.java
- ext/java/nokogiri/internals/ReaderNode.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- lib/nokogiri/xml/document.rb
There's some anti-patterns regarding JRuby ext / Java to revisit (still an ongoing effort).
The Java ext part is confusing at times - initializing parts twice (e.g. XmlDocument's node).
Relevant changes : 
- avoid ns-cache being double backed by a map + another key list (use just map backing)
also introduce a cache-key as using arrays was weird - potentially leaky on some scenarios
- do not construct ext wrapper objects went internally XML API objects are sufficient
- cleaner and more explicit way of initializing (document) internals of XmlNodeSets
- align with JRuby's toJava convention (will also now work for any Node not just Document)
- review some of the internals and remove dead-code
- do not silently swallow potentially fatal exception from backend
Nokogiri is a bit heavy on memory …
> [jruby] cleanup/refactor extension code

- ext/nokogiri/xml_node.c
- test/xml/test_node.rb
Add support for setting the line number on elements from Ruby. This only
works when Nokogiri uses `libxml2`.
Line numbers less than 65535 may be set. Larger line numbers require
`libxml2` to be compiled with a particular option and even then, it is
buggy. See https://bugzilla.gnome.org/show_bug.cgi?id=767138.
---
Thank you for contributing to Nokogiri! To help us prioritize, please take care to answer the questions below when you submit this pull request.
This PR is intended to solve the issues for downstream projects. In particular, https://github.com/gjtorikian/html-proofer/pull/362 in html-proofer which is preventing that from using Nokogumbo for HTML5 parsing.
This implementation is similar to …
> Add `Nokogiri::XML::Node#line=`

- patches/libxml2/0004-libxml2.la-is-in-top_builddir.patch
fix #1941 
BSD make seemds to need the prefix correctly.
> Add a patch to fix libxml2.la's path

- lib/nokogiri/xml/node.rb
- test/xml/test_node.rb
> add #value?, plus test

- lib/nokogiri/xml/node.rb
**Avoidable extra memory allocation**
While profiling a project to optimize memory usage, the following came to my notice:
```
Allocated String Report
-----------------------------------
154375  ""
88132  nokogiri-1.10.7/lib/nokogiri/xml/node.rb:767
```
which is:
https://github.com/sparklemotion/nokogiri/blob/e6b3229ec53ddf70f1d198bba0d3fc13fde842a8/lib/nokogiri/xml/node.rb#L767
The explanation is that **`'a string of any length' * 0 == ""`**.
`String#*` generates a *new string* even if string literals are frozen via the pragma.
Therefore, if the above line was executed (with `indent_times == 0`) a 100 times, there would be an allocation of 100 empty strings (irrespective of `indent_text`) .
This PR replaces this deterministic allocation with a single frozen string literal.
(*Hope the …
> Use the same empty string literal

- CHANGELOG.md
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.c
- lib/nokogiri/version.rb
some backwards-incompatible changes here that I don't expect actually
break anything for anyone:
* Nokogiri::VersionInfo will no longer contain the following
keys (previously these were set only when vendored libraries were
being used):
* `libxml/libxml2_path`
* `libxml/libxslt_path`
* `nokogiri -v` will no longer emit these VersionInfo values
* these C macros will no longer be defined:
* NOKOGIRI_LIBXML2_PATH
* NOKOGIRI_LIBXSLT_PATH
* these global variables will no longer be defined:
* NOKOGIRI_LIBXML2_PATH
* NOKOGIRI_LIBXSLT_PATH
Fixes #1482
> [#1482] remove library paths from version output

- CHANGELOG.md
- ext/nokogiri/nokogiri.c
- ext/nokogiri/nokogiri.h
- lib/nokogiri/version.rb
- lib/nokogiri/xml/node.rb
- test/html/sax/test_parser.rb
- test/html/test_document.rb
- test/html/test_document_fragment.rb
- test/html/test_element_description.rb
- test/test_nokogiri.rb
- test/test_version.rb
- test/xml/test_document.rb
- test/xml/test_document_encoding.rb
- test/xml/test_entity_reference.rb
See #1974 
- Added VersionInfo metadata for libxslt to match the metadata for libxml
- Renamed constant LIBXML_VERSION to LIBXML_COMPILED_VERSION.
- Renamed constant LIBXML_PARSER_VERSION to LIBXML_LOADED_VERSION.
- Renamed `VersionInfo#loaded_parser_version` to `#loaded_libxml_version` and changed the 
return type from String to Gem::Version.
- Renamed `VersionInfo#compiled_parser_version` to `#compiled_libxml_version` and changed 
the return type from String to Gem::Version.
- `Nokogiri.uses_libxml?` now accepts an optional requirement string which is interpreted as a Gem::Requirement and tested against the loaded libxml2 version. This greatly simplifies much of the version-dependent branching logic in both the implementation and the tests. …
> [#1974] libxslt version info

- lib/nokogiri/version.rb
The loading mechanism must include the ruby-version specific path.
This is a fixup to commit 252acd99aa7d9749d820b5b6ce3848e319ad282d .
---
Loading of fat binary gems fails on master branch on Windows with 
```
12: from C:/Ruby27-x64/bin/nokogiri:23:in `<main>'
11: from C:/Ruby27-x64/bin/nokogiri:23:in `load'
10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.4-x64-mingw32/bin/nokogiri:6:in `<top (required)>'
9: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
6: from …
```
> Fix loading of nokogiri binary gems

- patches/libxml2/0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
> backport libxml2 patch for CVE-2020-7595

- Rakefile
It is only necessary at build in extconf.rb.
As noted in [this issue](https://github.com/sparklemotion/nokogiri/issues/1983#issuecomment-581850547) binary gems depend on "mini_portile2" gems, although it isn't necessary.
There are no automated tests for binary gems, so far.
Only the C implementation.
> Remove dependency to "mini_portile2" from binary gems

- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/searchable.rb
- test/xml/node/test_attribute_methods.rb
- test/xml/test_node.rb
Nokogiri::XML::Node currently supports some convenience methods for dealing with CSS classes (`#classes`, `#add_class`, `#append_class`, and `#remove_class`).
There are other HTML attributes, though, that are interpreted as sets of keywords; for example `rel` (see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel).
Further, some of this keyword-attribute functionality has been built into `Loofah` in a really inconvenient way (see https://github.com/flavorjones/loofah/issues/173).
This PR creates a set of keyword-attribute convenience methods on Node:
* `#kwattr_values`
* `#kwattr_add`
* `#kwattr_append`
* `#kwattr_remove`
and re-implements the CSS class convenience methods using these new, more general, methods.
Finally, this PR improves the documentation for both sets of …
> support "keyword attributes" via new methods on Nokogiri::XML::Node

- CHANGELOG.md
- Gemfile
- Rakefile
- ext/nokogiri/extconf.rb
Keeping the dependencies updated.
It is not needed, all of the current ones should pass.
It shouldn't.
> Update mini_portile2 gem to 2.5.0

- ext/nokogiri/xml_schema.c
- test/xml/test_schema.rb
This commit works around a bug in libxml2 where parsing schemas can
result in dangling pointers which can lead to a segv.
Upstream bug is here:  https://gitlab.gnome.org/GNOME/libxml2/issues/148
Fixes #1985
> Work around a bug in libxml2

- tasks/cross-ruby.rb
The cross_compiling block wasn't called for the x86_64-linux platform, leading to an additional dependency to mini_portile2 and missing post install message.
Related patch to rake-compiler is here: https://github.com/rake-compiler/rake-compiler/pull/171
Fixes #1991
> Add a workaround for missing call to cross_compile block

- ext/nokogiri/nokogiri.h
---
Aims to partially fix the issue #2015 to allow compilation on MSVC. 
**This fixes the redefinition issues, but ideally the packaged dependencies (zlib, libxml, lixslt) would work out of the box (I am using `conan` to get the dependencies and passing some arguments such as `with-xxx-dir` to make it work right now), and the .cross-rubies and task/cross-ruby.rb would be modified to allow MSVC gems to be packaged.**
We have a thorough test suite that allows us to create releases confidently and prevent accidental regressions. Any proposed change in behavior __must__ be accompanied by tests.
If possible, please try to write the tests so that they communicate intent.
**Does this change affect the C …
> Support MSVC

- README.md
- lib/nokogiri.rb
I made this PR to update sample code.
Run sample codes with Ruby 2.7.0 and later and get decricated warning like below.
```
> Nokogiri::HTML(open('https://nokogiri.org/tutorials/installing_nokogiri.html'))
(irb):33: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly
```
So, I edited the codes not to use `Kernel#open` but `URI#open`.
Tests has no changes because I only changed sample codes.
> Kernel#open -> URI#open

- README.md
- concourse/TODO.md
I did not specifically create an issue for this because it is just a **minor spelling fix** of openSUSE/SUSE in [README.md](https://github.com/sparklemotion/nokogiri/blob/master/README.md) and [TODO.md](https://github.com/sparklemotion/nokogiri/blob/master/concourse/TODO.md)
No.
No
> Fix openSUSE/SUSE spelling

- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_io.c
GCC raises warnings for the function pointer mismatches and Visual-C raises errors in #2061 . Both should be fixed by this patch. In contrast to #2061 this patch ensures type safety for the single values to be passed to the callback.
Visual-C is not tested.
Only C.
> Fix gcc warings - alternative to #2061

- ext/java/nokogiri/HtmlSaxParserContext.java
- ext/java/nokogiri/HtmlSaxPushParser.java
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/XmlReader.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/XmlSchema.java
- ext/java/nokogiri/XmlSyntaxError.java
- ext/java/nokogiri/XmlXpathContext.java
- ext/java/nokogiri/internals/NokogiriHandler.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
This PR removes all deprecation warnings from the Java extension by using newer preferred APIs in JRuby.
The bulk of changes are to use `RubyException.toThrowable()` to construct a Java throwable for a Ruby exception, rather than the deprecated `RaiseException` constructor. This change is the likely the most controversial since it breaks compatibility with JRuby versions older than 9.2.
The other changes are to use RuntimeError instead of NativeException for raising unexpected Java XML errors, and to move away from overriding the old `to_s19` form from JRuby 1.7.
> Clean up deprecated calls into JRuby

- ext/nokogiri/extconf.rb
See https://github.com/oracle/truffleruby/blob/d0c380361d65fd9cc89f98efdf7c7f956f073720/lib/mri/mkmf.rb#L52-L54
I'll add a note in the TruffleRuby code that once we solve this we can remove the comment here too.
It's not so trivial to solve, so I think it's worthwhile adding a comment here.
Potentially compiling libxml2 with the GraalVM LLVM toolchain might allow using static libraries, but that would then mean running all of libxml2 in Sulong (instead of precompiled native code) which needs to be evaluated if it works and if it's fast.
> Add a note that NOKOGIRI_USE_SYSTEM_LIBRARIES is used by TruffleRuby

- CHANGELOG.md
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/internals/HtmlDomParserContext.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- test/files/iso-8859-1.xml
- test/test_iso.rb
This PR introduces three new commits on top of #2080/386ebcb5 in which @thbar adds tests showing a JRuby regression when parsing ISO-8859-1 content.
> Fix the tests in #2080

- CHANGELOG.md
- Gemfile
- Rakefile
Nokogiri always have had dependency on Racc, but it was never stated explicitly. This is possible issue for several reasons:
1) There is no way RubyGems/Bundler could avoid loading wrong version of Racc if other package in application specifies different version of Racc then Nokogiri needs.
2) If there is released incompatible Racc 2.x, all old versions of Nokogiri will be broken just because it does not specify its dependencies properly.
3) If Ruby decides to drop Racc from StdLib, all Nokogiri versions will be broken (unnoticeably). Or Ruby will be forced to carry Racc around around although it is possibly obsolete.
Fixes #1988
> Add explicit Racc depenency.

- CHANGELOG.md
- ext/nokogiri/xml_document.c
Closes #2105
---
#2105 
No functional changes
Only CRuby
> fix: avoid collision with glibc's canonicalize() method

- .github/workflows/macos.yml
- appveyor.yml
- ext/nokogiri/extconf.rb
- test/helper.rb
Part of continuing work to simplify extconf.rb
Test coverage of extconf.rb is still inadequate in my mind, but this doesn't make the problem worse, and in fact adds two flags to test variations of pkg-config.
Only the compilation/installation of C extensions. No functional change outside that.
> extconf: clean up pkg config logic

- CHANGELOG.md
- patches/libxml2/0006-htmlParseComment-treat-as-if-it-closed-the-comment.patch
- patches/libxml2/0007-rewrite-htmlParseLookupSequence-to-accept-an-arbitra.patch
- patches/libxml2/0008-use-new-htmlParseLookupCommentEnd-to-find-comment-en.patch
- test/html/test_comments.rb
This changeset introduces test coverage for both JRuby and CRuby implementations with respect to handling HTML parse errors within comments.
It then introduces a libxml2 patch to comply with the behavior suggested by the [WHATWG "Living Standard" doc](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-incorrectly-closed-comment) with respect to incorrectly-closed comments.
It's important to note that WHATWG's guidance is non-normative, but is what's followed by most popular browsers. Further, the difference in behavior between browsers and server-side sanitization done by a library relying on Nokogiri and libxml2 allows opportunity for XSS attacks (https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A7-Cross-Site_Scripting_(XSS)).
> Follow WHATWG guidance for incorrectly-closed HTML comments

- CHANGELOG.md
- ext/nokogiri/html_sax_parser_context.c
- ext/nokogiri/xml_sax_parser_context.c
- lib/nokogiri/xml/document_fragment.rb
- lib/nokogiri/xml/node.rb
- scripts/build-against-libxml2-source
- test/html/test_node.rb
- test/xml/test_node.rb
- test/xml/test_node_reparenting.rb
- test/xml/test_unparented_node.rb
https://github.com/rubys/nokogumbo/issues/160
:+1: 
Changes affect Nokogiri generally, though it has the side effect of bringing the JRuby and CRuby implementations in line with each other with respect to exceptions raised in edge cases.
> fix parsing in-context of parent

- ext/nokogiri/depend
- rakelib/cext-depend.rake
When developing Nokogiri, having correct dependencies in the Makefile is helpful and necessary to a tight feedback loop.
The `ext/nokogiri/depend` file was generated over ten years ago by Nobu and I'd like to have a way to easily keep it up-to-date.
Normal CI test suite should provide adequate coverage of compilation-during-installation.
No functional changes for end users.
> chore: update depend file and provide a rake task to regenerate it

- CHANGELOG.md
- ext/nokogiri/xml_relax_ng.c
- test/test_memory_leak.rb
https://github.com/sparklemotion/nokogiri/issues/2114
Tests for specific memory leaks has provided little value to prevent regressions over the years; this leak in particular is unlikely to regress, but that said, I've added a test to `test/test_memory_leak.rb` which can be run with:
```
NOKOGIRI_GC=t bundle exec ruby -Ilib:test test/test_memory_leak.rb -n/#2114/ -v
```
Before this change, that test shows increasing memory usage:
```
#2114 RelaxNG schema parsing has a small memory leak#test_0001_no longer leaks = 
(iter 0) 39720
(iter 10000) 77532 (+37812)
(iter 20000) 77532 (+0)
(iter 30000) 78852 (+1320)
(iter 40000) 81756 (+2904)
(iter 50000) 84396 (+2640)
(iter 60000) 87036 (+2640)
(iter …
```
> fix(memory): Ensure RelaxNG parsing does not leak the parser context

- ext/nokogiri/extconf.rb
Fixes #2121, which is only on master (not in any releases) resulting in some systems dynamically linking libxml2 when we asked to statically link the packaged library.
Ugh, I don't think we have good coverage for this problem. I'll think about that.
> fix: don't re-add libraries to the static link line

- ext/nokogiri/depend
- ext/nokogiri/extconf.rb
- rakelib/cext-depend.rake
Related to #2118. This is a simplified implementation of generating a C extension's `depend` file, and moves the rake task to a `cext` namespace.
Normal CI test suite should provide adequate coverage of compilation-during-installation.
> dev: simpler generation of cext depend file

- .cross_rubies
- concourse/nokogiri-pr.yml
- concourse/nokogiri-pr.yml.generated
- concourse/nokogiri.yml
- concourse/nokogiri.yml.generated
- scripts/setup-osx-native-builders
See #2123, we want to ship a release candidate of native gems that support the current Ruby 3.0.0-preview1 and potentially the upcoming Ruby 3.0.0 final release.
Yes, additional CI task has been created to ensure that the native gem builds and packages a `nokogiri.so` that supports ruby 3.0, but also exercises that the gem can be installed and runs correctly.
This change only impacts the build and packaging of native gems.
> add native gem support for ruby 3

- CHANGELOG.md
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.c
- lib/nokogiri/version/info.rb
- test/test_version.rb
When a user installs a native (precompiled) gem, it should be distinguished in some way from the `ruby` platform gem that is compiled during installation. See https://github.com/sparklemotion/nokogiri/issues/2075 for background.
Yes!
This changes the names of some of the constants in the C implementation, which I don't consider to be a breaking change since `VersionInfo` is intended to be the interface for this kind of metadata.
> native gems noted in versioninfo

- CHANGELOG.md
- lib/nokogiri/css/xpath_visitor.rb
- test/css/test_css_integration.rb
- test/css/test_parser.rb
Related to #854, which fixed this problem for CSS class selectors.
The CSS `~=` operator should treat the `class` attribute as a set of whitespace-delimited class names. However, the current implementation only works for spaces (and not tabs, newlines, or carriage returns).
Yes, I've added tests that fail without the `XPathVisitor` change but pass with it.
No, this change is entirely within rubyspace.
> fix: the CSS `~=` operator handles non-space whitespace

- lib/nokogiri/version/info.rb
- scripts/test-gem-installation
- test/test_version.rb
the presence of CPPFLAGS suitable for compilation against nokogiri and
the packaged libraries will allow us to deprecate
`libxml/libxml2_path` in v1.12.x
also:
- change VERSION_INFO["nokogiri"] from a string to a hash
- add VERSION_INFO["nokogiri"]["version"] to store the version string
I'd like to make sure we have a mechanism in place in v1.11.x that will replace `VERSION_INFO["libxml"]["libxml2_path"] so that we can deprecate it. With this value, another gem's extconf is as simple as:
```ruby
append_cflags(Nokogiri::VERSION_INFO["nokogiri"]["cppflags"])
have_libxml2 = have_header('libxml/tree.h')
have_ng = have_header('nokogiri.h')
```
Yes, test coverage added to `test/test_version.rb` and …
> feat: adds `nokogiri/cppflags` to VERSION_INFO

- LICENSE-DEPENDENCIES.md
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.c
- lib/nokogiri/version/info.rb
- rakelib/cross-ruby.rake
- test/test_version.rb
See #2127 for background. We want to be clear about which dependencies are distributed in which gem files, and provide readable license informatino.
Yes, for the changes in how VERSION_INFO is being presented.
No functional changes outside of VersionInfo, which are captured in #2139.
> Clarify library dependencies in native gems

- CHANGELOG.md
- ext/java/nokogiri/XmlXpathContext.java
- test/files/staff.xml
- test/xml/test_document.rb
- test/xml/test_dtd.rb
- test/xml/test_xpath.rb
Closes #1890
Related to #2147
JRuby's logic for inferring a namespace for the custom XPath function handler has been naive since it was introduced in 468c757. This PR makes it less naive and less likely to break things by looking for function calls in the query via regex, and looking for matches among the handler's declared Ruby methods.
Ideally we should require namespaces in both JRuby and CRuby implementations at some point to avoid having to do this kind of heavy lifting. See #2147 for a proposal.
Sure.
Only changes the JRuby implementation, to do a better job of matching the CRuby behavior.
> fix(jruby): make less-naive inference of xpath custom function ns

- patches/libxml2/0008-use-glibc-strlen.patch
This PR speeds up Nokogiri by speeding up `xmlStrlen`. It'd be better to reduce the amount of `xmlStrlen` calls from Nokogiri, but this patch is an easy win.
Our parsers sped up from 1.4 seconds to 1 second on big HTML documents with this patch.
`xmlStrlen` benchmark results:
```bash
xmlStrlen (entire HTML file): 926171.936981 μs
glibc_xmlStrlen (entire HTML file): 36905.903992 μs
delta (xmlStrlen ÷ glibc_xmlStrlen): 25.094584 times
xmlStrlen (average string): 57479.204010 μs
glibc_xmlStrlen (average string): 5802.069000 μs
delta (xmlStrlen ÷ glibc_xmlStrlen): 9.905937 times
xmlStrlen (bigger string): 388056.315979 μs
glibc_xmlStrlen (bigger string): 12797.856995 μs
delta (xmlStrlen ÷ glibc_xmlStrlen): 30.318382 times
xmlStrlen (smallest …
```
> Use glibc strlen to speed up xmlStrlen

- CHANGELOG.md
- C_CODING_STYLE.rdoc
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/internals/HtmlDomParserContext.java
- ext/nokogiri/html_document.c
- ext/nokogiri/xml_sax_parser.c
- lib/nokogiri/html/document.rb
- lib/nokogiri/xml/node.rb
- test/helper.rb
- test/html/test_document.rb
- test/html/test_document_encoding.rb
- test/test_xslt_transforms.rb
- test/xml/test_document.rb
- test/xml/test_node.rb
- test/xml/test_syntax_error.rb
There are quite a few things being addressed in this PR, but the most significant bit is consistently obeying the `recover` parse option for HTML documents. As #2130 points out, the CRuby/libxml2 implementation was completely ignoring the `recover` parse option (also know as the `strict` option) for HTML documents. This PR makes the `recover` option behave identically for HTML documents as it does for XML documents.
Related, though, the JRuby implementation was incorrectly applying the `recover` parse option in HTML documents, instead using `noerror` and `nowarning` to determine whether to raise an exception. This has been brought in line with the behavior described above.
Also related, the `EncodingReader` class which detects encoding in …
> HTML "strict" mode parsing

- lib/nokogiri.rb
Specifically, older systems may not meet our expectations for glibc,
and this commit attempts to help those poor souls find a path forward.
Closes #2081
I manually tested this change using the OCI image at:
registry.gitlab.com/gitlab-org/gitlab-omnibus-builder/centos_6:0.0.72
No.
> fix: emit helpful error when native gem fails to load glibc

- .github/workflows/macos.yml
This switches the setup-ruby action to the one created by the
[ruby organisation](https://github.com/ruby/setup-ruby) which has more
advanced features than the one already in use.
Most notably, this handles installing Bundler, bundling, and caching the
resulting bundle.
Yes, which is to say it hasn't changed any code or tests, just how they
are run.
No, just how CI runs, and you can see the results on this PR 😄.
> ci: switch to the ruby/setup-ruby action

- CHANGELOG.md
- ext/nokogiri/html_sax_parser_context.c
- ext/nokogiri/html_sax_push_parser.c
- ext/nokogiri/nokogiri.c
- ext/nokogiri/test_global_handlers.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_syntax_error.c
- ext/nokogiri/xml_syntax_error.h
- test/helper.rb
- test/namespaces/test_namespaces_preservation.rb
- test/test_xslt_transforms.rb
- test/xml/sax/test_parser_context.rb
- test/xml/test_relax_ng.rb
- test/xml/test_schema.rb
- test/xml/test_unparented_node.rb
When `libxml-ruby` is loaded before Nokogiri, it sets its own global libxml2 error handlers. There are a few places where Nokogiri does not defensively remove that handler or use its own handlers. Commit 771164d (shipped in v1.11.0) removed one instance of a defensive removal, and that combined with the presence of `libxml-ruby` caused some tests to fail in ActiveSupport's test suite.
- https://github.com/sparklemotion/nokogiri/issues/2168
- https://github.com/rails/rails/issues/41015
This changeset introduces a systemic approach to testing handlers, setting a foreign handlers before every test in the suite and asserting that it's never called. It then introduces defensive calls to `xmlSetStructuredErrorFunc` where necessary.
Notably, it also …
> fix(cruby): SAX and Push parser error handling in the presence of foreign handlers

- CHANGELOG.md
- ext/java/nokogiri/internals/HtmlDomParserContext.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- ext/nokogiri/html_document.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_document.h
- ext/nokogiri/xslt_stylesheet.c
- test/html/test_document.rb
- test/html/test_document_fragment.rb
- test/xml/test_document.rb
- test/xml/test_document_fragment.rb
Originally this PR was started to address errors in Loofah's test suite on JRuby (see flavorjones/loofah#88) related to Nokogiri object decorators not being applied correctly. The root cause of these errors was that `{XML,HTML}Document#initialize` was not being called in the JRuby implementation. Surprising! And breaks the subclassing behavior that Loofah relies on.
As I erected tests in Nokogiri's suite to make this failure obvious, I uncovered the fact that in CRuby, `Document#initialize` was actually being called twice from the `.parse` method. Even more surprising! But doesn't obviously break anything.
This PR addresses both of these issues, with the result that `Document#initialize` is called exactly once on all platforms.
**Have you …
> fix: Document#initialize should be called exactly once

- .github/workflows/macos.yml
Add coverage for Ruby 3.0 to the MacOS tests we run in Github Actions.
> ci: test ruby 3.0 in the github actions macos tests

- CHANGELOG.md
- ext/java/nokogiri/XmlNode.java
- nokogiri.gemspec
- rakelib/markdown.rake
- test/xml/test_node.rb
#1223 to make `Node#line` on JRuby smarter.
For background, the Java DOM interfaces don't provide any way for a Node to know or find the line number in the original document at which it appeared.
I'm unhappy with this approach, but was unable to figure out how to make the original approach at #1223 work. If you're familiar with the Java DOM interfaces and want to help, please do.
Yes.
The Java implementation's behavior should be closer to the C implementation's behavior now.
> (jruby) Fix Node#line

- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_document.h
See test failures when trying to install Nokogumbo against `main`:
- https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/cruby-gem-test/builds/76#L5ffe2a36:251
This restores this method as an accessible symbol after 8587972 renamed it.
Yes! Tests introduced in d02f723 demonstrated the problem that's being fixed in this changeset.
No behavioral changes.
> Restore Nokogiri_wrap_xml_document

- CHANGELOG.md
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- rakelib/test.rake
- scripts/files-modified-by-open-prs
- test/helper.rb
- test/xml/test_node_set.rb
fix: allow NodeSets to contain Nodes from multiple Documents
Specifically, this means we've added a mark callback for the NodeSet which marks each of the contained objects.
Previously we skipped explicitly marking the contained objects due to the assumption that all the nodes would be from the same document as the NodeSet itself.
Fixes #1952.
Yes, additional tests created.
This change allows the C implementation to do what the Java implementation has always allowed.
> Allow NodeSet to contain Nodes from multiple Documents (fix for #1952)

- CHANGELOG.md
- lib/nokogiri/html/document_fragment.rb
Reduce object allocations from a hack in the constructor of `Nokogiri::HTML::DocumentFragment`.
Nokogiri 1.11 requires at least Ruby 2.4.0. Therefore, we can safely use `Regexp#match?` instead of `String#=~`.
The advantages are:
- `Regexp#match?` doesn't allocate `MatchData` objects.
- Modifying the regex itself allows not using `String#strip` which duplicates the given string.
This change should be covered by existing tests.
No, it doesn't.
> Reduce allocations from hack in document_fragment

- CHANGELOG.md
- patches/libxml2/0010-parser.c-shrink-the-input-buffer-when-appropriate.patch
- test/xml/sax/test_parser.rb
This patch shrinks the libxml2 input buffer in a few parser functions.
Fixes #2132 using the proposed fix for GNOME/libxml2#200 in https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/100
Yes, the test case from #2132 is reproduced here and run against JRuby and packaged libxml2 (but not system libxml2).
This fixes an edge case in the C implementation that does not exist in the Java implementation.
> fix(cruby): patch libxml2 to address GNOME/libxml2#200

- .github/workflows/macos.yml
- appveyor.yml
`appveyor.yml` specifies "head-x64" but "30-x64" is now recognized (https://www.appveyor.com/docs/windows-images-software/#ruby).
> ci: specify 30-x64 now that Appveyor supports it

- CHANGELOG.md
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.h
- lib/nokogiri/version/info.rb
- scripts/test-gem-installation
- test/test_version.rb
Closes #2167 which relates to an issue building Nokogumbo on Windows against the precompiled libraries.
This PR does the following:
- ensures that libxml2 symbols are exported when built on windows
- ensures that nokogiri symbols are exported when built on windows
- includes `LDFLAGS` in `Nokogiri::VERSION_INFO` to allow the windows linker to resolve all symbols
There's pretty good test coverage of this test case in the Nokogumbo CI suite; and I've added some light tests here in `scripts/test-gem-installation` though I'll note that we're not testing gem installation on Windows in the Nokogiri CI suite at the moment (though, see https://github.com/sparklemotion/nokogiri/issues/2153).
**Does this …
> fix nokogumbo linking on windows

- CHANGELOG.md
- ext/nokogiri/extconf.rb
See https://github.com/sparklemotion/nokogiri/issues/2191
> Allow overriding env var with --use-system-libraries=false and default to --disable-static on TruffleRuby

- CHANGELOG.md
- ext/java/nokogiri/XmlDocument.java
- ext/nokogiri/xml_document.c
- test/xml/test_document.rb
#1900
Yes!
The CRuby implementation now raises an ArgumentError where it previously segfaulted. The JRuby implementation now raises an ArgumentError instead of a TypeError.
> check type passed to `Document#root=`

- CHANGELOG.md
- patches/libxml2/0011-update-automake-files-for-arm64.patch
- patches/libxslt/0001-update-automake-files-for-arm64.patch
The packaged versions of libxml2 and libxslt contain automake files that do not support arm64/aarch64/M1 architecture, meaning that people on those systems can't compile Nokogiri from source.
We've been relying on the precompiled native gems to solve this problem, but I guess there is a need to fully support the platform.
This is an attempt at a fix; but I really need someone with an M1 to verify that this works.
No! We unfortunately don't have arm64 coverage in the test suite. Someone with an M1 can follow these instructions to test:
- checkout this branch (`flavorjones-allow-arm64-compilation`)
- bundle exec rake clean clobber
- bundle exec rake compile
- bundle exec rake test
Note that the …
> fix: update automake files to allow arm64 to compile packaged libraries

- test/helper.rb
- test/html/sax/test_push_parser.rb
- test/html/test_attributes.rb
- test/html/test_attributes_properly_escaped.rb
- test/namespaces/test_namespaces_in_parsed_doc.rb
- test/test_nokogiri.rb
- test/test_version.rb
- test/test_xslt_transforms.rb
- test/xml/sax/test_parser.rb
- test/xml/sax/test_push_parser.rb
- test/xml/test_document_encoding.rb
- test/xml/test_document_fragment.rb
- test/xml/test_node.rb
- test/xml/test_node_attributes.rb
- test/xml/test_node_reparenting.rb
- test/xml/test_node_set.rb
- test/xml/test_reader.rb
- test/xml/test_reader_encoding.rb
- test/xml/test_relax_ng.rb
- test/xml/test_schema.rb
- test/xml/test_xinclude.rb
- test/xml/test_xpath.rb
- test/xslt/test_custom_functions.rb
- test/xslt/test_exception_handling.rb
Just cleaning up some tests, making some of the GC-specific tests more declarative and introducing a standard way to skip platform-specific tests.
> clean up tests

- CHANGELOG.md
- lib/nokogiri/xml/parse_options.rb
- lib/nokogiri/xslt.rb
- lib/nokogiri/xslt/stylesheet.rb
- test/test_xslt_transforms.rb
See #1940 where some XSL transformations ended up producing slightly different results from `xsltproc`
Yes!
This behavior appears to be libxslt-specific, and so the test only runs for CRuby; though the document ends up being parsed with the new options on both implementations.
> parse XSLT stylesheets using libxslt-preferred options

- .editorconfig
- CHANGELOG.md
- ext/nokogiri/extconf.rb
- rakelib/format.rake
- Speed up the one-time automake-based builds of libiconv, libxml2, and libxslt using the `--disable-dependency-tracking` option.
- Update `.editorconfig` for Java files to match the `astyle` formatting choices made in `rakelib/format.rake`
- Formatting uses `MakeMakefile.find_executable0` to discover `astyle` (instead of `.find_executable`) in order to avoid creating and cleaning up a stray `mkmf.log` file.
The functional change, disabling dependency tracking, has plenty of test coverage already.
> small chores / improvements

- ext/nokogiri/nokogiri.c
- lib/nokogiri/version/info.rb
- test/html/test_comments.rb
Adjust tests to pass on system libxml2 >= 2.9.11, because the comment parsing improvement was merged upstream. See https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/82 for context (and the recently removed `htmlParseComment` patch). This will allow us to run tests regularly against upstream master.
Also, work around the libxml2 issue described in #2241 by having libxml2 use its default memory management on windows when system libraries are being used. Note that this also introduces a new value into `Nokogiri::VERSION_INFO`, which is "libxml → memory_management", and the value will be either "ruby" or "default".
> test: adjust tests to pass on system libxml2 >= 2.9.11, and work around windows dll unloading issue

- .github/workflows/windows.yml
- CHANGELOG.md
- ext/nokogiri/nokogiri.c
- lib/nokogiri/version/info.rb
- test/html/test_comments.rb
#2241. This is applying #2240 to the v1.11.x branch for a patch release.
Existing test coverage is adequate on Appveyor, however in this PR we also add Github Actions coverage which is a bit faster than Appveyor for faster feedback loops.
It changes the behavior of libxml2's memory management, but only on Windows when using system DLLs.
> (v1.11.x) update tests to work with system libxml 2.9.12, and work around windows dll unloading issue

- CHANGELOG.md
- test/xml/test_builder.rb
- test/xml/test_node.rb
Add tests for the behavior change introduced by 1f483f0.
That behavior change fixes #1712
Yarp.
The Java implementation already exhibited this behavior; and 1f483f0 brought the two implementations in line with each other.
> namespace behavior change when reparenting

- ext/nokogiri/html_element_description.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_element_content.c
- ext/nokogiri/xml_encoding_handler.c
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
As specified in [`extensions.rdoc` on Ruby trunk](https://github.com/ruby/ruby/blob/master/doc/extension.rdoc), T_DATA classes should undefine (or redefine) the allocator function.
I test-drove these change by temporarily introducing this into `nokogiri.h`:
```c
static void
noko_check_allocator(VALUE klass)
{
rb_alloc_func_t current_allocator = rb_get_alloc_func(klass);
rb_alloc_func_t parent_allocator = rb_get_alloc_func(rb_cObject);
if (current_allocator == parent_allocator) {
VALUE class_name = rb_class_name(klass);
fprintf(stderr, "MIKE: %s has the default allocator\n",
StringValueCStr(class_name));
}
}
static VALUE
noko_check_wrap(VALUE klass, RUBY_DATA_FUNC dmark, RUBY_DATA_FUNC dfree, void *sval)
{
noko_check_allocator(klass);
return …
```
> T_DATA classes should undef the allocator, or define a custom allocator

- ext/nokogiri/xml_node.c
- test/xml/test_document.rb
- test/xml/test_document_fragment.rb
Fixes #2250 which describes a segfault when calling `DocumentFragment#path` with libxml > 2.9.10.
Yes. Introduced test coverage for both `DocumentFragment#path` and `Document#path`
This maintains the behavior of the C extension across versions of libxml2. That, however, doesn't mean that the behavior makes sense, and we should fix it when we're ready to introduce breaking changes into `DocumentFragment#xpath`.
> fix: `DocumentFragment#path` with libxml > 2.9.10

- CHANGELOG.md
- ROADMAP.md
- ext/nokogiri/xml_node.c
- rakelib/markdown.rake
- test/xml/test_document.rb
- test/xml/test_document_fragment.rb
This is a version of PR #2251 that applies the fix for #2250 to the v1.11.x branch.
> fix(v1.11.x): `DocumentFragment#path` with libxml > 2.9.10

- ext/nokogiri/gumbo.c
- ext/nokogiri/nokogiri.h
- Ruby 3.0 deprecates `rb_cData`
- Ruby head emits warnings around `_MSC_VER` and `_WIN32` macros
> fix: address ruby 3.0 compiler warnings

- .github/workflows/ci.yml
- .github/workflows/upstream.yml
- ext/nokogiri/extconf.rb
- nokogiri.gemspec
- test/html/test_attributes_properly_escaped.rb
Do more-frequent integration testing with upstream libraries, to find issues early. Related to #2247.
- update to mini_portile 2.6.0
- modify extconf.rb
- make sure tests will be green against unpatched upstream today
- add a github actions pipeline
> build against upstream libxml2 and libxslt

- CHANGELOG.md
- patches/libxml2/0007-Fix-XPath-recursion-limit.patch
Backporting an upstream libxml2 fix for the problem described in #2257
> fix: libxml2 xpath recursion limit bug (v1.11.x)

- CONTRIBUTING.md
- scripts/test-gem-set
Recommending that developers of Nokogiri use `rbenv` instead of `rvm` to enable us to more easily test against custom Ruby builds (like the "extensions check" PR I'm writing for upstream Ruby).
We only use RVM in one place: installing and testing the built gems with `scripts/test-gem-set` (and that's only used from `scripts/build-gems`). This PR replaces it with `rbenv`.
> dev: switch from `rvm` to `rbenv` in scripts/test-gem-set

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/upstream.yml
Trying to optimize feedback loops: If a branch CI is already running, and another commit is pushed, cancel CI in progress.
> ci: github actions concurrency and cancel-in-progress

- .github/workflows/truffle.yml
- appveyor.yml
- rakelib/check-manifest.rake
Ensure we have some TruffleRuby coverage in the Github Actions pipelines. Previously we had coverage on Concourse, which has been dropped as a CI platform. See #2247 for context.
> ci: add truffleruby to github actions

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/truffle.yml
- .github/workflows/upstream.yml
make the github actions cache platform-specific
because, e.g., zlib isn't used on linux but it used on windows, and if it's not in the cache then we'll end up re-downloading and potentially getting throttled.
> ci: make the GA cache platform-specific

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/truffle.yml
- .github/workflows/upstream.yml
- CHANGELOG.md
- ext/nokogiri/nokogiri.c
- ext/nokogiri/xslt_stylesheet.c
- lib/nokogiri/version/info.rb
- test/test_nokogiri.rb
- test/test_version.rb
- test/test_xslt_transforms.rb
The 3.1.0.dev windows ruby installer uses UCRT, see #2268 for context. This gives Nokogiri and @larskanis a feedback loop.
> ci: try UCRT for windows ruby-head builds

- .github/workflows/ci.yml
- .github/workflows/upstream.yml
- ext/nokogiri/extconf.rb
Quite a bit of CI time is spent compiling our packaged dependencies (libxml2, libxslt, libiconv, zlib). For a given platform, we should be able to cache these libraries once compiled.
This PR does two things:
- move libgumbo out of `/ports`
- caches `/ports` for most jobs that were previously caching just `/ports/archives` (which only contains the tarballs)
I'll run CI twice on this branch and compare the timing to previous runs to make sure this is actually effective.
> improve CI caching of compiled dependencies

- scripts/test-gem-install
- scripts/test-nokogumbo-compatibility
Adding test coverage to ensure that we don't break any applications that have upgraded Nokogiri but haven't dropped Nokogumbo yet.
Related to #2204
This PR is pure test coverage :sunglasses: 
No behavior changes.
> ci: ensure that nokogumbo 2.0.4 and 2.0.5 both work

- test/helper.rb
- test/xml/test_node_set.rb
In an attempt to speed up CI, I'm experimenting with moving from Valgrind to using ASan for detecting memory issues.
One issue was reported at https://bugs.ruby-lang.org/issues/18001
The second issue is that we see a warning like:
> ==108142==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7ffc026fc000; bottom 0x7f18d53ae000; size: 0x00e32d34e000 (975716016128)
> False positive error reports may follow
> For details see https://github.com/google/sanitizers/issues/189
when we run the Enumerator#each test. Note that we've had to take precautions with this test with valgrind as well, because of the way the stack is manipulated within Enumerator.
This PR skips this test when it detects that ASan has been linked in.
> ci: skip the problematic Enumerator#each test with ASan

- gumbo-parser/src/parser.c
- gumbo-parser/test/parser.cc
- test/html5/test_tree-construction.rb
html5lib-tests has updated since I forked it to fix a bunch of errors. Some of the updates include new tests to test functionality that changed in the spec. This updates the code to parse the new tests, updates the submodule to include my fixes to the latest version of html5lib-tests, and updates the gumbo parser to accommodate the spec changes.
The new tests were mentioned in https://github.com/sparklemotion/nokogiri/issues/2204#issuecomment-863550189.
Yes. The changes to the parser include parser-specific tests and the update to html5lib-tests includes end-to-end tests to test the behavior.
This only affects …
> Update html5 tests

- test/xslt/test_custom_functions.rb
Upstream libxslt started failing after https://gitlab.gnome.org/GNOME/libxslt/-/commit/b0074eeca3c6b21b4da14fdf712b853900c51635 which addresses https://gitlab.gnome.org/GNOME/libxslt/-/issues/55.
Update the test to order the templates appropriately to reflect this change to how templates are resolved.
This change affects only tests, not functional behavior.
This change to the tests is forward-looking, as the next version of libxslt is likely to include the related change to the xslt template resolver.
> libxslt: tests should handle changed XSLT template resolution

- rakelib/test.rake
When running in Github Actions, the default minitest progress reporter makes the Actions UI appear to hang while the tests are running (presumably because there are no newlines to cause a flush of IO?).
Let's move to using `-v` when running in CI so that we have a better sense of progress. Disk is cheap! Right?
> ci: run minitest in verbose mode on CI

- .gitmodules
My PR to fix the errors
https://github.com/html5lib/html5lib-tests/pull/136 was merged. We can
now track the upstream repository.
Closes #2282
The html5 tests had been tracking my fork of html5lib-tests but with https://github.com/html5lib/html5lib-tests/pull/136 merged, we can track upstream. #2282 
There is no change in test coverage.
This is only relevant to the C implementation, but it affects the behavior of neither.
> Switch to upstream html5lib-tests

- .github/workflows/upstream.yml
As the `html5lib-tests` repo changes over time, I think it might be helpful to automatically run against the latest so that if any failures are introduced, we can address them proactively.
This PR adds a job to the `upstream` CI pipeline, which runs periodically every few days, running against the latest versions of some of Nokogiri's dependencies.
I'll rely on @stevecheckoway to tell me if this is _actually_ useful.
This PR introduces new test coverage.
> ci(upstream): run against latest html5lib-tests master

- ext/nokogiri/gumbo.c
#2276 reports some valgrind warnings coming from the object used to wrap gumbo parse arguments.
This PR avoids the creation of an object and passes the C struct pointer directly, casting it as a `VALUE` when necessary.
I spent a few hours trying to reliably reproduce the #2276 warning and couldn't. :shrug: 
> fix(gumbo): use C struct pointer directly instead of wrapping

- .github/workflows/ci.yml
- Vagrantfile
- gumbo-parser/src/Makefile
The makefile in `gumbo-parser/src/Makefile` contained Gnu-isms that are not compatible with BSD `make` (see #2298). This PR adds CI coverage for FreeBSD and updates the makefile to be portable across both flavors of `make`.
Yes! New jobs in the `ci` pipeline will cover BSD with and without system libraries.
Just the C implementation on BSD, and just at install-time.
> fix BSD support for libgumbo

- .github/workflows/upstream.yml
- ext/nokogiri/extconf.rb
- ext/nokogiri/gumbo.c
See #2302 and conversation at #2303. This PR explicitly enables C90- and C99-isms in the C extension code.
cc @stevecheckoway
> better c99 fix

- .github/workflows/upstream.yml
This reverts commit a81343b2192ede40db8ddd89dd5a0a3e67c4c7a3.
Ruby-head on windows is failing. It's not clear to me why
The first failure was [here](https://github.com/sparklemotion/nokogiri/actions/runs/1105925545), with an error message indicating it might have been a server-side problem, but I recently introduced a81343b2192ede40db8ddd89dd5a0a3e67c4c7a3 to quash warnings and a different failure is now being raised, which seems to be packages not being found when enabling system libraries, and a segfault when using packaged libraries.
Here I'm just experimentally unwinding that change to see if I can learn what's going wrong.
> Revert "ci: avoid warnings from setup-ruby-ref"

- .github/workflows/ci.yml
- .github/workflows/generate-ci-images.yml
- .github/workflows/truffle.yml
- .github/workflows/upstream.yml
- oci-images/nokogiri-test/truffle-nightly.dockerfile
- oci-images/nokogiri-test/truffle.erb
- rakelib/docker.rake
Part of #2271
- make sure all images are generated from the same Gemfile.lock
- use the generated images (from ghcr.io) in all the pipelines
- schedule ci.yml to integration test the containers after they're generated
> ci: generate and use images to/from ghcr.io

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- lib/nokogiri/xml/parse_options.rb
- test/xml/test_node.rb
As noted in #1493, #1617, #1505, #1003, and #533, libxml2 has not historically supported line numbers greater than a `short int`. Starting in libxml v2.9.0, setting the parse option `BIG_LINES` would allow tracking line numbers in longer documents.
Specifically this PR makes the following changes:
- set `BIG_LINES` parse option by default which will allow `Node#line` to return large integers
- allow `Node#line=` to set large line numbers on text nodes
Fixes #1764 
Yes!
JRuby's Xerces-based implementation did not suffer from this particular shortcoming, although its line number functionality is questionable in …
> feat(cruby): support line numbers larger than a short

- dependencies.yml
Fixes #2206
CI pipelines on darwin and windows should be sufficient.
No.
> dep: update libiconv to 1.16

- CHANGELOG.md
- patches/libxml2/0008-htmlParseComment-handle-abruptly-closed-comments.patch
- test/html4/test_comments.rb
Hackerone user [tehryanx](https://hackerone.com/tehryanx?type=user) reported a method of potentially confusing Loofah sanitizers by taking advantage of the difference between how abruptly-closed comments are handled by libxml2 and how they're handled by WHATWG-guidance-compliant modern browsers.
WHATWG advises to treat `` as empty comments, but libxml2 today treats these as the _start_ of a comment.
https://html.spec.whatwg.org/multipage/parsing.html#parse-error-abrupt-closing-of-empty-comment
I've submitted this patch upstream at https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/124
Similar prior art is for incorrectly-closed comments:
- https://github.com/sparklemotion/nokogiri/pull/2058
- …
> feat(cruby): patch libxml2 to handle abruptly-closed HTML comments

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/xml/test_node_reparenting.rb
Fixes #1912
Yes
C is now at parity with Java
> feat(cruby): raise RuntimeError if reparenting creates a cycle

- ext/java/nokogiri/XmlSchema.java
- test/html4/test_node.rb
- test/xml/test_schema.rb
The LSResourceResolver interface specifies that the systemId parameter may be null. The SchemaResourceResolver uses this argument without checking for this which can result a NullPointerException. This patch adds an extra null check before using the parameter.
I'm seeing this NPE in my code, but I'm afraid I haven't been able to derive a simple reproduction case yet. No test yet either as a consequence.
Only the Java implementation.
> Resolve potential NPE in SchemaResourceResolver

- CHANGELOG.md
- ext/java/nokogiri/XmlDocumentFragment.java
- ext/java/nokogiri/XmlNode.java
- ext/nokogiri/xml_node.c
- lib/nokogiri/xml/builder.rb
- lib/nokogiri/xml/document.rb
- test/xml/test_builder.rb
- test/xml/test_document.rb
- test/xml/test_node_reparenting.rb
- allow users to determine how namespaces are inherited by reparented children via `Document#namespace_inheritance` atttribute which defaults to `false`
- `XML::Builder` sets `Document#namespace_inheritance` to `true` but allows it to be overridden via constructor parameter
I'd like this to be backported to v1.12.
**Deeper context**
Prior to v1.12.0, the CRuby and JRuby implementations had different behavior with respect to how children inherit namespaces when added to a parent node (via the `Node#add_child` family of methods). In CRuby, children without a namespace would automatically inherit their new parent's namespace (a bug originally reported in 2011 at [#425](https://github.com/sparklemotion/nokogiri/issues/425)). In JRuby, this was …
> Restore Builder namespace inheritance behavior, and introduce Document#namespace_inheritance

- lib/nokogiri/xml/node/save_options.rb
- test/html4/test_document.rb
Addresses the bug described in #2324
Commit 1d06b4f1 introduced `NO_EMPTY_TAGS` into `SaveOptions::DEFAULT_XHTML` which libxml2 ignored due to a long-standing bug in serialization.
libxml2 v2.9.11 fixed that serialization bug
(https://gitlab.gnome.org/GNOME/libxml2/-/commit/dc6f009) and started paying attention to the `NO_EMPTY_TAGS` save option, resulting in seeing output containing, e.g. `<col></col>` instead of `<col/>`.
This commit updates the default XHTML save options to drop the `NO_EMPTY_TAGS` flag, restoring this behavior.
Yes.
This brings the C implementation for libxml >= 2.9.11 back into agreement …
> fix: HTML4::Document.to_xhtml self-closing tags

- lib/nokogiri/xml/node/save_options.rb
- test/html4/test_document.rb
This is #2326 backported to v1.12.x for a patch release.
> fix: HTML4::Document.to_xhtml self-closing tags (v1.12.x)

- ext/java/nokogiri/Html4SaxPushParser.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/XmlSaxPushParser.java
- ext/java/nokogiri/internals/NokogiriEntityResolver.java
- ext/java/nokogiri/internals/NokogiriErrorHandler.java
- ext/java/nokogiri/internals/NokogiriHandler.java
- ext/java/nokogiri/internals/NokogiriNonStrictErrorHandler.java
- ext/java/nokogiri/internals/NokogiriNonStrictErrorHandler4NekoHtml.java
- ext/java/nokogiri/internals/NokogiriStrictErrorHandler.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- test/xml/sax/test_parser.rb
- test/xml/sax/test_push_parser.rb
https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2rr5-8q37-2w7h (may be private for now)
This is a backport of #2328 for a v1.12.x patch release.
Yes.
The Java implementation behavior now matches the C implementation behavior.
> fix JRuby SAX parser entity handling (v1.12.x backport)

- ext/java/nokogiri/Html4SaxPushParser.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/XmlSaxPushParser.java
- ext/java/nokogiri/internals/NokogiriEntityResolver.java
- ext/java/nokogiri/internals/NokogiriErrorHandler.java
- ext/java/nokogiri/internals/NokogiriHandler.java
- ext/java/nokogiri/internals/NokogiriNonStrictErrorHandler.java
- ext/java/nokogiri/internals/NokogiriNonStrictErrorHandler4NekoHtml.java
- ext/java/nokogiri/internals/NokogiriStrictErrorHandler.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- test/xml/sax/test_parser.rb
- test/xml/sax/test_push_parser.rb
https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2rr5-8q37-2w7h (may be private for now)
Yes.
The Java implementation behavior now matches the C implementation behavior.
> fix JRuby SAX parser entity handling

- ext/nokogiri/extconf.rb
Bring zlib and iconv config closer to how we configure the other libraries. Specifically, we remove the `windows?` check for zlib, and we explicitly add the `include` directories for both if the mini_portile recipe has been invoked.
I think existing coverage is fine, this is a refactoring. Note that this commit was originally part of #2332 and breakage was caught by the `gem-install` pipeline on windows.
It's a slight change to how the Windows C extension is built; but a small one.
> Configure zlib and iconv consistently

- CHANGELOG.md
- ext/java/nokogiri/internals/SaveContextVisitor.java
- test/html4/test_node.rb
Fixes #2355
The JRuby code for SaveContextVisitor is brittle and clearly
buggy (since this bug exists for fragment nodes but not fragments or
document nodes?), but this seems like an easy fix.
Yes. Though I fear we still don't have enough coverage on JRuby formatting.
This brings the JRuby implementation in line with the C implementation and the XHTML spec.
> fix(jruby): XHTML formatting of non-container element closing tags

- .github/workflows/generate-ci-images.yml
- oci-images/nokogiri-test/alpine.dockerfile
- oci-images/nokogiri-test/alpine.erb
- rakelib/docker.rake
Update the alpine CI image to install git, in order for actions/checkout to clone submodules
> ci: oci image for alpine should have git installed

- .github/workflows/ci.yml
See https://github.com/sparklemotion/nokogiri/issues/2354 for an investigation into why Ruby 2.5 Windows jobs started failing last week. Until that gets sorted, this PR will make those builds "nonblocking" when they fail.
> ci: allow windows 2.5 builds to fail

- .github/workflows/gem-install.yml
- CONTRIBUTING.md
Add CI coverage for native linux gem installation on musl libc systems.
At one point in 2021 this didn't work because the download-artifact action was failing on musl systems, but it appears to work now.
See related:
https://github.com/flavorjones/ruby-c-extensions-explained/pull/4
> ci: test native gem install on musl systems

- .github/workflows/ci.yml
- .github/workflows/generate-ci-images.yml
- rakelib/docker.rake
Revert the workaround to https://github.com/docker/buildx/issues/834 that was solved by https://github.com/moby/buildkit/pull/2461
> ci: revert buildx workaround in image-building

- CHANGELOG.md
- lib/nokogiri/xml/builder.rb
- test/xml/test_builder.rb
https://github.com/sparklemotion/nokogiri/issues/2372
I think so.
Yes, since this changes non-platform specific code.
Co-authored-by: Joana Tavares <jtavares@salsify.com>
> Fix XML::Builder not handling exceptions safely - 2372

- .github/workflows/ci.yml
When actions's `macos-latest` moved to macos-11, the `vmactions/freebsd-vm` started failing with this error:
```
/usr/bin/sudo vboxmanage import /Users/runner/work/_actions/vmactions/freebsd-vm/v0.1.5/freebsd-13.0.ova
sudo: vboxmanage: command not found
Error: The process '/usr/bin/sudo' failed with exit code 1
```
This PR locks that job to macos-10.15.
> ci: vmactions/freebsd-vm needs macos-10.15

- nokogiri.gemspec
rake-compiler v1.1.2 broke darwin native builds, see https://github.com/sparklemotion/nokogiri/runs/4458677557?check_suite_focus=true for an example
This PR pins us to v1.1.1 for now
cc @larskanis
> dep(dev): rake-compiler 1.1.2 broke darwin native builds

- test/xml/test_reader.rb
see #2354 which describes tests segfaulting in CI for Windows Ruby 2.5
This PR simply skips a test that we know is segfaulting in an attempt to ignore the likely root cause of gcc version incompatibilities in CI.
> ci: skip tests that are causing issues in CI

- CHANGELOG.md
- ext/java/nokogiri/XmlReader.java
- ext/nokogiri/xml_reader.c
- lib/nokogiri/xml/reader.rb
- test/xml/test_reader_encoding.rb
Closes #980 
Previously Reader#encoding always and only returned the encoding passed to the
constructor. Now, if no encoding is passed to the constructor, then
Reader#encoding will return the encoding detected by the parser.
Yes.
Note that this has not been implemented for JRuby.
> feat(CRuby): XML::Reader#encoding returns detected enc when not set

- .github/workflows/ci.yml
- nokogiri.gemspec
- rakelib/test.rake
- scripts/test-gem-build
- suppressions/nokogiri_ruby.supp
- test/helper.rb
@peterzhu2118 and I paired on getting his [ruby_memcheck](https://github.com/peterzhu2118/ruby_memcheck) gem running in Nokogiri.
This is an experiment, but this approach promises to avoid all the noisy false positives that valgrind's `--leak-check` tends to emit.
It:
- adds ruby_memcheck as a dev dependency
- adds a rake task
- adds a CI task to run that rake task
> test: try using ruby_memcheck to look for leaks

- ext/nokogiri/xml_node.c
@kwilczynski mentioned that a static analysis tool found this:
> duplicateConditionalAssign ext/nokogiri/xml_node.c:1898 The statement 'if (child_iter->parent!=(xmlNodePtr)node->doc) child_iter->parent=(xmlNodePtr)node->doc' is logically equivalent to 'child_iter->parent=(xmlNodePtr)node->doc'.
https://gist.github.com/kwilczynski/4b2f4650b00cead133e337714260a416
> cleanup: remove unnecessary conditional

- CHANGELOG.md
- lib/nokogiri.rb
- lib/nokogiri/class_resolver.rb
- lib/nokogiri/xml/builder.rb
- lib/nokogiri/xml/node.rb
- nokogiri.gemspec
- rakelib/check-manifest.rake
- test/xml/test_builder.rb
- test/xml/test_node.rb
#1158 reported a bug whose root cause is the use of incorrect class (Nokogiri::HTML4::DocumentFragment instead of Nokogiri::XML::DocumentFragment) during fragment parse error recovery.
This PR introduces a new mixin, `Nokogiri::ClassResolver` for the few places in the codebase where an appropriate class needs to be chosen. (For example, a node in a `Nokogiri::XML::Document` needing to use the related `DocumentFragment` class.) `ClassResolver` is now used for fragment parsing as well as `Builder` document creation.
Yes!
No.
> use the correct classes for fragment parsing

- ext/nokogiri/extconf.rb
* Update the source link for libiconv due to redirect not followed on windows
* Update zlib source link to `https` to be consistent where possible
* xmlsoft.org is left as `http` due to what looks like SNI hosting without `https` service for xmlsoft.org
Native build on windows seems to be failing due to redirects related to `libiconv` package retrieval.
```
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libiconv-1.15.
Configuration options: --host\=x86_64-w64-mingw32 --enable-static
--disable-shared
--libdir\=C:/embedded/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5/ports/x86_64-w64-mingw32/libiconv/1.15/lib
--disable-dependency-tracking --disable-shared --enable-static CPPFLAGS\=-Wall …
```
> update source links to https where possible

- bin/nokogiri
See #2392 for an example of UX confusion when the Nokogiri CLI contains an error that raises an exception.
This change will change the resulting output from:
```
$ nokogiri -e "$_" < /dev/null
<main>:1:in `<top (required)>': undefined local variable or method `xxxx' for main:Object (NameError)
from /home/flavorjones/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `eval'
from /home/flavorjones/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/bin/nokogiri:112:in `<top (required)>'
from /home/flavorjones/.rbenv/versions/3.0.3/bin/nokogiri:25:in `load'
from /home/flavorjones/.rbenv/versions/3.0.3/bin/nokogiri:25:in `<main>'
```
to
```
bin/nokogiri -e "$_" < /dev/null …
```
> feat: print failing expression when nokogiri cli errors

- CHANGELOG.md
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/node_set.rb
- lib/nokogiri/xml/searchable.rb
- test/xml/test_document_fragment.rb
- test/xml/test_node.rb
- test/xml/test_node_set.rb
Fixes #1857
Along the way we've extracted `#>` from Node and NodeSet into
Searchable.
Yes, improved the existing tests for this method across
Node, NodeSet, and DocumentFragment.
No, changes common code.
> fix: DocumentFragment#> works properly

- CHANGELOG.md
- ext/java/nokogiri/XmlDocumentFragment.java
- ext/java/nokogiri/internals/NokogiriStrictErrorHandler.java
- ext/nokogiri/xml_document_fragment.c
- lib/nokogiri/html4.rb
- lib/nokogiri/html4/document.rb
- lib/nokogiri/html4/document_fragment.rb
- lib/nokogiri/xml.rb
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/document_fragment.rb
- lib/nokogiri/xml/node.rb
- test/html4/test_document_fragment.rb
- test/xml/test_document_fragment.rb
Similar to Document constructors, we can now pass in parse options as
a parameter or via a config block.
Fixes #1692
Fixes #1844
Co-authored-by: @jackmc
Yes! Both XML and HTML4 document fragments now have complete test coverage of parse options.
Both implementations have been updated.
> feat: DocumentFragment constructors all take parse options param

- CHANGELOG.md
- ext/java/nokogiri/XmlNode.java
- ext/nokogiri/xml_node.c
- lib/nokogiri/html5.rb
- lib/nokogiri/xml/node.rb
- test/xml/test_node.rb
- test/xml/test_unparented_node.rb
The second argument to Node.new **must** be a Node, and it _should_ be a Document (and a warning will be emitted if it is not).
Closes #975
Yarp
Both implementations have been updated.
> fix: Node.new second argument is typechecked

- test/xml/test_reader.rb
#2354 introduced a skip to tests that were failing on Ruby 2.5 on windows for reasons related to system library versions.
This PR removes that skip, now that 2.5 has been dropped.
> test: stop skipping windows test from #2354

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/generate-ci-images.yml
- .github/workflows/upstream.yml
- CONTRIBUTING.md
- oci-images/nokogiri-test/mri-3.1.dockerfile
- rakelib/docker.rake
- suppressions/nokogiri_ruby.supp
See #2397 which describes supporting Ruby 3.1 in precompiled native gem releases.
Yes!
No behavioral changes.
> ci: test coverage for ruby 3.1

- ext/nokogiri/xslt_stylesheet.c
- lib/nokogiri/xslt.rb
- test/test_xslt_transforms.rb
Along the way, rewrite this method, refactor the tests, and improve
the documentation.
Closes #2418
Yes!
No.
> fix: regression in XSLT.quote_params handling non-strings

- CHANGELOG.md
- ext/nokogiri/xslt_stylesheet.c
- lib/nokogiri/xslt.rb
- test/test_xslt_transforms.rb
Backport #2420 to v1.13.x.
Closes #2418.
> fix: regression in XSLT.quote_params handling non-strings (backport)

- CHANGELOG.md
- README.md
- lib/nokogiri/extension.rb
Closes #2427, providing a clearer error message on glibc incompatibility.
Also add aarch64-linux to the set of supported platforms, and note the
version of glibc required.
No
No
> fix: clearer error message on glibc incompatibility

- nokogiri.gemspec
- rakelib/extensions.rake
update to rake-compiler 1.1.8 which contains https://github.com/rake-compiler/rake-compiler/pull/199, and remove the workaround for ruby required versions
Test coverage was originally introduced in 56b89d9 when the workaround was introduced.
No.
> ext(package): update to rake-compiler 1.1.8

- CHANGELOG.md
- ext/nokogiri/nokogiri.c
- lib/nokogiri/xml/node.rb
- test/xml/test_document.rb
- test/xml/test_document_encoding.rb
#752 reported a bug in serializing long UTF-16 documents.
The serialized document was corrupted when we were not being careful to use the document encoding while collecting multiple libxml2 buffer flushes. As a result, an incorrect number of bytes were written, including some garbage, as well as incorrect BOMs appearing in the middle of the serialized document.
This fix works by setting the external encoding on the StringIO object used to collecting the serialized stream, and then using that encoding when constructing intermediate strings from libxml2's buffer.
Yes!
This fixes the CRuby/libxml2 behavior which now …
> Correctly serialize UTF-16 documents that are longer than libxml2's internal string buffer

- CONTRIBUTING.md
- LICENSE-DEPENDENCIES.md
- rakelib/format.rake
- automate regeneration of tables-of-contents in LICENSE-DEPENDENCIES.md and CONTRIBUTING.md with a `format:toc` rake task
- improve CONTRIBUTING.md by adding a section on branch and release management
> doc: table of contents automation and CONTRIBUTING updates

- lib/nokogiri/xml/node.rb
- test/xml/test_document_encoding.rb
This PR simplifies the fix submitted in #2434, there's no need to explicitly specify the encoding in the IO open mode string.
It's a refactor, existing test coverage is fine. Note in particular the test added in #2434.
No.
> refactor: simplify fix from 2e260f5 / #2434

- CHANGELOG.md
- gumbo-parser/src/parser.c
- gumbo-parser/test/parser.cc
In the usual course of events, a `</form>` tag does _not_ pop all of the
nodes off the stack of open elements until a `form` element is popped.
Instead, it only removes the `form` element itself. Popping in the
normal fashion will flush any text node that is in the process of being
constructed.
This commit adds that flushing when `</form>` is encountered as well.
Fixes: #2450
#2450 
Yes. The Gumbo parser's test suite was updated to test for this.
It affects the C implementation's HTML5.
> Correctly handle text in form elements

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/upstream.yml
Currently, Actions CI is using non-standard branches for Ruby setup.  When the branches were used, changes had not been merged to the various actions repos (MSP-Greg/setup-ruby-pkgs, ruby/setup-ruby).  Updates have been merged.
When tested in my fork, updated CI workflows ran as they do in main
na, as only workflow files have been changed
> ci: Change Ruby setup to standard

- appveyor.yml
We use Appveyor to test 32-bit windows, and it wasn't previously updated to test Ruby 3.1.
Yes.
> ci: test ruby 3.1 on appveyor

- .github/workflows/ci.yml
- .github/workflows/upstream.yml
- scripts/compile-against-libxml2-source
As discussed in #2449, there's little value to running the "upstream" CI jobs on every commit or pull request. This PR moves them to run a few times a week on a timer.
> Run "upstream" CI periodically

- patches/libxml2/0010-Revert-Different-approach-to-fix-quadratic-behavior.patch
- test/html4/test_document.rb
Fixes #2461 by reverting the relevant upstream commit in libxml2.
Yes, this PR includes additional test coverage for start tag recovery by the HTML4 parser.
This keeps the HTML4 parser behavior identical in both CRuby and JRuby implementations (they diverged in v1.13.2 due to #2461).
> fix: revert libxml2 regression with HTML4 recovery (v1.13.x branch)

- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
The C extension didn't check whether memory allocations were successful (= `malloc`/`calloc` return a value other than `NULL`). In the rare case, that memory allocation fails, this leads to undefined behavior, which usually results in a segmentation fault.
This problem was discovered using the [static analyzer](https://gcc.gnu.org/onlinedocs/gcc/Static-Analyzer-Options.html) (`-fanalyzer`) of GCC.
There is no easy way to test this behavior, hence I omitted test cases.
If no more memory is available `rb_eNoMemError` is raised. As far as I can tell, it is not necessary to change the Java implementation, since Java …
> C: Check whether memory allocation was successful

- CHANGELOG.md
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
- suppressions/nokogiri_ruby.supp
- test/helper.rb
- test/test_xslt_transforms.rb
- test/xml/sax/test_parser.rb
- test/xml/test_document.rb
#2481 proposed cleaning up our local implementation of `vasprintf` and using it on all platforms; however this PR takes an alternative approach of removing calls to `vasprintf` in favor of using `rb_vsprintf` since we need to create Ruby String objects from all the errors being handled this way.
Some nice side effects:
- ~TruffleRuby should like this better, since Sulong was missing functionality around varargs~
- we no longer have to do platform-specific detection of `vasprintf` at compile time
Note also that this PR is based on #2480, so that should be considered before this one.
Yes! Some of the error handling code did not have good, or any, coverage. Test coverage has been added in this PR. …
> remove calls to vasprintf

- test/css/test_css_integration.rb
- test/css/test_xpath_visitor.rb
#2492 asked about support for the CSS pseudo-class `:contains()`
This PR adds missing test coverage for that selector as well as `:gt()`.
/cc @walterdavis
Ya
No behavior change
> test: add coverage for some css pseudo-classes

- test/test_version.rb
pend the LIBXML_LOADED_VERSION test on freebsd
see #2506 for more context
> test: pend the LIBXML_LOADED_VERSION test on freebsd

- lib/nokogiri/html4/document.rb
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/processing_instruction.rb
- test/html4/test_document_encoding.rb
HTML4 document encoding detection improvements.
Yes, there is a quick-and-dirty test for the `v1.13.x` branch, see #2448 for a more complete perf testing approach that's on `main`.
No.
> improve encoding reader performance (backport to v1.13.x)

- test/test_version.rb
Closes #2506
essentially reverting 97be5d1 from #2507
> test: unpend the LIBXML_LOADED_VERSION test on freebsd

- ext/nokogiri/extconf.rb
- test/helper.rb
The test helper `pending` currently prints out the line number from `test/helper.rb`. This PR makes it print out the caller info.
Pending tests that are still erroring will be skipped with a message like:
```
Skipped:
Nokogiri::XML::SAX::TestParserContext#test_graceful_handling_of_invalid_types [/home/flavorjones/code/oss/nokogiri/test/helper.rb:263]:
pending TODO [/home/flavorjones/code/oss/nokogiri/test/xml/sax/test_parser_context.rb:84:in `test_graceful_handling_of_invalid_types']
```
and pending tests that start passing will fail with a message like:
```
Failure:
Nokogiri::XML::SAX::Parser#test_0006_handles invalid types gracefully [/home/flavorjones/code/oss/nokogiri/test/helper.rb:265]
Minitest::Assertion: pending test unexpectedly …
```
> fix test pending message

- CHANGELOG.md
- ext/java/nokogiri/Html4SaxParserContext.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/internals/ParserContext.java
- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/xml_sax_parser_context.c
- lib/nokogiri/html4/sax/parser.rb
- test/html4/sax/test_parser.rb
- test/html4/sax/test_parser_context.rb
- test/xml/sax/test_parser.rb
- test/xml/sax/test_parser_context.rb
HTML4::SAX::Parser, HTML4::SAX::ParserContext, XML::SAX::Parser, and XML::SAX::ParserContext now properly check the types of the arguments to their various constructor methods.
Previously, passing arguments of unexpected types might cause a segfault or other less-obvious exceptions.
Yes! Added test coverage for these cases.
Both the C and Java implementations have been updated to behave identically in this circumstance.
> SAX::Parser constructors check types

- ext/java/nokogiri/Html4SaxParserContext.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/internals/ParserContext.java
- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/xml_sax_parser_context.c
- lib/nokogiri/html4/sax/parser.rb
- test/html4/sax/test_parser.rb
- test/html4/sax/test_parser_context.rb
- test/xml/sax/test_parser.rb
- test/xml/sax/test_parser_context.rb
HTML4::SAX::Parser, HTML4::SAX::ParserContext, XML::SAX::Parser, and XML::SAX::ParserContext now properly check the types of the arguments to their various constructor methods.
Previously, passing arguments of unexpected types might cause a segfault or other less-obvious exceptions.
This is a backport of #2529 
Yes! Added test coverage for these cases.
Both the C and Java implementations have been updated to behave identically in this circumstance.
> SAX::Parser constructors check types (v1.13.x branch)

- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
Commit 3831a00 replaced `vasprintf` calls with `rb_vsprintf`, however that caused gcc to start emitting warnings because of the `-Wsuggest-attribute=format` flag.
This PR introduces a `PRINTFLIKE_DECL` macro to declare the gnu_printf format attribute for some functions to quash those warnings.
It also replaces the `NORETURN` macro (which will come from ruby.h`) with `NORETURN_DECL` that doesn't take an argument, because that syntax is easier to combine with `PRINTFLIKE_DECL` IMHO.
No tests necessary.
No behavior change.
> ext: declare gnu_printf format attribute for some functions

- .cross_rubies
- .github/workflows/gem-install.yml
- CHANGELOG.md
- README.md
- rakelib/extensions.rake
Recently https://github.com/sparklemotion/nokogiri/issues/2466 described the installation experience of a user on the arm/v7 platform, which compiles from source. The user compared this experience against the precompiled native gem experience on other platforms.
rake-compiler-dock supports this architecture since v1.2.0, so this PR adds it as an experimental platform
This PR also adds a CI job to test the native gem under qemu.
Closes #2467
Yes
No behavior change
> arm-linux native gem support

- ext/nokogiri/gumbo.c
- lib/nokogiri/html5/document.rb
- test/html4/sax/test_parser.rb
- test/html4/sax/test_parser_text.rb
- test/html4/sax/test_push_parser.rb
- test/html4/test_attributes.rb
- test/html4/test_attributes_properly_escaped.rb
- test/html4/test_builder.rb
- test/html4/test_comments.rb
- test/html4/test_document.rb
- test/html4/test_document_encoding.rb
- test/html4/test_document_fragment.rb
- test/html4/test_element_description.rb
- test/html4/test_node.rb
- test/html4/test_node_encoding.rb
- test/html5/test_api.rb
- test/html5/test_monkey_patch.rb
- test/test_html.rb
- test/test_memory_leak.rb
- test/test_nokogiri.rb
- test/xml/test_node.rb
- test/xml/test_node_reparenting.rb
- test/xml/test_xpath.rb
See #2331 for context. I want to start getting things in place to make it possible to seamlessly switch to HTML5 parsing by default on supported platform. Part of this will require subclassing behavior to work properly (i.e., as Loofah expects it to, where a subclass of Nokogiri::HTML5::Document will return the appropriate subclass from `.parse`).
This PR introduces that subclassing behavior, and makes all the HTML4 tests explicitly use `HTML4` instead of `HTML`.
Note that `Gumbo.parse` now takes an additional argument, which is the class that should be used for the new document. `Gumbo.parse` is considered to be an internal-only API and so this shouldn't be a breaking change, but it might be worth mentioning in release notes just in case. …
> html5 subclassing

- test/helper.rb
For example, ruby 3.0 on Debian ppc64el architecture does not support GC
compaction. When running the tests, every 20th test crashes like this:
> ```
> Error:
> Minitest::Result#test_parsing_attribute_namespace:
> NotImplementedError: Compaction isn't available on this platform
>     <internal:gc>:213:in `compact'
>     /home/terceiro/ruby-nokogiri-1.13.5+dfsg/test/helper.rb:123:in `teardown'
> ```
> test/helper.rb: ignore GC compaction on unsupported platforms

- CHANGELOG.md
- ext/java/nokogiri/XmlDocument.java
- ext/nokogiri/xml_document.c
- test/xml/test_c14n.rb
`Document#canonicalize` now raises an exception if `inclusive_namespaces` is non-nil and the mode is inclusive, i.e. XML_C14N_1_0 or XML_C14N_1_1.
`inclusive_namespaces` can only be passed with exclusive modes, and previously this silently failed.
Yes, coverage has been added in this PR.
Both the C and Java implementations have been updated.
> fix: Document#canonicalize raises exception for incompatible modes

- nokogiri.gemspec
Lock the version of the development dependency `rubocop-shopify`, because
a) we can't generate the ruby 2.6 ci image with the latest version of the gem (which dropped support for ruby <2.7).
b) we kept getting CI breaks from eager updating, anyway
At some point, I'd like to move all our development dependencies into the Gemfile, tighten the dependencies, and have dependabot send PRs for updates.
N/A
N/A
> dev: lock rubocop-shopify dependency for now

- lib/nokogiri.rb
I don't think we need to require `rbconfig` anymore.  Looks like it was
introduced in 544b431e5ac6a12369ddc6fb01d2a4b06dbd534d so that we could
check the host's OS back when we were using FFI with Nokogiri.  That
check got removed in 6eae89695cf875fbe15fe57241ba387dd79d91c8, so I
think we can remove this require now.
> Remove rbconfig require

- ext/nokogiri/gumbo.c
- lib/nokogiri/html5/document.rb
- lib/nokogiri/html5/document_fragment.rb
- test/html5/test_api.rb
Closes #2583
HTML5::Document#url now matches the behavior of HTML4::Document and XML::Document. Previously this method always returned `nil`.
I've also improved the documentation for HTML5::Document.
Yes!
This affects the behavior of HTML5::Document which only exists in the C implementation today.
> fix: HTML5::Document#url returns the URL passed to the parser

- ext/nokogiri/extconf.rb
- ext/nokogiri/gumbo.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_attr.c
- ext/nokogiri/xml_attribute_decl.c
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_dtd.c
- ext/nokogiri/xml_element_decl.c
- ext/nokogiri/xml_entity_decl.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_text.c
- ext/nokogiri/xml_xpath_context.c
- suppressions/nokogiri_ruby.supp
- test/test_compaction.rb
This PR is an attempt to fix compaction issues from #2578.  We've split the PR in to 3 commits.
The first commit consistently sets a mark function on the xml node.  We need this because we need to provide a static struct to `TypedData_Wrap_Struct`.
The second commit introduces a helper function for unwrapping xml nodes.  Unfortunately, xml nodes use a union type, and subclasses want to unwrap the type in to different things, so we had to extract a function that would unwrap the nodes correctly.
The third commit actually fixes compaction by adding a callback for updating references.
Fixes #2578
> Fix compaction on nodes

- .github/workflows/gem-install.yml
- ext/nokogiri/extconf.rb
- ext/nokogiri/gumbo.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_attr.c
- ext/nokogiri/xml_attribute_decl.c
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_dtd.c
- ext/nokogiri/xml_element_decl.c
- ext/nokogiri/xml_entity_decl.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_text.c
- ext/nokogiri/xml_xpath_context.c
- nokogiri.gemspec
- suppressions/nokogiri_ruby.supp
- test/test_compaction.rb
> Fix compaction on nodes (backport to v1.13.x)

- .github/workflows/gem-install.yml
- nokogiri.gemspec
- scripts/test-gem-build
Recently, while trying to release v1.13.7, I had to debug an issue that ended up being caused by the bug fixed in https://github.com/rake-compiler/rake-compiler-dock/pull/67/files
Despite using rake-compiler-dock v1.2.2 in the Gemfile, the CI pipeline was still using the OCI image tagged `1.2.0` which still contained that bug.
This PR will make sure the CI pipeline is always using the same version as the Gemfile/gemspec. Additionally let's make sure we're pinned to a specific version of rake-compiler-dock to ensure we opt into any new behavior.
N/A
N/A
> ci: ensure pipeline uses the RCD IMAGE_VERSION for containers

- ext/nokogiri/xml_node.c
- lib/nokogiri/html5.rb
- lib/nokogiri/html5/node.rb
- test/html5/test_serialize.rb
HTML 5 serialization was previously done entirely in Ruby.
The Ruby code is slow. This reimplements the serialization in C.
Reencoding happens after UTF-8 serialization.
Fixes: #2569
#2569
Not yet.
It should speed up the serialization of HTML 5 without a change in behavior.
> Implement HTML 5 serialization in C

- lib/nokogiri/html5/document.rb
- test/html5/test_api.rb
Fixes: #2551
Yes.
It changes the C HTML5 visible behavior (but not implementation) to match the C HTML4 implementation. I don't know what the Java implementation does.
> Use `body` as the context element for `Document#fragment`

- .github/workflows/downstream.yml
- ext/java/nokogiri/XmlReader.java
- ext/java/nokogiri/internals/ReaderNode.java
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
- lib/nokogiri/xml/reader.rb
- test/xml/test_reader.rb
This is a proposed fix for #2598, see that issue for an extended explanation of the problem.
This PR implements "option 2" from that issue's proposed solutions:
- introduce a new `Reader#attribute_hash` that will return a `Hash<String ⇒ String>` (instead of an `Array<XML::Attr>`)
- deprecate `Reader#attribute_nodes` with a plan to remove it entirely in a future release
- re-implement `Reader#attributes` to use `#attribute_hash` (instead of `#attribute_nodes`)
After this change, only applications calling `Reader#attribute_nodes` directly will be running the unsafe code. These users will see a deprecation warning and may use `#attribute_hash` as a replacement.
I think it's very possible that `Reader#attribute_hash` won't meet the needs of …
> fix: XML::Reader XML::Attr garbage collection

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- ext/java/nokogiri/XmlReader.java
- ext/java/nokogiri/internals/ReaderNode.java
- ext/nokogiri/extconf.rb
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
- lib/nokogiri/xml/reader.rb
- test/xml/test_reader.rb
Closes #2598.
Backport of #2599 to v1.13.x for a patch release. See that issue for details.
> fix: XML::Reader XML::Attr garbage collection (backport to v1.13.x)

- suppressions/nokogiri_ruby.supp
Update CI memleak suppressions, related to:
- https://github.com/Shopify/ruby_memcheck/issues/6
- https://github.com/sparklemotion/nokogiri/issues/2389
> ci: suppress memleak reports from gc stack_chunk_alloc

- .github/workflows/ci.yml
- .github/workflows/gem-install.yml
- .github/workflows/generate-ci-images.yml
- .github/workflows/upstream.yml
- nokogiri.gemspec
- rakelib/docker.rake
Because of https://github.com/jruby/jruby/issues/7262 let's pin jar-dependencies to 0.4.1
Because of https://github.com/ruby/setup-ruby/issues/358 let's explicitly opt into latest bundler in all CI jobs
> ci: fix development dependency breakage

- CHANGELOG.md
- dependencies.yml
- ext/nokogiri/extconf.rb
libxslt just release v1.1.36. Full change log is at https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.36. This was a lockstep release with libxml 2.10.0 (see https://github.com/sparklemotion/nokogiri/pull/2625) and contains performance improvements and bugfixes.
Existing coverage should be adequate.
Potentially could change behavior in the CRuby implementation, but tests should provide coverage. We've been [regularly running CI against upstream master](https://github.com/sparklemotion/nokogiri/actions/workflows/upstream.yml).
> dep: update libxslt to v1.1.36

- CHANGELOG.md
- Gemfile
- ext/java/nokogiri/XmlNodeSet.java
- rakelib/format.rake
- rakelib/test.rake
- test/xml/test_node_set.rb
fix: NodeSet#[] raises a TypeError on invalid params
Previously this was raising a Java exception
Closes #2211
Yes.
The Java implementation now matches the C implementation.
> [jruby] NodeSet#[] raises TypeError when passed invalid param type

- CHANGELOG.md
- dependencies.yml
Closes #2627
Closes #2635 
Existing coverage should be sufficient.
Updating the C libraries, so, maybe? This is why we have tests :joy:
> dep: upgrade to libxml 2.10.1 and libiconv 1.17

- lib/nokogiri/xml/sax/parser.rb
- test/xml/sax/test_parser.rb
encoding set during initialisation of sax parser gets replaced to ASCII when parsing.
Fix: check if encoding has already been set.
> Do not override encoding set during initialisation

- CHANGELOG.md
- ext/nokogiri/xml_xpath_context.c
- test/xml/test_xpath.rb
See #2147 for context and deprecation roadmap.
Yes.
The CRuby implementation will now support the same XPath query syntax as JRuby.
> feat(cruby): custom XPath functions support `nokogiri` namespace

- test/xml/test_schema.rb
#783 describes an issue with JRuby schema validation when passed a blank document.
This introduces a test that's marked "pending" for JRuby to capture the issue.
> test: pending test for JRuby schema validation issue

- ext/java/nokogiri/XsltStylesheet.java
Should unblock compilation issue with older Xalan versions (https://github.com/sparklemotion/nokogiri/pull/2632).
Using the `TransformerImpl` (internal) class from Xalan is avoided.
Existing tests cover the serialization feature.
JRuby only and should be considered a simple refactoring change - wout side-effects.
> [jruby] avoid relying on transformer internals

- CHANGELOG.md
- lib/nokogiri/xml/node_set.rb
- test/html4/test_document_fragment.rb
Fix empty fragment encoding, and improve test coverage around fragment encoding
Closes #2649
Yes!
No.
> fix: empty fragment encoding

- lib/nokogiri/xml/parse_options.rb
Clearly indicate which options are unsafe for untrusted documents.
Related to #1582
N/A
N/A
> doc: clarify ParseOptions

- ext/nokogiri/xml_xpath_context.c
- test/xml/test_document.rb
Avoid raising Ruby exceptions from within libxml2 error callbacks while evaluating xpath queries in `xmlXPathEvalExpression`. Instead, collect them in an array and raise an exception after `xmlXPathEvalExpression` returns.
Partly addresses #1610.
I've also cleaned up xml_xpath_context.c a bit while I was in there.
Existing test coverage is appropriate.
The only behavior change is for C to match JRuby's exception type when an xpath function can't be found. The  test has been updated to remove the conditional on engine.
> improve exception handling in xpath evaluation

- dependencies.yml
- test/xml/sax/test_parser.rb
update libxml2 to v2.10.3 from v2.10.2
See https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.3
Related to #2665 
Existing coverage is fine.
Note the new libxml2 behavior around CDATA nodes longer than 10MB.
> dep: update libxml2 to v2.10.3

- lib/nokogiri/xml/node.rb
As part of #2655 I realized that although `Node#inner_html=` is essentially an alias for `#children=` and parses string arguments using the appropriate document fragment parser (XML or HTML4 or HTML5, as implemented at #2388), the name is potentially misleading.
Closes #2655
> doc: improve `Node#inner_html=` docs

- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
- rakelib/debug.rake
- test/test_compaction.rb
- test/test_memory_leak.rb
Under certain circumstances, GC compaction will cause a segfault when accessing wrapped `XML::Namespace` objects.
See previous similar work at #2579 
This fix, if merged, should be backported to v1.13.x and released as a bugfix.
Yes, repro test is included thanks to @eightbitraptor and @peterzhu2118
No functional behavior changes.
> fix: namespace nodes behave with compaction

- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_node.c
- test/test_compaction.rb
- test/test_memory_leak.rb
> fix: namespace nodes behave with compaction (backport to v1.13.x)

- dependencies.yml
- ext/nokogiri/extconf.rb
See #2626 for context. This change updates precompiled native gems to use zlib 1.2.13.
This is a backport of #2670
> dep: update zlib to v1.2.13 (backport to v1.13.x)

- .github/workflows/ci.yml
GitHub is [deprecating the use of `set-output`](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), so this PR removes the warning by updating the same logic to the new sequence.
> Modernize rcd_image_version retrieval

- test/helper.rb
As of version 1.2.0, ruby_memcheck no longer needs the call to GC.start at exit. It will do it automatically.
N/A.
No.
> Remove GC.start required by ruby_memcheck

- CHANGELOG.md
- gumbo-parser/src/parser.c
Avoid parse error around whitespace in `template` and update to the latest html5lib-tests.
See:
- https://github.com/whatwg/html/issues/7922
- https://github.com/whatwg/html/pull/8271
- https://github.com/html5lib/html5lib-tests/pull/150
- https://github.com/html5lib/html5lib-tests/pull/151
Updating to the latest html5lib-tests
N/A
> html5: remove parse error around whitespace in template

- CHANGELOG.md
- ext/nokogiri/extconf.rb
Related to #2689.
No, not sure how to test this in an automated way without adding dispropotionate complexity.
@stevecheckoway any chance you can try this out on your system?
N/A
> ext: tell clang to ignore unknown options

- CHANGELOG.md
- lib/nokogiri/html5.rb
- test/html5/test_encoding.rb
I found an interesting test failure while playing with upgrading Mastodon to use the HTML5 parser that was caused by case-sensitivity in the HTML5 encoding detection.
Yes.
N/A
> fix: html5 encoding detection case insensitive re: meta tag

- ext/nokogiri/gumbo.c
- test/html5/test_api.rb
Calling `fragment()` on an `annotation-xml` element crashes.
```ruby
require 'nokogiri'
doc = Nokogiri::HTML5.parse('<!DOCTYPE html><math><annotation-xml encoding="text/html" /></math>')
a_xml = doc.xpath('//math:annotation-xml')[0]
frag = a_xml.fragment('<p>')
```
Yes. This functionality was not previously exercised by tests. It is now.
It fixes a crash that's only present in the C implementation.
> Fix crash when calling fragment on annotation-xml elements

- ext/nokogiri/nokogiri.h
Fixes #2696
Unfortunately there's no failing test, but #2696 makes the argument that this is an improvement, and existing native gem CI pipelines should make sure nothing breaks.
No.
> fix: include ruby/defines.h early to avoid _GNU_SOURCE confusion

- ext/nokogiri/extconf.rb
- ext/nokogiri/gumbo.c
- ext/nokogiri/html4_document.c
- ext/nokogiri/html4_entity_lookup.c
- ext/nokogiri/xml_attribute_decl.c
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_element_content.c
- ext/nokogiri/xml_element_decl.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
There are multiple integer loss of precision warnings. 
There are three categories of warnings fixed.
1. Most are spurious warnings where we cast an `int` to a `long` and then use `INT2NUM` rather than just avoiding the cast);
2. With the HTML5 parser and a file containing an error on line number 2^31 or higher (or column number 2^31 or higher), the returned errors will have the wrong line (resp. column) number.
3. Node pointers are cast to a `int`s and used as ids for node comparison. Two different nodes could have the same least significant 32 bits in their pointers which would cause them to compare equal.
I added no test coverage. The warnings in the first category are harmless. The ones in the …
> Fix loss of precision warnings

- CHANGELOG.md
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/node_set.rb
- test/html5/test_api.rb
- test/xml/test_node.rb
- test/xml/test_node_set.rb
Duplicating an instantiated Node is significantly faster than re-parsing a string for multiple invocations.
Closes #2657
Here's a benchmark:
```ruby
#! /usr/bin/env ruby
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "benchmark-ips"
gem "nokogiri", path: "."
end
require "nokogiri"
require "benchmark/ips"
HTML = "<body><section>" + ("<span>foo</span>" * 100) + "</section></body>"
def wrap
doc = Nokogiri::HTML::Document.parse(HTML)
doc.at_css("section").children.each do |child|
child.wrap("<p>")
end
doc
end
def new_feature_reparent
doc = Nokogiri::HTML::Document.parse(HTML)
wrapper = doc.create_element("p")
doc.at_css("section").children.each do |child|
child.wrap(wrapper)
end
doc
end
Benchmark.ips do |x|
x.warmup = 0 …
```
> feat: {Node,NodeSet}#wrap accept a Node argument

- CHANGELOG.md
- lib/nokogiri/css.rb
- test/css/test_css.rb
Closes #2700
Previously this code
```ruby
Nokogiri::HTML5.parse("<div></div>").css("")
```
would raise:
```
nokogiri/css/parser_extras.rb:86:in `on_error': unexpected '$' after '' (Nokogiri::CSS::SyntaxError)
```
Now:
```
nokogiri/lib/nokogiri/css.rb:46:in `xpath_for': empty CSS selector (Nokogiri::CSS::SyntaxError)
```
which I think we can all agree is clearer. The previous exception came from the bowels of `racc` and I timed out after digging into it for about 20 minutes.
Yes!
No.
> feat: better exception message when a CSS selector is empty

- .github/workflows/upstream.yml
- test/helper.rb
- test/html4/test_attributes.rb
- test/html4/test_document.rb
- test/html4/test_node.rb
See https://gitlab.gnome.org/GNOME/libxml2/-/commit/76d6b0d768d4e60a2d2844d55def120257ab6c6e
As of that commit, serialized attributes no longer escape double quotes.
Updating existing tests here to reflect the small underlying serialization behavior change.
This is a test-only change to ensure we handle the upstream C implementation when it is released.
> update tests to handle upstream libxml2

- .github/workflows/ci.yml
Addressing Github Actions warnings about Node 12:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
I had previously done this in #2669 (37325aa), but then accidentally re-introduced @v2 in #2659 (f0bf5d6).
> ci: update to actions/checkout@v3

- test/html5/test_tree_construction.rb
exercise fragment construction with a context Element, in addition to the existing tests that use the context element name
Closes #2697
Before:
`4191 tests, 58094 assertions, 0 failures, 0 errors, 17 skips`
After:
`4385 tests, 60489 assertions, 0 failures, 0 errors, 17 skips`
> test: exercise fragment construction with a context Element

- Gemfile
- test/xml/sax/test_parser.rb
Getting CI green again, see https://github.com/ruby/setup-ruby/issues/409
> dep(dev): pin psych to v4 until v5 builds in CI

- nokogiri.gemspec
- test/xml/sax/test_parser.rb
Backport of #2716 to get CI green again.
> dep(dev): pin psych to v4 until v5 builds in CI (backport)

- CHANGELOG.md
- ext/nokogiri/xml_reader.c
- test/xml/test_reader.rb
`Reader#attribute_hash` does not behave the same way `Reader#attribute_nodes` behaved when parse errors are encountered.
For callers of `Reader#attributes` this restores the behavior from v1.13.7 before #2602.
See also the related change in #2714 which will land in v1.14.0 that raises a `SyntaxError` instead of returning `nil`.
Yes, coverage added.
The C and Java parsers differ in when they detect a syntax error in this case. libxml2 indicates an error when we try to expand a start tag that does not have a matching end tag, but xerces will defer the error until later. The tests reflect that difference.
> fix: XML::Reader#attribute_hash returns nil on error

- CHANGELOG.md
- ext/nokogiri/xml_reader.c
- test/xml/test_reader.rb
`XML::Reader` parsing errors encountered during `Reader#attribute_hash` and `Reader#namespaces` now raise an `XML::SyntaxError`.
Previously these methods would return `nil` and users would generally experience `NoMethodErrors` from elsewhere in the code.
Test coverage added.
The C and Java parsers differ in when they detect a syntax error in this case. libxml2 indicates an error when we try to expand a start tag that does not have a matching end tag, but xerces will defer the error until later. The tests reflect that difference.
> fix: XML::Reader error handling during xmlTextReaderExpand

- gumbo-parser/src/util.c
- gumbo-parser/src/util.h
Part of #2722, optimizing performance of gumbo.
Benchmarks from running show 7-11% improvements.
-  "test/files/GH_1042.html", # 650b
-  "test/files/tlm.html", # 70kb
-  "big_shopping.html", # 1.9mb
```
Comparison:
nodbg html5 parse 656:    16646.6 i/s
BASE_ html5 parse 656:    15545.9 i/s - same-ish: difference falls within error
with 99.0% confidence
Comparison:
nodbg html5 parse 70095:      271.1 i/s
BASE_ html5 parse 70095:      253.1 i/s - same-ish: difference falls within error
with 99.0% confidence
Comparison:
nodbg html5 parse 1929522:       14.9 i/s
BASE_ html5 parse 1929522:       13.4 i/s - 1.11x  (± 0.07) slower
with 99.0% confidence
```
> perf: avoid gumbo_debug function calls when GUMBO_DEBUG isn't def'd

- CHANGELOG.md
- ext/nokogiri/gumbo.c
- lib/nokogiri/html5/document.rb
- lib/nokogiri/html5/document_fragment.rb
- test/html5/test_quirks_mode.rb
Fixes #2646.
This PR introduces:
- `HTML5::QuirksMode`, an enum
- `HTML5::Document#quirks_mode`
- `HTML5::DocumentFragment#quirks_mode`
It also changes the behavior of the fragment parser to use the parent document's quirks mode, and default to `NO_QUIRKS` in edge cases.
Yes!
The HTML5 parser is only supported in CRuby.
> fix: fragment context parsing

- ext/nokogiri/extconf.rb
Recently there have often been builds failing because they couldn't download the zlib tarball (primarily windows jobs).
Use github by default for zlib tarball, but allow folks to fall back to the canonical URL if they need to. Note that this presumes the tarballs are identical (and have the same checksum), which is true for 1.2.13.
> dep: use github by default for zlib tarball

- .github/workflows/downstream.yml
#2594 points out downstream breakage in the `nokogiri-xmlsec-instructure` gem.
Let's add it to the CI suite to prevent regression.
> ci: add xmlsec to the downstream tests

- .github/workflows/downstream.yml
skip downstream xmlsec test, because that gem doesn't support compaction and frequently segfaults
see https://github.com/instructure/nokogiri-xmlsec-instructure/pull/17
> ci: skip downstream xmlsec test

- ext/nokogiri/nokogiri.c
- test/xml/test_node.rb
A file-IO has no external_encoding by default, so that rb_to_encoding() fails with a TypeError.
This regression was introduces in commit 2e260f53e6b84b8f9c1b115b0ded85eebc8155d7.
Fixes #2752
> Fix writing to an IO with no external_encoding

- .github/workflows/ci.yml
- rakelib/extensions.rake
Trying out the new rake-compiler-dock OCI images from https://github.com/rake-compiler/rake-compiler-dock/pull/95
> ci: use the new rake-compiler-dock oci images

- lib/nokogiri/css/xpath_visitor.rb
- lib/nokogiri/xml/node/save_options.rb
- lib/nokogiri/xml/parse_options.rb
- lib/xsd/xmlparser/nokogiri.rb
- test/xml/node/test_save_options.rb
- test/xml/node/test_subclass.rb
- test/xml/test_parse_options.rb
Things declared in anonymous eval are always annoying to locate. (e.g. profling etc).
cc @flavorjones
> Get rid of anonymous eval calls

- .github/workflows/ci.yml
- Gemfile
- rakelib/extensions.rake
update to rake-compiler-dock 1.3.0 with official ruby 3.2 support. this is the final step for #2564
> dep: update to rake-compiler-dock 1.3.0

- gumbo-parser/src/error.c
- gumbo-parser/src/parser.c
Clang warns about casting `void *` to an enum. This cast is fine in this case so first cast to `intptr_t`.
This isn't a functional change so no tests were added. (I don't think we test for the absence of compiler warnings.)
No.
> Fix Clang warnings about casting void* to an enum

- Gemfile
Psych 5 no longer bundles libyaml which causes `bundle install` to fail on macOS which doesn't have libyaml and doesn't have an easy, standard way to install it.
One can use `bundle config set --local without rdoc` to disable installing the `psych` and `rdoc` (which depends on `psych`) gems.
Hopefully, this is only temporary and the upstream Psych team will produce a better way to handle this.
#2769
As this is a (hopefully temporary) workaround, rather than a supported configuration, I have not.
No.
> Move rdoc and psych into their own bundler group

- CHANGELOG.md
- Gemfile
- ext/nokogiri/nokogiri.c
- test/xml/test_document_encoding.rb
#2773 
Serializing documents now works again with pseudo-IO objects that don't support IO's encoding API (like rubyzip's `Zip::OutputStream`). This was a regression in v1.14.0 due to the fix for #752 in #2434, and was not completely fixed by #2753. [#2773]
Yes, existing coverage was extended to include JRuby, and new coverage was added for this case.
This restores CRuby behavior to parity with the previous behavior that matches JRuby.
> fix: serialization with pseudo-IO objects like Zip::OutputStream

- lib/nokogiri/xml/node_set.rb
- test/xml/test_node_set.rb
> fix: empty node set serialization when document encoding is nil

- CHANGELOG.md
- lib/nokogiri/xml/node_set.rb
- test/xml/test_node_set.rb
Backport of #2789 to v1.14.x
Fixes #2784
> fix: empty node set serialization when document encoding is nil (backport)

- CHANGELOG.md
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/internals/SaveContextVisitor.java
- lib/nokogiri/xml/node/save_options.rb
- test/html4/test_document.rb
On JRuby, serializing an HTML node or document without specifying save options (as with calling `#write_to`) would emit XML. Now this mimics the libxml2 behavior of emitting HTML.
This PR also contains a commit to close #2767 by making `SaveOptions#inspect` contain the names of the options set.
Yes!
Bringing the Java impl into agreement with CRuby impl.
> fix(jruby): serializing HTML with no save options emits HTML

- ext/nokogiri/xslt_stylesheet.c
The old `Data` API is soft deprecated since a long time. The `TypedData` API is a bit more strict and opens the door for compaction, write barriers, memsize, etc (they have to be opted individually)
Here I just do a very simple translation of a single type, so it's easy to review.
> Migrate Nokogiri::XSLT::Stylesheet to the TypedData API

- ext/nokogiri/html4_document.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_comment.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_document_fragment.c
- ext/nokogiri/xml_entity_reference.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_processing_instruction.c
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xslt_stylesheet.c
- test/test_memory_leak.rb
Ref: #2806
Paired with @byroot. First we created a `rb_data_type_t` and then used it with `TypedData_Get_Struct` everywhere we're unwrapping an `xmlDoc`.
Then we added a limited version of `dsize`, which counts all the children nodes of the document recursively.
This allows `ObjSpace.memsize_of` to be closer to reality:
```sh-session
$ ruby -rbundler/setup -rnokogiri -robjspace -e 'puts ObjectSpace.memsize_of(Nokogiri::XML(File.read("test/files/po.xml")))'                                                    
88
```
After the second commit:
```sh-session
$ ruby -rbundler/setup -rnokogiri -robjspace -e 'puts ObjectSpace.memsize_of(Nokogiri::XML(File.read("test/files/po.xml")))'                                                    
9144
```
We're missing other members in the struct, not sure …
> Migrate Nokogiri::XML::Document to the TypedData API

- ext/nokogiri/xml_reader.c
> Migrate XML::Reader to the TypedData API

- test/helper.rb
- test/test_compaction.rb
When I'm running the tests with Ruby 3.2 I can see a deprecation warning, this fixes it.
> Fix deprecated double_heap option to GC.verify_compaction_references under 3.2

- CHANGELOG.md
- ext/nokogiri/xml_element_content.c
- lib/nokogiri/xml/attribute_decl.rb
- lib/nokogiri/xml/element_content.rb
- lib/nokogiri/xml/element_decl.rb
- lib/nokogiri/xml/entity_decl.rb
- lib/nokogiri/xml/pp/node.rb
Improve output of inspect and pp for some classes: AttributeDecl, ElementContent, ElementDecl, and EntityDecl
These classes were either:
- inheriting `PP::Node` and overriding `#inspect` but not `#pretty_print`, or
- not inheriting `PP::Node` where they could be to simplify things
Additionally, `PP::Node#inspect` and `PP::Node#pretty_print` no longer munge the names of inspected attributes (e.g., `attribute_nodes` appears as-is instead of as `attributes`), and if there is only a single `inspect_attributes`, we omit the key name which makes the XML declarations' output nicer. 
Err, no, but these changes should only impact debugging.
**Does this change affect the behavior of either the C or the Java …
> dev: better pp and inspect

- CHANGELOG.md
- lib/nokogiri/html5/node.rb
- lib/nokogiri/xml/node.rb
- test/test_serialization_encoding.rb
Fixes #2774
The PR adds two tests that cover both setting encoding with a string and the `Encoding` class.
**Question**
I discovered that the html5 node `write_to` (`lib/nokogiri/html5/node.rb`) also doesn't support the `Encoding` class, is this something you'd like me to add as well? Where would be a good place to test this? I couldn't find any encoding tests for this class.
> fix: support Encoding class for xml write_to

- ext/nokogiri/html4_element_description.c
Ref: https://github.com/sparklemotion/nokogiri/issues/2808
Since it has no mark function, we can enable write barrier without changing any code.
cc @flavorjones @etiennebarrie
> Migrate HTM4::ElementDescription to TypedData

- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_xpath_context.c
See #2808.
Note that I chose to make a new public function, `noko_xml_node_set_unwrap`, to allow other files to unwrap node sets. This differs from the tactic adopted in #2807 / cb1557d0 which was to make public the data type.
We should probably decide which is the better approach and standardize on it.
cc @etiennebarrie @casperisfine
> ext: migrate NodeSet to TypedData api

- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/html4_sax_push_parser.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
Ref: #2808
We now rely on `TypedData_Make_Struct` to do the allocation instead of using `ruby_xcalloc` directly, and we use RUBY_TYPED_DEFAULT_FREE to let Ruby free it as well.
There's no mark function so we can enable RUBY_TYPED_WB_PROTECTED.
> Migrate XML::SAX::Parser to the TypedData API

- ext/java/nokogiri/NokogiriService.java
- ext/java/nokogiri/XsltStylesheet.java
- ext/nokogiri/xslt_stylesheet.c
- lib/nokogiri/xslt.rb
- suppressions/ruby.supp
- test/xslt/test_custom_functions.rb
After renaming the function in c75c0dce we need to update the suppression file. But while I was in here, I cleaned some things up:
- function name for `XSLT.register` is now `rb_xslt_s_register`
- improve the test coverage for XSLT custom functions
- add complete usage to the docstrings for XSLT custom functions
- remove the JRuby native stub for XSLT.register
Yes.
No behavior changes.
> cleanup: update memcheck suppression with correct function name

- CONTRIBUTING.md
- scripts/compile-against-libxml2-source
- test/xml/test_node.rb
See #2836 for more context. Upstream libxml2 is changing how namespaces are handled. For background see https://gitlab.gnome.org/GNOME/libxml2/-/commit/d7d0bc6581e332f49c9ff628f548eced03c65189
This PR updates the tests to handle both older and newer libxml2 behaviors. At some point, we will likely have to update downstream loofah and rails-html-sanitizer tests, but I'll wait for an official libxml2 release to do that.
Closes #2836 
The important change here is to preserve existing test coverage.
No behavioral changes are _introduced_, but when libxml2 2.11.0 finally ships with the relevant change, the behavior of …
> fix tests for upstream libxml2 handling of HTML4 namespaces

- .rubocop.yml
- Gemfile
Use `rubocop-packaging` to ensure Nokogiri continues to be easy to repackage.
> dep(style): rubocop-packaging

- .github/workflows/ci.yml
- CHANGELOG.md
- adr/2023-04-libxml-memory-management.md
- ext/nokogiri/nokogiri.c
This allows a user to opt into configuring libxml2 to use system `malloc` instead of ruby's `ruby_xmalloc` (which is the default on all platforms except windows using system DLLs).
This addresses a few problems:
- it's a workaround for environments affected by the Ruby bug described in #2785 and fixed in https://github.com/ruby/ruby/pull/7663
- it improves parsing performance by ~10-30%, and serialization performance by ~5-10%
Parsing benchmarks:
```
default memory html4 parse 656:    27145.8 i/s
ruby memory html4 parse 656:    24287.1 i/s - 1.12x  (± 0.04) slower
default memory html4 parse 70095:      605.9 i/s
ruby memory html4 parse 70095:      450.5 i/s - 1.34x  (± 0.13) slower
default memory html4 parse 681406:       73.7 i/s
ruby memory …
```
> feat: env var to control libxml2 memory management

- ext/java/nokogiri/XmlNode.java
- test/xml/test_node.rb
Fixes #2802 
On JRuby, `first_element_child` properly returns nil when only non-element children exist. Previously this NPEd.
Yes!
This brings the Java implementation into alignment with the C implementation.
> fix(jruby): first_element_child properly returns nil

- .gitmodules
- gumbo-parser/src/foreign_attrs.c
- gumbo-parser/src/foreign_attrs.gperf
- test/html5/test_tree_construction.rb
Partial fix for #2841
A test recently added upstream showed that the list of foreign attributes gumbo is adjusting needed to be updated. Specifically:
- add `xlink:arcrole`
- remove `xml:base`
(see https://html.spec.whatwg.org/multipage/parsing.html#adjust-foreign-attributes)
I've also pinned (for now) to my branch of html5lib-tests, and improved some of the error messages from the tree construction test wrapper.
This PR is all about the tests! :tada: 
The HTML5/gumbo functionality changed, but this does not exist in the Java implementation.
> gumbo: update adjusted foreign attributes

- dependencies.yml
- test/xml/test_node.rb
https://github.com/sparklemotion/nokogiri/issues/2851 update libxml2 to 2.10.4 from 2.10.3
and update a test which assumed a behavior change was going to go into 2.11.0 but ended up in this release
> dep: update libxml2 to 2.10.4 from 2.10.3

- ext/java/nokogiri/XsltStylesheet.java
- ext/java/nokogiri/internals/HtmlDomParserContext.java
- nokogiri.gemspec
Written while spiking on #2565, these commits are valuable and should be applied.
- address JRuby 9.4 deprecations
- simplify the jar handling in the gemspec
- remove some unused code
Existing test coverage is sufficient.
No behavioral changes.
> jruby: some cleanup / refactoring

- gumbo-parser/src/error.c
Gumbo tree constructions errors could be improved. In this PR we're adding punctuation, cleaning up whitespace, and naming the input tag.
If the message was:
> 1:13: ERROR: This tag isn't allowed here  Currently open tags: html, body, div, table.
it is now:
> 1:13: ERROR: Start tag 'svg' isn't allowed here. Currently open tags: html, body, div, table.
No tests exist for error message contents. This is a potential area we could improve in the future.
No behavioral changes other than the contents of the error message.
> Improve gumbo error messages during tree construction

- .github/workflows/upstream.yml
- ext/nokogiri/extconf.rb
- nokogiri.gemspec
- suppressions/ruby.supp
[libxml2 2.11.0 is failing windows builds](https://github.com/sparklemotion/nokogiri/pull/2866), and I think I probably could have caught the problem earlier if I was running the upstream builds on windows. This PR adds that integration testing.
libxml2 is also leaking memory, so this PR also adds `ruby_memcheck` testing on the upstream builds to try to detect these problems earlier.
> ci: upstream libxml2 testing: windows and ruby_memcheck coverage

- .github/workflows/downstream.yml
It looks like libxml2 master has broken something related to flagging nondeterministic schemas, and in particular is failing a test that was sent by the maintainers of ruby-saml a long time ago.
https://gitlab.gnome.org/GNOME/libxml2/-/commit/a06eaa6119ca5b296b8105dc8c9a34ed5fc1f338
Let's add some coverage for this project, so that we can know if and when libxml2 has broken something.
> ci: downstream integration testing of ruby-saml

- ext/nokogiri/nokogiri.c
fix: make sure libxml memory management is set early enough to avoid mistakenly calling xmlCleanupParser at exit on windows.
Note that calling `xmlParserVersion` will implicitly call `xmlInitParser` (via `xmlIsMainThread`) on systems with thread support.
Something may have changed in libxml2 since v2.10 around thread detection, because this didn't happen on earlier versions.
Anyway, what is happening with v2.11 is that `xmlInitParser` was being implicitly called before the memory management functions were set, meaning that these lines in parser.c were setting up an atexit memory cleaner:
if (xmlFree == free)
atexit(xmlCleanupParser);
which we know is a problem when we're using the ruby memory functions (on versions of ruby without the fix …
> fix: make sure libxml memory management is set early enough

- CHANGELOG.md
- gumbo-parser/src/parser.c
- test/html5/test_tree_construction.rb
feat: gumbo support for `<hr>` in `<select>`
- https://github.com/whatwg/html/issues/3410
- https://github.com/whatwg/html/pull/9124
- https://github.com/html5lib/html5lib-tests/pull/167
- https://github.com/html5lib/html5lib-tests/pull/168
The text added to the parser spec, under ["in select" insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inselect), is:
> A start tag whose tag name is "hr"
>
> If the [current node](https://html.spec.whatwg.org/multipage/parsing.html#current-node) is an [option](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element) element, pop that node from the [stack of open elements](https://html.spec.whatwg.org/multipage/parsing.html#stack-of-open-elements).
>
> …
> feat: gumbo support for `hr` in `select`

- Gemfile
update ruby_memcheck to 1.3.2 for the HUGE parse option fix. we had previously pinned to a PR branch.
https://github.com/Shopify/ruby_memcheck/releases/tag/1.3.2
> dep: update ruby_memcheck to 1.3.2

- .github/workflows/ci.yml
ci: drop valgrind checks on Ruby 2.7
because there seems to be a compaction bug in 2.7 that occasionally (rarely) gets triggered. it happens more frequently on windows, where we get segfaults, but sometimes valgrind catches it on linux, too.
e.g. https://github.com/sparklemotion/nokogiri/actions/runs/5063811163/jobs/9090845467?pr=2890#step:7:3154
```
== Invalid read of size 4
==780==    at 0x4908CB0: rb_gc_location (gc.c:8136)
==780==    by 0x4908CB0: rb_gc_location (gc.c:8127)
==780==    by 0x4A4CAD1: transient_heap_block_update_refs (transient_heap.c:831)
==780==    by 0x4A4CAD1: transient_heap_blocks_update_refs (transient_heap.c:847)
==780==    by 0x4A4CAD1: rb_transient_heap_update_references (transient_heap.c:859)
==780==    by …
```
> ci: drop valgrind on 2.7

- CHANGELOG.md
- ext/java/nokogiri/internals/SaveContextVisitor.java
- test/xml/test_node.rb
Closes #2559
This PR aims to solve issue #2559 in the Nokogiri project. After investigating the reported bug, it was identified that a NullPointerException occurs in the isHtmlScript and isHtmlStyle functions due to the inability to evaluate a null object in Java. The proposed solution involves adding a null check for the getParentNode() method's return value and logging an appropriate message if the parent node is null or does not match the expected tag name. A draft PR will be opened to implement these modifications and gather feedback for effectiveness.
As this is my first contribution to the project, I am uncertain about the appropriate location to include the corresponding test. However, I am …
> Serializing unparented HTML node on JRuby

- rakelib/css-generate.rake
```
$ be rake css:clean css:generate
rm -f lib/nokogiri/css/parser.rb
rm -f lib/nokogiri/css/tokenizer.rb
rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_mtime - lib/nokogiri/css/parser.rb
/home/flavorjones/code/oss/nokogiri/rakelib/css-generate.rake:7:in `mtime'
/home/flavorjones/code/oss/nokogiri/rakelib/css-generate.rake:7:in `needed?'
/home/flavorjones/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/home/flavorjones/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
Tasks: TOP => css:generate => lib/nokogiri/css/parser.rb
(See full trace by running task with --trace)
```
Our hacky file task needs to check for file existence before invoking `File.mtime`.
> dev: make sure css:generate works if target doesn't exist

- oci-images/nokogiri-test/mri-3.2.dockerfile
- oci-images/nokogiri-test/mri.erb
- oci-images/nokogiri-test/valgrind-from-source.step
Build mri-3.2 image with modern valgrind from source. Otherwise we run into DWARF5 format issues.
Closes #2909
> ci: build mri-3.2 image with modern valgrind

- suppressions/ruby.supp
See recent failures in upstream.yml, e.g. https://github.com/sparklemotion/nokogiri/actions/runs/5354163940/jobs/9710862134
Something changed recently, not sure if it's the compiler in CI, or the library, or a combination.
> ci: update memcheck suppression stack signature

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/xml/test_node_reparenting.rb
Closes #2916
Related to #283 and #595
Yes
Brings C in line with Java behavior.
> fix: do not dup text siblings in reparent_node_with(xmlAddChild)

- ext/java/nokogiri/XmlCdata.java
- ext/java/nokogiri/XmlSchema.java
- ext/java/nokogiri/XmlText.java
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_text.c
- test/xml/test_cdata.rb
- test/xml/test_schema.rb
- test/xml/test_text.rb
Hackerone user [nmb-se](https://hackerone.com/nmb-se?type=user) (Mikael Borg) reported an issue with typechecking arguments to `XML::Text.new` that could lead to a segfault.
This PR fixes the typechecking for `Text.new` as well as similar problems in `CDATA.new` and `Schema.from_document` in both the C and the Java implementations.
Related to #2825.
Yes!
Both implementations have been updated.
> Fix argument typechecking in Text.new, CDATA.new, and Schema.from_document

- CHANGELOG.md
- ext/nokogiri/xml_document.c
- test/test_memory_leak.rb
The `properties` field of an `xmlNode` element points to an `xmlAttr`. The first few fields of `xmlAttr` are in common with `xmlNode`, but not the `properties` field which doesn't exist in an `xmlAttr`.
The `memsize_node` function was passing an `xmlAttr` to a recursive call and then trying to do the same with the properties of that.
This led to type confusion and subsequent crashes.
Fixes: #2923
#2923
No. I don't know how to test this behavior. I'd appreciate help with this.
It fixes a crash in the C implementation.
> fix memsize_node when called on xmlAttrs

- gumbo-parser/src/error.c
Fix a typo in a human-readable error message. I spent a minute trying to figure out what an "Eng tag" was before I realized it was a typo :)
N/A
I think there is no Java analog of this code
> Fix typo in error message

- suppressions/ruby-3.3.supp
See #2928 and https://github.com/Shopify/ruby_memcheck/issues/23
> Add suppressions for ruby-3.3 inline cache references

- test/test_compaction.rb
The compaction tests crash a pretty good percentage of the time on Ruby 2.7 on windows, and the ruby core folks I talked to seem to think it's just a bug in compaction that's not going to get fixed.
Recent example of a crash: https://github.com/sparklemotion/nokogiri/actions/runs/5577141095/jobs/10189493278#step:7:3554
> ci: skip compaction tests on windows ruby 2.7

- .github/workflows/ci.yml
Add a CI job that regenerates the CSS parser and ensures the tests still pass
We don't exercise regenerating the lexer and parser very often and it would be nice to know if something is broken.
> ci: add a test job that regenerates the CSS parser

- Gemfile
- rakelib/test.rake
- test/helper.rb
Bumps ruby_memcheck to 2.0.0 which includes several breaking changes, one of which being that `binary_name` is no longer used in `RubyMemcheck.config`.
The new ruby_memcheck does not work well with SimpleCov, so it's disabled when ruby_memcheck is running. 
N/A.
No.
> Bump ruby_memcheck to 2.0.0

- CHANGELOG.md
- dependencies.yml
#2948
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.5
> dep: update libxml2 to v2.11.5

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/workflows/downstream.yml
- CHANGELOG.md
- CONTRIBUTING.md
- dependencies.yml
- ext/nokogiri/xml_document.c
- gumbo-parser/src/error.c
- suppressions/ruby.supp
- test/helper.rb
- test/test_memory_leak.rb
Backporting changes from:
- #2927
- #2924
- #2951
> backport updates and fixes to v1.15.x

- dependencies.yml
https://github.com/madler/zlib/releases/tag/v1.3
zlib is used to build a portable native (precompiled) gem
Closes #2960
> dep: update zlib to 1.3

- CHANGELOG.md
- lib/nokogiri/xml/attr.rb
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/document_fragment.rb
- lib/nokogiri/xml/namespace.rb
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/node_set.rb
Pattern matching was introduced as an experimental feature in v1.14.0 (see #2360 and #2523 for historical context).
Seeing downstream libraries adopt pattern matching for testing, as in https://github.com/rails/rails/pull/49003, means this is apparently useful enough to start using.
Let's end experimental support and make it a fully-supported feature in the next minor release, v1.16.0.
> feat: document official support for the pattern matching API

- test/xml/test_reader.rb
Upstream integration tests against libxml2 have been failing for a few days:
https://github.com/sparklemotion/nokogiri/actions/runs/6070705559/job/16467292067
Bisecting shows the behavior changed in libxml2 commit 53050b1d. Let's update the test to handle the different error message.
> test: update to handle upstream libxml2 error changes

- CONTRIBUTING.md
- Gemfile
- test/helper.rb
Faster test suite in development!
With NCPU=7 I can usually get the suite done in under 1.8 seconds on my laptop (inspired by [tldr](https://github.com/tendersearls/tldr))
Note that I dropped minitest-reporters because the two gems aren't compatible. I wasn't often using minitest-reporters features, anyhow.
> dev: use minitest-parallel_fork to speed up the suite

- Gemfile
- scripts/test-gem-file-contents
- scripts/test-gem-installation
- scripts/test-nokogumbo-compatibility
drop minitest-reporters, because even having it in the Gemfile messes with
minitest-parallel_fork, sigh.
For context, see:
- https://github.com/minitest-reporters/minitest-reporters/issues/247
- https://github.com/jeremyevans/minitest-parallel_fork/pull/3
Also, avoid psych 5.1.1 because of https://github.com/ruby/psych/issues/655
> dep: drop minitest-reporters, avoid psych 5.1.1

- Gemfile
- test/helper.rb
Revert commit https://github.com/sparklemotion/nokogiri/commit/59e4981a4fe68e1fa0372451f7950f6aebb2d8eb which avoided versions of psych that don't work on JRuby
> test: remove psych from gemfile

- test/xml/sax/test_push_parser.rb
Upstream libxml2 slightly changed encoding in recovery mode. Let's update the one failing test, which is intended to test general recovery mode error handling (and not encoding specifically) to be less specific  and forwards-compatible.
See:
- https://gitlab.gnome.org/GNOME/libxml2/-/issues/598
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/c082ef4644ce1f0af2a7c01e27c4a75f4d7d4feb
> fix: work around change in upstream libxml2 recovery

- CHANGELOG.md
- lib/nokogiri/css/xpath_visitor.rb
- test/css/test_css_integration.rb
- test/css/test_tokenizer.rb
- test/css/test_xpath_visitor.rb
Prevent errors when nokogiri is translating nth css to xpath and there are spaces in it. (E.g. `2n + 1` instead of `2n+1`)
Background: This came up because prettier started rewriting my email css from `li:nth-child(2n+1)` to `li:nth-child(2n + 1)` (which is perfectly valid in browsers) and this caused a `expected an+b node to have either + or - as the operator, but is " + " (ArgumentError)` error from https://github.com/Mange/roadie using nokogiri as part of inlining the css.
I believe so!
Since I only modified ruby code, I'm assuming not?
> fix: strip spaces from the operator when translating nth css to xpath

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- .github/workflows/upstream.yml
In CI, add ruby version to vendored libs cache key. The ruby 2.7 and 3.0 base images are old enough
to generate binaries that are not compatible with later base images, and vice versa. CI is failing
with libxml 2.12.0 in particular.
> ci: add ruby version to vendored libs cache key

- CHANGELOG.md
- dependencies.yml
update libxml to 2.11.5 and libxslt to 1.1.39
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.6
- https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.39
> dep: update libxml to 2.11.5 and libxslt to 1.1.39 (v1.15.x)

- CHANGELOG.md
- dependencies.yml
update libxml to 2.11.5 and libxslt to 1.1.39
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.6
- https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.39
(forward ported from #3025 / aa3208bc908aa69a940479b0cfb8ebe0162c8d0f)
> dep: update libxml to 2.11.5 and libxslt to 1.1.39 (main branch)

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- .github/workflows/upstream.yml
- dependencies.yml
- ext/nokogiri/extconf.rb
- ext/nokogiri/html4_sax_push_parser.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/test_global_handlers.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_syntax_error.c
- patches/libxml2/0012-fix-pthread-weak-references-in-globals.c.patch
#3031
This approach uses the patches submitted upstream at:
- https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/229
- https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/230
and turns off libxml2's thread-local storage feature, which is an issue when precompiling for musl on glibc systems. If and when we can build a separate musl native gem, we can revisit this decision.
> dep: libxml 2.12.0 upgrade (with libxml2 patch for weakref)

- CHANGELOG.md
- Gemfile
- rakelib/markdown.rake
The CHANGELOG.md file has had hyperlinked issues, PRs, and usernames since 0ac90334 / 2020-02-02 so that, when rendered on nokogiri.org, users could easily get to deeper information.
The downside, though, is that when the changelog snippets are copied to release notes, usernames aren't added to the "contributors" list for the release; and the release notes consumed by tools like dependabot and libraries.io don't really need the hyperlinks and it's sometimes just messy-looking.
So this PR removes the markdown linkification, and updates the CHANGELOG to just have bare references like `#1234` and `@flavorjones`.
Separately, I've added hoe-markdown to nokogiri.org in https://github.com/sparklemotion/nokogiri.org/commit/4fa918dd8c880994c8600c740eea …
> doc: remove hoe-markdown

- rakelib/test.rake
In development, I have the `NCPU` environment variable set to run tests in parallel with minitest-parallel_fork.
If I run `rake test:valgrind`, it will run multiple valgrind processes, which I don't want. This change limits the run to one process.
> test: don't run valgrind in parallel

- gumbo-parser/src/tokenizer.c
- test/test_memory_leak.rb
The fuzzer in #3007 found a memory leak when incomplete tags are encountered.
The repro added to the memory leak test suite is:
```html
<asdfasdfasdfasdfasdfasdfasdfasdfasdfasdf foo="bar
```
which will leak the tag name without this fix.
cc @stevecheckoway 
Yes, but added it to the memory leak suite which can only be run manually today (see #1603 for context on plans to improve it).
No functional change.
> fix: gumbo memory leak on abandoned tags

- scripts/test-gem-install
remove BUNDLE_CACHE_PATH hack. it looks like the jruby images no longer have the problem this was working around, and in the ruby:3.3.0-preview3 images, it interferes with built-in gems like stringio.
> ci: remove BUNDLE_CACHE_PATH hack

- .cross_rubies
- .github/workflows/ci.yml
- .github/workflows/generate-ci-images.yml
- Gemfile
- oci-images/nokogiri-test/mri-3.3-rc.dockerfile
- rakelib/docker.rake
Add precompiled native support for Ruby 3.3.
Note that this is still experimental! It is precompiling using a rake-compiler-dock prerelease that uses 3.3.0-preview3.
Testing against 3.3.0-preview3 or head
N/A
> ext: ruby 3.3 support

- CHANGELOG.md
- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.2
> dep: update libxml2 to v2.12.2

- CHANGELOG.md
- dependencies.yml
dep: update libxml2 to 2.12.3
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.3
> dep: update libxml2 to 2.12.3

- .github/workflows/ci.yml
- ext/nokogiri/nokogiri.h
- test/helper.rb
- test/test_memory_usage.rb
1. Restore the FreeBSD suite since the really offensive bug has been fixed
2. Change one memory_suite test to get more reps in
3. Change memory_suite to retry once when a leak is detected, to reduce false positives
4. Flag memory_suite as continue-on-error until we get more miles in with those tests
> ci/test: make some small improvements

- .github/workflows/ci.yml
- Gemfile
This PR has two changes
- build native gems using rake-compiler-dock v1.4.0.rc2 images using ruby 3.3.0-rc1
- test against ruby 3.3.0-rc1 in CI pipelines, including native gems
N/A
N/A
> ci: ruby 3.3.0 rc1

- ext/nokogiri/xml_sax_parser_context.c
- lib/nokogiri/xml/node.rb
Upstream libxml2 test failures.
- work around a bug/merge-request filed upstream [(on master) fix: support ASCII encoding on input buffers (!231) · Merge requests · GNOME / libxml2 · GitLab](https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/231)
- looks like in-context parser recovery now works? updating `XML::Node#parse` behavior to accommodate it in a backwards-compatible fashion. See #2092 which might be fixed in future versions of libxml2.
Making existing tests pass (or not segfault while we wait for an upstream fix).
No.
> handle upstream libxml2 changes

- test/test_xslt_transforms.rb
- test/xml/test_document.rb
- test/xml/test_schema.rb
Upstream error handling changed for XPath and IO in 954b8984 and 7e511f35.
This PR updates the tests to accept the new behavior.
Yes.
No behavioral changes.
> tests: updated for upstream libxml support

- CHANGELOG.md
- ext/nokogiri/xml_reader.c
- test/xml/test_reader_encoding.rb
default Reader node encoding to UTF-8 when it's not specified either as a method param or in the document
Fixes #2891
Yes, I've added coverage.
Yes, this updates the C implementation but does not update the Java implementation because Reader encoding is already wonky there in a few edge cases.
> fix(libxml): default Reader node encoding to UTF-8

- suppressions/ruby.supp
Upstream libxml valgrind (memcheck) test is failing. This callstack is changed on upstream master as of 2024-01-02.
This PR updates the suppression.
> ci: libxml2 callstack changed, so updating the suppression

- ext/nokogiri/xml_document.c
Compiling Nokogiri with older versions of GCC and centos causes the following error:
```
12:06:09 checking for gumbo_parse_with_options() in nokogiri_gumbo.h... yes
12:06:09 checking for xmlHasFeature()... yes
12:06:09 checking for xmlFirstElementChild()... yes
12:06:09 checking for xmlRelaxNGSetParserStructuredErrors()... yes
12:06:09 checking for xmlRelaxNGSetValidStructuredErrors()... yes
12:06:09 checking for xmlSchemaSetValidStructuredErrors()... yes
12:06:09 checking for xmlSchemaSetParserStructuredErrors()... yes
12:06:09 checking for rb_category_warning()... yes
12:06:09 checking for whether
12:06:09 -DNOKOGIRI_OTHER_LIBRARY_VERSIONS="\"libgumbo:1.0.0-nokogiri\"" is accepted as
12:06:09 CPPFLAGS... yes
12:06:09 creating Makefile …
```
> Allow compilation on older gcc versions

- .github/workflows/ci.yml
Realized today, because of some CI failures, that `mingw` is a ruby HEAD version (3.4.0 today), and we removed HEAD builds from the main CI pipeline back in 2021 (0fcbe1e4). The `upstream.yml` pipeline should be sufficient for testing ruby HEAD.
> ci: drop mingw from ci.yml because it's upstream ruby-head

- gumbo-parser/Makefile
- gumbo-parser/fuzzer/build-ossfuzz.sh
This pull request is needed so that i can update the oss-fuzz builder located at https://github.com/fuzzy-boiii23a/oss-fuzz/tree/master/projects/nokogiri which makes it much more seamless to add new fuzz targets in this nokogiri repo which will automatically be pulled by oss-fuzz and fuzzed instead of maintaining the fuzzer in the oss-fuzz repo.
> maintain oss-fuzz target building upstream

- CHANGELOG.md
- dependencies.yml
Update vendored libxml2 to v2.12.4.
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.4
> dep: update libxml2 to 2.12.4

- gumbo-parser/src/parser.c
- test/test_memory_usage.rb
When a token causes a node to be added to the DOM which increases the depth of the DOM to exceed the `max_tree_depth` _and_ the token needs to be reprocessed, memory is leaked. By delaying breaking out of the loop until after the token has been completely handled, this appears to fix the leak.
Fixes #3098
#3098
No! I don't know how to test this. Help is appreciated here.
Fixes a bug in the C implementation.
More investigation is needed to be sure it actually fixes the issue, however.
> Delay breaking out of the parse loop when max_tree_depth is hit

- test/xml/test_schema.rb
Upstream libxml2 (pre-2.13) is changing some error messages. Let's make the tests more robust around those messages.
> test: handle upstream libxml2 error message changes

- CHANGELOG.md
- patches/libxml2/0012-parser-Fix-crash-in-xmlParseInNodeContext-with-HTML.patch
- test/html5/test_api.rb
Apply upstream fix for #3112
- upstream bug report https://gitlab.gnome.org/GNOME/libxml2/-/issues/672
- upstream fix https://gitlab.gnome.org/GNOME/libxml2/-/commit/95f2a17440568694a6df6a326c5b411e77597be2
Fixes #3112
Yes
Only affects the C implementation.
> fix: apply upstream patch for in-context parsing

- ext/java/nokogiri/XmlDocument.java
- ext/java/nokogiri/XmlNode.java
- ext/java/nokogiri/XmlNodeSet.java
- ext/java/nokogiri/XsltStylesheet.java
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/node.rb
- lib/nokogiri/xml/node_set.rb
- lib/nokogiri/xml/pp/node.rb
- test/xml/test_document.rb
- test/xml/test_node.rb
- test/xml/test_node_set.rb
Fixes #316
Classes this PR updates:
Yes.
The fix applies to both implementations.
> Implement `#clone` correctly with respect to singleton classes

- .github/workflows/ci.yml
- ext/nokogiri/html4_element_description.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_element_content.c
- ext/nokogiri/xml_encoding_handler.c
- ext/nokogiri/xml_namespace.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_node_set.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_xpath_context.c
- ext/nokogiri/xslt_stylesheet.c
- test/xml/test_node.rb
- some minor C code cleanup
- improved testing around `Node#dup` that should have been in #3117
- update CI to use `download-artifact` and `upload-artifact` v4
Yes.
> cleanup: improve typeddata naming, improve `Node#dup` tests, action upgrade

- CHANGELOG.md
- lib/nokogiri/html5.rb
- lib/nokogiri/html5/builder.rb
- nokogiri.gemspec
- test/html4/test_builder.rb
- test/html5/test_builder.rb
Provide a Builder class that generates HTML5 documents.
The construction behavior is identical to HTML4::Builder, but HTML5 documents serialize according to the HTML5 standard (see `xml_node.c:output_node()`).
Added tests are a copied-and-modified version of the HTML4::Builder tests.
The Java implementation still does not support HTML5.
> feat: `Nokogiri::HTML5::Builder`

- gumbo-parser/src/parser.c
The parser is fragile and hitting the maximum tree depth has exposed several bugs. By treating this condition as if it is an EOF means that we're back in the normal parsing condition.
This does expose a weakness in Gumbo's design: A spec bug that results in skipped steps or failure to reprocess a token (or if we fail to implement the spec in such a way), then the result can be crashes. Not ideal.
Fixes: oss-fuzz-66107
oss-fuzz-66107
Nope! I'm sorry to punt on testing again but I didn't take the time to understand why this bug occurred so I didn't produce a minimal test case. Treating hitting the max depth as EOF just seemed like the best way to fix this whole class of bugs by turning the …
> Treat reaching the maximum parse depth as EOF

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/html4/test_attributes.rb
- test/html5/test_attributes.rb
Previously an exception would be raised, either "Unexpected node" or "Unsupported document node (2)" depending on the version of Nokogiri.
Fixes #3125
Yes.
HTML5 is only available in CRuby.
> fix: serializing an individual attribute in an HTML5 document

- test/xml/test_entity_reference.rb
Update tests to accept libxml2 master error message formatting that was changed in gnome/libxml2@67e475b7
N/A
Non-functional change
> test: handle libxml2 master error message formatting

- lib/nokogiri/xml/parse_options.rb
- rakelib/test.rake
We've long documented use of `HUGE` as a performance concern, when in reality it's a security concern. Large untrusted documents can cause OOM condition when the HUGE option is set.
Also: small developer change to lower verbosity of tests.
> doc: update `ParseOptions::HUGE` warning

- CHANGELOG.md
- dependencies.yml
- ext/nokogiri/xml_reader.c
Update to v2.12.6, see https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.6
This also makes a small change to `XML::Reader` to accommodate changes in how libxml2 reports the encoding of the Reader (see https://gitlab.gnome.org/GNOME/libxml2/-/issues/697 for details).
Closes #3148
> dep: update libxml 2.12.6 (branch v1.16.x)

- CHANGELOG.md
- dependencies.yml
- ext/nokogiri/xml_reader.c
Update to v2.12.6, see https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.6
This also makes a small change to `XML::Reader` to accommodate changes in how libxml2 reports the encoding of the Reader (see https://gitlab.gnome.org/GNOME/libxml2/-/issues/697 for details).
Closes #3148
(see related https://github.com/sparklemotion/nokogiri/pull/3151)
> dep: update libxml to 2.12.6 (main branch)

- CHANGELOG.md
- dependencies.yml
- scripts/test-gem-install
In https://github.com/sparklemotion/nokogiri/discussions/3146, @jamiemccarthy requested a security release on the v1.15.x branch to address CVE-2024-25062 which was fixed in v1.16.2 with an upgrade to libxml 2.12.5.
This PR attempts to upgrade the v1.15.x branch to [libxml 2.11.7](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.7) (from 2.11.6) which also addresses that vulnerability.
Also see related https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-xc9x-jj77-9p9j
> dep: update libxml to 2.11.7 (branch 1.15.x)

- CHANGELOG.md
- CONTRIBUTING.md
- ext/java/nokogiri/XmlCdata.java
- ext/nokogiri/xml_cdata.c
- ext/nokogiri/xml_comment.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_text.c
- rakelib/test.rake
- test/xml/test_cdata.rb
- test/xml/test_node_reparenting.rb
Closes #3156 and gets CI green against libxml2 master.
- CDATA.new no longer accepts `nil` for content
- update Node lifecycle to ensure the new libxml2 changes don't leak memory
- update tests to reflect improved text coalescing
See commit logs for deeper explanations on these changes.
Yes.
Both C and Java implementations no longer accept `nil` for CDATA content.
> support upstream libxml2 master up to gnome/libxml2@05c147c3

- test/xml/test_node_reparenting.rb
- test/xml/test_unparented_node.rb
Get upstream libxml2 integration tests passing again. gnome/libxml2@5bb84b47 changed behavior around text node coalescing again. See related #3161.
Notably, with this change, blank text nodes are no longer merged by `#add_{next,previous}_sibling`. See the tests originally added in 3c8c21ec back in 2009 for some context.
> libxml2 upstream tests (up to gnome/libxml2@5bb84b47)

- dependencies.yml
Update vendored zlib to 1.3.1.
See #3172 
Please note that Nokogiri is not vulnerable to the CVE patched in this version of zlib (which is related to the minizip library, which is not used by Nokogiri or its vendored libraries).
> dep: update to zlib 1.3.1 (main)

- dependencies.yml
Update vendored zlib to 1.3.1.
See #3172 
Please note that Nokogiri is not vulnerable to the CVE patched in this version of zlib (which is related to the minizip library, which is not used by Nokogiri or its vendored libraries).
> dep: update to zlib 1.3.1 (v1.16.x)

- test/xml/test_document_encoding.rb
Because I still want to pass the nokogiri's unit tests in a downstream nokogiri package on a Linux distro such as CentOS 10 Stream and RHEL 10, where we don't want to manage the rubyzip gem[1].
[1] https://rubygems.org/gems/rubyzip
We manage the nokogiri's downstream RPM package on a Linux distro such as CentOS 10 Stream and RHEL 10.
However, we don't want to manage the depending rubyzip gem RPM package in CentOS 10 Stream and RHEL 10. And we still want to pass the nokogiri's unit tests on the environments.
This PR is still to pass the nokogiri's unit tests where rubyzip is not maintained.
This PR is just to make a test case optional. So, it doesn't affect the test coverage.
**Does this change …
> Make a test depending on the rubyzip gem optional.

- test/xml/test_entity_reference.rb
gnome/libxml2@b717abdd makes undeclared entities a warning where it used to be an error
I'm opting to leave the JRuby implementation as-is. We can change it later if anybody requests it.
> test: update tests to reflect upstream libxml2 entity references

- .github/workflows/ci.yml
Add arm64-darwin coverage using macos-14. Also, pin the x86_64-darwin test to macos-13.
See flavorjones/ruby-c-extensions-explained#30 for more context.
> ci: add arm64-darwin coverage using macos-14

- ext/nokogiri/extconf.rb
#3160
Note I also have branches that fix this on v1.16.x and v1.15.x, but I wanted to make sure I actioned feedback in one place before I opened additional MRs.
Also note that Nokogiri doesn't seem to honor variables passed as gem configuration args, and I didn't add that here because I'm not entirely sure what the "canonical" way to do this is with mkmf/mini_portile. In other situations where I need to provide the toolchain (rdkafka/karafka-rdkafka), there seems to be no special code to convert `FOO=BAR` to an env var.
That said, it's not actually necessary in my case because using `AR` and `LD` from `RbConfig` is sufficient. So one might say if you need to do something different from that, maybe it's actually a good thing that you would …
> Make extconf.rb honor AR and LD variables in addition to CC

- .github/workflows/ci.yml
- CHANGELOG.md
- dependencies.yml
Vendored libxml2 is updated to address CVE-2024-34459. See [GHSA-r95h-9x8f-r3f7](https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-r95h-9x8f-r3f7) for more information.
> dep: update vendored libxml2 to v2.12.7

- CHANGELOG.md
- ext/java/nokogiri/Html4Document.java
- ext/java/nokogiri/XmlDocumentFragment.java
- ext/java/nokogiri/XmlDtd.java
- ext/java/nokogiri/internals/NokogiriHelpers.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- ext/java/nokogiri/internals/c14n/Canonicalizer20010315Excl.java
- ext/java/nokogiri/internals/c14n/CanonicalizerBase.java
- ext/java/nokogiri/internals/c14n/NameSpaceSymbTable.java
- ext/java/nokogiri/internals/c14n/UtfHelper.java
- ext/java/nokogiri/internals/dom2dtm/DOM2DTM.java
- gumbo-parser/src/tokenizer.c
- lib/nokogiri/xml/document.rb
- nokogiri.gemspec
- test/html5/test_encoding.rb
- test/test_xslt_transforms.rb
Fix various typos - some found via `codespell` and `typos` CLI (h/t @kianmeng with PR #3166)
This PR does not change test coverage - existing tests should suffice.
This PR does not introduce any changes in behavior.
> Typo fixes

- gumbo-parser/test/tokenizer.cc
Testing gumbo prints error messages even when they are expected (at least in
some cases). This stops that from happening.
No functional changes outside of tests.
N/A. This is a change to the testing infrastructure.
No.
> libgumbo test: Don't print expected errors

- ext/nokogiri/gumbo.c
- lib/nokogiri/html5/document.rb
- lib/nokogiri/html5/document_fragment.rb
- test/html5/test_encoding.rb
- test/html5/test_nokogumbo.rb
Refactor `Gumbo.parse` and `Gumbo.fragment` to use keyword arguments for parse options (instead of positional arguments).
These methods are internal and not part of the public API, so this isn't considered a breaking change. We're changing them to be more extensible going forward.
See comments at #3178 for context
This PR also
- introduces checking for the Gumbo options passed in
- takes care to delete deprecated kwarg `max_parse_errors`
- cleans up options passed around in tests
It's a refactor, existing test coverage should be sufficient.
No behavior changes, but the HTML5 parser is only available in CRuby.
> refactor: `Gumbo.parse` and `.fragment` now use keyword arguments

- ext/nokogiri/extconf.rb
- ext/nokogiri/gumbo.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_node.c
While working with @stevecheckoway on #3205, we caught an edge case in how the `max_depth` parameter was converted from signed to unsigned int. It turned out that it would have been caught much earlier with the `-Wconversion` flag, but that flag is useless in Ruby C extensions because of the issue described at https://bugs.ruby-lang.org/issues/20507
That issue was fixed in Ruby 3.4-dev by https://github.com/ruby/ruby/pull/10843 and so I'm using it here and fixing the compilation warnings it flags.
N/A
N/A
> Compile with type/sign conversion warnings

- CONTRIBUTING.md
- ext/nokogiri/extconf.rb
Enable a faster development feedback loop when working on libgumbo. See notes in CONTRIBUTING.md for how to use it.
Closes #2718
> dev: extconf supports --gumbo-dev

- CHANGELOG.md
- lib/nokogiri/css.rb
The undocumented and unused method `Nokogiri::CSS.parse` is now deprecated and will generate a warning. This method will be removed in a future version of Nokogiri.
The AST returned by this method is private and subject to change and removal in future versions of Nokogiri.
There is no test coverage for this method because Nokogiri doesn't use it.
This method is unused.
> deprecate: Nokogiri::CSS.parse

- lib/nokogiri/css.rb
- lib/nokogiri/css/parser_extras.rb
- lib/nokogiri/css/selector_cache.rb
- lib/nokogiri/decorators/slop.rb
- nokogiri.gemspec
- test/css/test_css.rb
- test/css/test_parser_cache.rb
This is part of a continuing track of work to separate out the concerns of CSS parser, CSS selector cache, and XPath expression translation into distinct components.
In this PR, I've extracted a CSS::SelectorCache class providing functionality that was previously built directly into CSS::Parser (with an awkward API that I'm responsible for writing in 2008).
- The methods `Parser.set_cache`, `Parser.cache_on?`, and `Parser.without_cache(&blk)` have been removed.
- The cache is now injected by `CSS.xpath_for` (optionally, via a `cache:` keyword argument) instead of being built into the parser.
- Documentation for `CSS.xpath_for` has also been updated and improved.
Mostly an internal refactor, …
> extract CSS selector cache into CSS::SelectorCache

- CHANGELOG.md
- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.8
backport to v1.16.x
> dep: update libxml2 to 2.12.8 (backport to v1.16.x)

- ext/nokogiri/extconf.rb
- gumbo-parser/src/error.c
- gumbo-parser/src/error.h
- gumbo-parser/src/parser.c
- test/html5/test_errors.rb
Error messages do not currently show nonstandard element names.  This remedies this situation.
Yes.
It changes the behavior of the gumbo parser.
> Show nonstandard element tags in error messages

- Gemfile
`mutex_m` is one of the gems that was dropped from the default gems in Ruby 3.4. I think we originally added it to the Gemfile in #3092 because minitest was using it, and that changed in minitest/minitest@5f5c2111
> dep(dev): drop mutex_m from the Gemfile

- test/xml/test_entity_reference.rb
- test/xml/test_schema.rb
Update tests to accept new libxml2 error messages (from `master` branch, pre-2.14).
Failing tests: https://github.com/sparklemotion/nokogiri/actions/runs/9544039534/job/26301851765
```
1) Failure:
Nokogiri::XML::TestDOMEntityReference#test_document_dtd_loading_with_nonet [test/xml/test_entity_reference.rb:203]:
--- expected
+++ actual
@@ -1 +1 @@
-["2:49: WARNING: failed to load \"http://foo.bar.com/\": Attempt to load network entity", "ERROR: Attempt to load network entity: http://foo.bar.com/", "4:14: ERROR: Entity 'bar' not defined"]
+["2:49: WARNING: failed to load \"http://foo.bar.com/\": Attempt to load network entity", "4:14: ERROR: Entity 'bar' not defined"]
2) Failure:
Nokogiri::XML::TestDOMEntityReference#test_document_dtd_loading_wi …
```
> upstream: update tests for upstream libxml2 changes

- CHANGELOG.md
- dependencies.yml
update libxml to 2.13.1 and libxslt to 1.1.41
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.1
- https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.41
> dep: update libxml to 2.13.1 and libxslt to 1.1.41

- .github/workflows/downstream.yml
- .github/workflows/upstream.yml
- use ruby 3.3 for some downstream projects
- use ruby 3.3 for upstream xmlsoft-head-valgrind job
Note: an early version of this PR updated ubuntu 24.04 for upstream ruby-head-valgrind job, and that failed because some of the stack frames had no information.
> ci: update some containers and versions of ruby

- CHANGELOG.md
- ext/nokogiri/gumbo.c
- gumbo-parser/src/nokogiri_gumbo.h
- gumbo-parser/src/parser.c
- lib/nokogiri/html5.rb
- test/html5/test_api.rb
- test/html5/test_tree_construction.rb
This change adds support for parsing noscript content with the scripting flag enabled. In this case, Gumbo will treat the content of the noscript element as raw text, exactly as the browser would.
Closes #3178 
Yes.
It adds support for this parsing option to libgumbo only.
> Support parsing noscript content in script-enabled mode

- ext/nokogiri/extconf.rb
- ext/nokogiri/html4_sax_parser.c
- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/html4_sax_push_parser.c
- ext/nokogiri/libxml2_polyfill.c
- ext/nokogiri/nokogiri.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_sax_parser.c
- ext/nokogiri/xml_sax_parser_context.c
- ext/nokogiri/xml_sax_push_parser.c
- lib/nokogiri/xml/sax/parser.rb
- nokogiri.gemspec
- test/xml/sax/test_parser.rb
Upstream has started to deprecate some struct members that we're accessing directly. Let's start addressing some of those issues.
I'm also introducing some polyfills for libxml2 so we can always use the latest and greatest API functions.
Refactoring. Existing coverage is adequate.
Refactoring. No behavior changes.
**Related upstream PRs**
- [parser: implement xmlCtxtGetOptions (!262) · Merge requests · GNOME / libxml2 · GitLab](https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/262)
> libxml 2.14-dev deprecations

- .github/workflows/upstream.yml
The runners are now using libxml 2.9.14 which leaks memory in schema parsing edge cases (and is fixed in modern versions of libxml2).
Testing against old system libraries is not really useful since we can't do anything about it. So I'm removing it.
> ci: stop upstream valgrind testing against system libraries

- CHANGELOG.md
- ext/nokogiri/gumbo.c
- lib/nokogiri/css.rb
- lib/nokogiri/html5.rb
- lib/nokogiri/html5/document_fragment.rb
- test/html5/test_api.rb
- test/html5/test_quirks_mode.rb
Coming from the discussion at #3203, I wanted to improve the fragment parsing API
- as discussed in #2646, parse in no-quirks mode if a context element name is provided (not a context `Node`, just the name)
- allow passing `:context` kwarg to `DocumentFragment.new` and `.parse`
- deprecate the positional options hash to `.parse` per notes at #3200
Included additional coverage for the API changes
HTML5 is only in CRuby.
> Fix fragment quirks mode, and make it easier to specify fragment context

- ext/nokogiri/extconf.rb
`DLLIB` seems to be broken on Android.
Closes #3244
We don't have test coverage for Android builds, so they remain officially unsupported, but this reportedly helps.
N/A
> fix: use TARGET_SO instead of DLLIB to clean installation

- test/helper.rb
- test/html4/sax/test_parser.rb
- test/html4/sax/test_parser_context.rb
- test/html4/test_document.rb
- test/html4/test_document_fragment.rb
- test/html4/test_element_description.rb
- test/html4/test_node.rb
- test/test_compaction.rb
- test/test_memory_usage.rb
- test/xml/sax/test_parser.rb
- test/xml/test_builder.rb
- test/xml/test_comment.rb
- test/xml/test_document.rb
- test/xml/test_document_fragment.rb
- test/xml/test_entity_reference.rb
- test/xml/test_namespace.rb
- test/xml/test_node.rb
- test/xml/test_node_attributes.rb
- test/xml/test_node_reparenting.rb
- test/xml/test_processing_instruction.rb
- test/xml/test_reader.rb
- test/xml/test_schema.rb
Raise exception if a test makes no assertions.
See https://railsatscale.com/2024-01-25-catching-assertionless-tests/
And this PR cleans up all of the assertionless tests that were found.
- some were not useful (doing a thing in a loop might have been useful
early in nokogiri development, but not anymore) and were deleted
- some needed explicit `refute_raises`
- some needed explicit `refute_valgrind_errors`
- some just needed rewriting with assertions
> test: raise exception on assertionless tests

- CHANGELOG.md
- lib/nokogiri/xml/node.rb
- test/xml/test_document_fragment.rb
This hack is not necessary with libxml 2.13 which improves fragment recovery behavior.
- add a TODO to remind me to remove the hack once we no longer support libxml 2.13 (system libs)
- add a test that asserts the correct behavior when using libxml >= 2.13
Closes #2092
Yes. 
Sadly, the Java implementation still does not handle in-context fragment parsing correctly, but that's out of scope for this improvement.
> tidy: prepare to remove in-context recovery hack needed for libxml < 2.13

- CHANGELOG.md
- ext/java/nokogiri/XmlNode.java
- test/xml/test_node_attributes.rb
#2677 pointed out inconsistent behavior in the JRuby implementation with respect to namespaced attributes.
This may be an incomplete fix, but it's good enough to ship.
Closes #2677 
Yes
This PR fixes the JRuby behavior to match the CRuby behavior.
> (jruby) namespaced attributes

- CHANGELOG.md
- ext/nokogiri/html4_document.c
- ext/nokogiri/html4_sax_push_parser.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_dtd.c
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_reader.c
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_sax_push_parser.c
- ext/nokogiri/xml_schema.c
- ext/nokogiri/xml_syntax_error.c
- ext/nokogiri/xml_xpath_context.c
- lib/nokogiri/xml/syntax_error.rb
- suppressions/ruby.supp
- test/xml/test_syntax_error.rb
In places (like document parsing) where it's possible for libxml2 to emit multiple warnings and errors, aggregate these libxml2 errors into a single exception so users can see all the problems.
Previously, we were grabbing the most recent "error" which might just be a warning and not the fatal error preventing parsing from completing. This was misleading and hid the source of the real problem.
Now, if there are multiple errors, they're aggregated into a single Nokogiri::XML::SyntaxError with a message like:
Multiple errors encountered:
WARNING: text of warning message
ERROR: text of error message
WARNING: text of second warning message
Note that I've also renamed some internal C functions to try to incrementally get consistent with naming. …
> feat: aggregate libxml2 errors into a single exception

- CHANGELOG.md
- ext/java/nokogiri/XmlSchema.java
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_schema.c
- test/xml/test_schema.rb
Fixes #1282
Yes.
Brings the JRuby impl in line with the CRuby impl.
> fix(jruby): Schema#validate should not accumulate errors in @errors

- CHANGELOG.md
- ext/java/nokogiri/XmlSchema.java
- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_schema.c
- lib/nokogiri/xml/relax_ng.rb
- lib/nokogiri/xml/schema.rb
- test/xml/test_relax_ng.rb
On both JRuby and CRuby impls, replace the native `read_memory` method
from XML::Schema and XML::RelaxNG with a ruby method that uses
`from_document`. `read_memory` was buggy on both platforms, but
especially on the JRuby impl.
This is comparable in performance on CRuby. From a benchmark taken
before this change:
Warming up --------------------------------------
Schema.new     1.219k i/100ms
Schema.from_document     1.258k i/100ms
Schema.read_memory     1.118k i/100ms
Calculating -------------------------------------
Schema.new     12.160k (± 8.3%) i/s -    121.900k in  10.093638s
Schema.from_document     12.216k (± 8.6%) i/s -    122.026k in  10.059696s
Schema.read_memory     12.790k (±10.7%) i/s -    127.452k in  10.105931s
Comparison: …
> fix: RelaxNG.read_memory is now reliable

- CHANGELOG.md
- ext/java/nokogiri/XmlSchema.java
- ext/nokogiri/xml_schema.c
- test/xml/test_schema.rb
`Schema#validate` now returns errors on empty and malformed files. Previously, it would return errors on empty/malformed Documents, but not when reading from files.
Closes #642
Yes!
This fixes different bugs on CRuby and JRuby, but both impls agree with each other now.
> fix: Schema#validate returns errors on empty and malformed files

- .github/workflows/upstream.yml
Upstream workflow started failing on xmlsoft windows build because it no longer can find liblzma. (I'm not sure why this is, the runner image manifests don't seem to have a relevant change in the last week ...)
> ci: windows upstream needs liblzma

- CHANGELOG.md
- lib/nokogiri/xml/builder.rb
- test/xml/test_builder.rb
Fixes #1041 
Previously, missing methods with blocks on dynamically-created nodes were always handled by invoking `instance_eval(&block)` on the Builder, even when the Builder was yielding self for all other missing methods with blocks.
Now the scope convention is consistent, meaning these two `doc.div` lines do the same thing:
Nokogiri::XML::Builder.new do |doc|
doc.root do
doc.div(class: "foo") { doc.text self.class }
doc.div.foo           { doc.text self.class }
end
end
Yes!
N/A
> fix: Builder is now consistent in how it handles method_missing

- CHANGELOG.md
- ext/java/nokogiri/internals/ReaderNode.java
- test/xml/test_reader.rb
Closes #1523
Yes.
This makes the Java impl behave like the C impl.
> fix(jruby): Reader#outer_xml and #inner_xml encode entities properly

- lib/nokogiri/xml/sax/push_parser.rb
- test/xml/sax/test_push_parser.rb
The behavior is different between Java and C impls in a way that I don't care enough to fix. Let's document the difference and move on with our lives.
Closes #1758
Yes.
N/A
> test: add test coverage describing how pushparser handles empty docs

- lib/nokogiri/encoding_handler.rb
- test/test_encoding_handler.rb
Example failure: https://github.com/sparklemotion/nokogiri/actions/runs/9774049613/job/26981486984
Let's just work around it in the tests. The behavior we're testing isn't specific to UTF-8, so let's just swap in ISO-2022-JP.
gnome/libxml2@6d8427dc
Tagging @nwellnhof just for awareness.
Yes
N/A
> tests: handle upstream libxml2 returning null for UTF-8 enc handler

- CHANGELOG.md
- ext/java/nokogiri/XmlEntityReference.java
- ext/java/nokogiri/internals/XmlDomParserContext.java
- test/xml/test_entity_reference.rb
Two things getting fixed here:
1. We were not calling `setFeature(FEATURE_NOT_EXPAND_ENTITY, ...)` correctly. It defaults to true, and we were conditionally setting it to true. Instead, let's just explicitly set this feature (and the other features we care about) to avoid mistaken assumptions about the default.
2. We were rendering the children of the EntityReference, which contains the replacement text, as well as the EntityReference itself. We should only ever render one or the other. If NOENT is false, though, there won't be any EntityReferences in the DOM. So: if we encounter an EntityReference, don't render its children.
See https://xerces.apache.org/xerces-j/features.html section on `create-entity-ref-nodes` for a deeper explanation of …
> fix(jruby): serialize entity refs or the replacement text, not both

- ext/nokogiri/extconf.rb
See https://github.com/ruby/ruby/pull/11085 for discussion
Existing test suite should be sufficient to tell us if this breaks things.
N/A
> ext: don't split the compiler flags when appending env vars

- dependencies.yml
Update vendored libxml2 and libxslt:
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.2
- https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.42
> dep: update vendored libxml2 → 2.13.2, libxslt → 1.1.42

- test/html4/sax/test_parser.rb
I'm about to do some work on the sax parser encoding functionality, so let's clean this file up.
> tidy: update html4/sax/test_parser.rb to use minitest::spec

- CHANGELOG.md
- ext/java/nokogiri/Html4SaxParserContext.java
- ext/java/nokogiri/XmlSaxParserContext.java
- ext/java/nokogiri/internals/ParserContext.java
- ext/nokogiri/extconf.rb
- ext/nokogiri/html4_sax_parser_context.c
- ext/nokogiri/libxml2_polyfill.c
- ext/nokogiri/nokogiri.h
- ext/nokogiri/xml_node.c
- ext/nokogiri/xml_sax_parser_context.c
- lib/nokogiri/class_resolver.rb
- lib/nokogiri/html4/sax/parser.rb
- lib/nokogiri/html4/sax/parser_context.rb
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/sax.rb
- lib/nokogiri/xml/sax/document.rb
- lib/nokogiri/xml/sax/parser.rb
- lib/nokogiri/xml/sax/parser_context.rb
- lib/xsd/xmlparser/nokogiri.rb
- test/html4/sax/test_parser.rb
- test/html4/sax/test_parser_context.rb
- test/test_class_resolver.rb
- test/xml/sax/test_parser.rb
- test/xml/sax/test_parser_context.rb
Previously, encoding overrides were not implemented for XML::SAX::Parser#parse_memory (as reported in #918) and XML::SAX::Parser#parse_file.
However, this commit goes further and significantly simplifies and unifies the two SAX::ParserContext implementations and the two SAX::Parser implementations.
This commit also allows Encoding objects and encoding names to be passed into the SAX::ParserContext methods, and the XML memory and file methods now accept and properly use passed encodings.
Finally, this commit also backfills a lot of test coverage for the XML and the HTML4 sax parser encoding.
Closes #918
Yes.
Yes, …
> fix: overhaul SAX::Parser encoding handling

- gumbo-parser/fuzzer/parse_fuzzer.cc
Place an upper limit on the input size to the fuzzer, to avoid naive out-of-memory failure reports, which we've been getting regularly.
See:
- [63481 - nokogiri:parse_fuzzer: Out-of-memory in parse_fuzzer - oss-fuzz](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63481)
Earlier I had given up on fixing this because I was trying to configure higher memory limits; this is a more straightforward solution (and one suggested by https://google.github.io/oss-fuzz/getting-started/new-project-guide/#input-size).
> fuzz: limit input size

- CHANGELOG.md
- dependencies.yml
Update packaged libxml2, see https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.3
> dep: update libxml2 to v2.13.3

- CHANGELOG.md
- dependencies.yml
See https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.9
Addresses CVE-2024-40896 which Nokogiri maintainers believe does not affect Nokogiri users.
> dep: update libxml2 to v2.12.9 (branch v1.16.x)

- CHANGELOG.md
- lib/nokogiri/html4/document_fragment.rb
- test/html4/test_document_fragment.rb
Previously an exception (TypeError: no implicit conversion of File into String) would be raised.
Fixes: #2069 
Yes.
No.
> fix: IO handling in HTML4::DocumentFragment.parse

- CHANGELOG.md
- ext/nokogiri/extconf.rb
I'm deciding to drop support for earlier versions because:
- 2.7.7 nanohttp.c doesn't compile on modern systems
- 2.8.0 doesn't have PARSE_BIG_LINES, GNOME/libxml2@968a03a2 introduced it in 2.9.0
- 2.9.0 and 2.9.1 have the xpath optimization bug that ruined our CSS queries in :first-child broken with libxml 2.9.0 #829, GNOME/libxml2@b4bcba23 fixed it in 2.9.2
Also, bump the min recommended version to v2.12.0 because Nick has fixed a lot of long-standing issues upstream. ♥ ♥ ♥
Followup to #3232
Closes #3287
Existing coverage is sufficient.
No.
> dep: bump libxml2 min required version to v2.9.2

- README.md
- test/html4/test_document_fragment.rb
- test/xml/test_entity_reference.rb
This should have been in 3bd62021
> doc: update tests and README to reflect libxml2 min req

- ext/nokogiri/xml_syntax_error.c
- lib/nokogiri/xml/syntax_error.rb
- test/html4/test_document.rb
- test/xml/test_document.rb
- test/xml/test_schema.rb
- test/xml/test_syntax_error.rb
When validating an XML document with a schema it is difficult to impossible to know where the error happened in the document. With the path on the error, we can identify where in the document the error occurred.
I believe so. I updated the test in the schema to check to see if path errors were being returned correctly.
This change the C implementation gently. Setting the path during error creation.
I looked if xerces-j could do it, but I couldn't find anything on the SAXException that would help.
> Make available the XPath path of the node where a SyntaxError occurred during Schema validation

- .gitignore
Local work using `rbenv` populates the `.ruby-version` file, which we don't want included in source control.
n/a
No
> Add rbenv version file to .gitignore

- lib/nokogiri/html4.rb
https://github.com/sparklemotion/nokogiri/issues/3323
No new behavior has been added, so existing tests are sufficient.
No.
> Use argument forwarding in HTML4 module

- .github/workflows/ci.yml
- ext/nokogiri/extconf.rb
When using Nix on Darwin, we ideally should be latching onto the Nix-provided AR and RANLIB. Without this, when blocking Xcode via `sandbox-exec`, I see errors like this while attempting to install the gem, since we end up using the default `ar` and `runlib`
```
xcode-select: note: No developer tools were found, requesting install.
If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
See `man xcode-select` for more details.
```
No but this seems relatively harmless?
**Does this change affect the behavior of either the C or …
> extconf: respect AR and RANLIB in recipes on darwin

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/html5/test_serialize.rb
> fix: escape foreign style tag content when serializing HTML5 (v1.15.x)

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/html5/test_serialize.rb
> fix: escape foreign style tag content when serializing HTML5 (v1.16.x)

- CHANGELOG.md
- ext/nokogiri/xml_node.c
- test/html5/test_serialize.rb
Normally, a `style` tag is considered to be a raw text element, meaning `<` is parsed as part of a possible "tag start" token, and is serialized literally (and not rendered as an escaped character reference `&lt;`).
However, when appearing in either SVG or MathML foreign content, a `style` tag should *not* be considered a raw text element, and should be escaped when serialized. libgumbo is parsing this case correctly, but our HTML5 serialization code does not escape the content.
This commit updates the static `is_one_of()` C function to consider the namespace of the parent node as well as the tag's local name when deciding whether the tag matches the list of HTML elements, so that a `style` tag in foreign content will *not* match, but a …
> fix: escape foreign style tag content when serializing HTML5

- CONTRIBUTING.md
- ext/nokogiri/xml_relax_ng.c
- lib/nokogiri/xml/relax_ng.rb
> XML::RelaxNG argument forwarding

- lib/nokogiri/html5.rb
hackday 🙂
#3323 
No test changes
No
> Update html5.rb forwarding params syntax

- ext/nokogiri/xml_relax_ng.c
- ext/nokogiri/xml_schema.c
- lib/nokogiri/xml/relax_ng.rb
- lib/nokogiri/xml/schema.rb
- test/xml/test_relax_ng.rb
- test/xml/test_schema.rb
Related to https://github.com/sparklemotion/nokogiri/issues/3323, introducing keyword argument support in Nokogiri::XML::Schema.read_memory() and argument forwarding in Nokogiri::XML::Schema{,.new}().
Some minor test coverage mimicking the existing permutations of options.
No
> Nokogiri::XML::Schema.read_memory() support keyword arguments

- Gemfile
Dependabot has been unable to bump standard or the rubocop gems because I had over-specified dependencies.
> dep: let standardrb set its dependency versions

- ext/nokogiri/xml_reader.c
- lib/nokogiri/xml.rb
- lib/nokogiri/xml/reader.rb
- test/xml/test_reader_encoding.rb
Adds support for keyword args for optional args for Nokogiri::XML::Reader#initialize
Yas, says @flavorjones 
> Implement XML::Reader.new with keyword args and forward Reader() to it

- lib/nokogiri/html5.rb
- lib/nokogiri/html5/document.rb
- test/html5/test_api.rb
- test/html5/test_nokogumbo.rb
Keyword arguments for HTML5::Document.parse, etc.
YAS.
> Updates HTML5::Document.parse with keyword arguments;

- CHANGELOG.md
- ext/java/nokogiri/XmlDocumentFragment.java
- ext/nokogiri/html4_document.c
- ext/nokogiri/nokogiri.c
- ext/nokogiri/xml_document.c
- ext/nokogiri/xml_document_fragment.c
- lib/nokogiri/html4/document.rb
- lib/nokogiri/html4/document_fragment.rb
- lib/nokogiri/html5.rb
- lib/nokogiri/html5/document.rb
- lib/nokogiri/html5/document_fragment.rb
- lib/nokogiri/xml.rb
- lib/nokogiri/xml/document.rb
- lib/nokogiri/xml/document_fragment.rb
- test/html4/test_document.rb
- test/html4/test_document_fragment.rb
- test/html5/test_api.rb
- test/xml/test_document_fragment.rb
As part of #3323 there were a few RubyConf 2024 Hack Day pull requests addressing Document and DocumentFragment constructors which were related to, or blocked on, some changes to the C code.
So this PR is a mega-PR that merges all those PRs and unifies the code and doc style:
- #3327 
- #3336 
- #3334 
- #3335 
But in addition to those PRs also updates:
- the `XML::DocumentFragment` new/initialize argument handling for CRuby and JRuby
- `XML::DocumentFragment#initialize` kwargs
- `HTML4::Document.parse` kwargs
- general improvement of documentation
I think so!
The XML::DocumentFragment allocator has changed, but …
> {XML,HTML4,HTML5}::{Document,DocumentFragment}{.parse,#initialize} take keyword arguments

- lib/nokogiri/xml.rb
- test/xml/test_document.rb
- test/xml/test_document_encoding.rb
- test/xml/test_node_encoding.rb
Related to https://github.com/sparklemotion/nokogiri/issues/3323, introducing keyword argument support in Nokogiri::XML::Document.parse.
Some minor test coverage mimicking the existing permutations of options.
No
> Nokogiri::XML() and Nokogiri::XML.parse() support argument forwarding

- lib/nokogiri/xslt.rb
part of #3323
Existing coverage should be fine.
No.
> Nokogiri::XSLT() uses parameter forwarding

- ext/nokogiri/xml_node.c
- test/xml/test_document_fragment.rb
- test/xml/test_node.rb
`Node#dup` adds the new node to the document's node cache to make sure it's marked properly. Fixes #3359.
Also, we make sure the new node is decorated if necessary with its document's decorators.
Yes! HUGE thanks to @byroot for doing the work to create a tight reproduction. 🙇
Both bugfixes affect the C implementation only.
> fix: `Node#dup` adds the new node to the document's node cache

- ext/nokogiri/xml_node.c
- test/xml/test_document_fragment.rb
- test/xml/test_node.rb
Backport of #3363 addressing #3359.
> fix: Node#dup adds the new node to the document's node cache (backport to v1.17.x)

- ext/java/nokogiri/XmlNode.java
- test/xml/test_node.rb
Back in b92660e6 (#1834 fixing #1063) I omitted support in JRuby for the "new_parent_document" argument to `Node#dup` because there was no performance reason to implement it. So the test was skipped.
However, in 1e7d38af and other commits in #3117 (fixing #316), I introduced a call to `initialize_copy_with_args` that passes the new parent document as an argument on both CRuby and JRuby implementations. Because the test was skipped, I didn't catch that this broke on JRuby.
In particular this was a problem for Loofah which relies on decorators, and even more particularly this broke the `Loofah::TextBehavior` formatting concern for `Loofah::*::DocumentFragment` objects.
The skipped test is no longer …
> fix(jruby): XML::DocumentFragment.dup to another document

- ext/java/nokogiri/XmlNode.java
- test/xml/test_node.rb
Backport of https://github.com/sparklemotion/nokogiri/pull/3372
> fix(jruby): XML::DocumentFragment.dup to another document (v1.17.x)

- .cross_rubies
- .github/workflows/ci.yml
- .github/workflows/generate-ci-images.yml
- CHANGELOG.md
- Gemfile
- oci-images/nokogiri-test/mri-3.4-rc.dockerfile
- rakelib/docker.rake
ext: add Ruby 3.4 to the precompiled native gems
Closes #3273.
Yes.
CRuby only, obvs.
> ext: add Ruby 3.4 to the precompiled native gems

- ext/nokogiri/extconf.rb
Over time, we've accumulated a couple of hacks specifically aimed at improving the compatibility of the `-linux` native gem on Musl systems.
With #3375 we're building separate `-linux-gnu` and `-linux-musl` gems, so these hacks should no longer be needed. Let's remove them.
We're testing on a matrix that includes Musl systems, so existing coverage should be adequate.
N/A
> ext: revert hacks for GNU/Musl compatibility

- CHANGELOG.md
- gumbo-parser/src/ascii.c
- gumbo-parser/src/parser.c
I'm seeing some compiler warnings, so just doing some cleanup.
cc @stevecheckoway
> dev: quash gumbo compiler warnings 202412

- Gemfile
- ext/java/nokogiri/XmlXpathContext.java
- ext/java/nokogiri/internals/NokogiriNamespaceContext.java
- ext/java/nokogiri/internals/NokogiriXPathVariableResolver.java
- test/xml/test_xpath_context.rb
Workaround recommended in https://github.com/jruby/jruby/issues/7262
> ci: try to get jruby green by pinning jar-dependencies

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- .github/workflows/generate-ci-images.yml
- .github/workflows/upstream.yml
- Gemfile
- oci-images/nokogiri-test/mri-3.4.dockerfile
- oci-images/nokogiri-test/mri.erb
- rakelib/docker.rake
Now that both docker/ruby and setup-ruby have 3.4 releases, let's update CI.
> ci: bump everything to use 3.4 final

- ext/nokogiri/xml_sax_parser_context.c
- test/test_memory_usage.rb
I saw a failure in CI at https://github.com/sparklemotion/nokogiri/actions/runs/12529532790/job/34945362057?pr=3393
```
1) Error:
Nokogiri::HTML4::SAX::ParserContext::constructor::encoding::.io#test_0001_supports passing encoding name:
NotImplementedError: method `read' called on terminated object (0x0000005520809790)
test/html4/sax/test_parser_context.rb:60:in `parse_with'
test/html4/sax/test_parser_context.rb:60:in `block (5 levels) in <module:SAX>'
```
So now the class keeps a reference to the input object to prevent it from being GCed before we parse it.
Yes.
N/A
> fix: SAX::ParserContext keeps a reference to the input

- CHANGELOG.md
- ext/nokogiri/xml_sax_parser_context.c
- test/test_memory_usage.rb
> fix: SAX::ParserContext keeps a reference to the input (backport of #3395 to v1.18.x)

- .github/workflows/ci.yml
bump windows test images from "head" to "3.4" now that rubyinstaller has been released
> ci: bump windows test images from "head" to "3.4"

- .github/workflows/downstream.yml
In #3348, downstream CI tests for Sanitize were temporarily disabled because the changes in that PR (intentionally) caused some of Sanitize's tests to fail.
As of Sanitize 7.0.0, tests are passing again with the latest Nokogiri and it's safe to re-enable the downstream tests. 🎉
> ci: re-enable downstream sanitize test

- gumbo-parser/src/nokogiri_gumbo.h
- gumbo-parser/src/parser.c
It's unused. See discussion at #2950
> dev: delete gumbo_normalize_svg_tagname

- Gemfile
- lib/nokogiri/css/xpath_visitor.rb
- scripts/test-gem-install
- test/css/test_xpath_visitor.rb
- test/xml/test_xpath.rb
When performing a CSS selector query, an XML document's root namespace declarations are injected into the XPathVisitor, and the default namespace is applied to any non-namespaced element in the resulting xpath query.
However, the wildcard selector "*" should not have this namespace applied. This regressed in v1.17.0 with 179d74d5.
Fixes #3411
Yes.
N/A
> fix(css-selector): default XML namespace is not applied to wildcard

- doc/keyword_arguments.md
Adds a doc about "modernized" call-seqs.
A modernized method's doc can link to this doc.  This should allow a simpler discussion in the method's doc.
Doc only.
No.
> New doc for modernized call-seqs (kwargs)

- .github/workflows/ci.yml
- Gemfile
- lib/nokogiri/css/xpath_visitor.rb
- scripts/test-gem-install
- test/css/test_xpath_visitor.rb
Backport of https://github.com/sparklemotion/nokogiri/pull/3413 to v1.18.x
> backport: fix(css-selector): default XML namespace should not be applied to wildcard

- lib/nokogiri/xml/node.rb
Clarifies the far-reaching importance of XML::Node.
Doc only.
Doc only.
> [DOC] Adds to introduction of XML::Node

- .github/workflows/ci.yml
- .github/workflows/downstream.yml
- dependencies.yml
Update vendored libxml2 to v2.13.6
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.6
Security note: the changelog mentions CVE-2025-24928 and CVE-2024-56171, but it's not obvious that those vulnerabilities affect Nokogiri users.
> dep: update libxml2 to v2.13.6

- lib/nokogiri/xml/node.rb
I had thought to put in an Issue for this, but instead will make bold and propose to `:nodoc:` `Node#accept`.
Reason:  I was unable to find out how I would use this (so maybe it should be internal?).  I found nothing in `test`, and on the wide web, saw only that accept/visit often have to do with data locking.
If this is to be retained as user documentation, I'd like to be able to document it properly, but would need help (pointers to relevant docs both within `nokogiri` and elsewhere).
> [DOC] :nodoc: for Node#accept

- .github/workflows/downstream.yml
- dependencies.yml
- ext/nokogiri/extconf.rb
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.6
See related #3437 and #3438
I'm not making any kind of statement or promises about whether I'll cut security releases for v1.17.x in the future. I'm doing this because Mastodon 4.2 still supports Ruby 3.0 and its dependency on ruby-saml makes it potentially impacted by the underlying libxml2 fixes.
I know somebody out there, somewhere, is going to say "I'll stay on Ruby 3.0 if Mike is going to keep cutting security updates", and hoo boy that is NOT a bet you should be making. I am the most enthusiastic supporter of "dropping support for EOL versions of Ruby" that you will ever meet, and this is NOT going to continue.
I know somebody out there, somewhere, is going to try to convince me that because I made this one security update, …
> dep: update libxml2 to v2.13.6 (v1.17.x branch)

- README.md
- rakelib/rdoc.rake
README.md urges the reader to "See CONTRIBUTING.md."  But the reader cannot do so because the page is not included in the Nokogiri documentation
So:
- First, I've modified `rake.rdoc` to generate the page.
- Second, I've changed the reference into a link to the page.
- Third, I've given the the link's text as the page title, "Contributing to Nokogiri" (not the page path `CONTRIBUTING.md).
- Finally, I've given the url as an `rdoc-ref:`, which will give a warning if the page is not found.
Besides `README.md`, there are several other cited-but-missing pages, which I've treated similarly.
> [skip ci] Add links to local pages in README.md

- ext/java/nokogiri/XmlNode.java
- test/namespaces/test_namespace_definitions.rb
In this PR, I've updated `Node#namespace_definitions` to no longer uses the namespace cache, meaning it uses the attributes defined on the node to determine the return value(s).
Removing this use of the cache revealed a separate bug in the `relink_namespace` java function, which suddenly became better tested on JRuby as a result of removing the cache usage (which was hiding the bug).
Finally, removing the cache also means that `relink_namespace` now needs to remove namespace definitions that are redundant (that is, the exact prefix and URI resolve in the parent) in order to match the CRuby implementation, so I've done that, too.
Closes #2543 
Yes.
**Does this change affect the behavior of either …
> fix(java): stop using the cache for Node#namespace_definitions

- lib/nokogiri/xml/builder.rb
- test/helper.rb
- test/namespaces/test_serializing_namespaces.rb
- test/xml/test_builder.rb
Simplify Builder to do late binding on namespaces, so that nodes can be built that rely on namespaces they define.
Fixes #3458
Existing pending coverage (now resolved) is sufficient.
This really only affects the CRuby implementation, which now behaves like the JRuby impl does.
> fix: XML::Builder namespace stitching

- .github/workflows/downstream.yml
- dependencies.yml
- ext/nokogiri/extconf.rb
https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.43
Note that this release is documented as fixing:
* CVE-2025-24855: Fix use-after-free of XPath context node
* CVE-2024-55549: Fix UAF related to excluded namespaces
so this will be a security release.
> dep: update libxslt to 1.1.43 (v1.18.x branch)

- CHANGELOG.md
- ext/java/nokogiri/internals/SaveContextVisitor.java
- test/namespaces/test_serializing_namespaces.rb
Fix MRI Ruby vs. JRuby XML child namespace output differences
Fixes https://github.com/sparklemotion/nokogiri/issues/3455
Backport of #3456
cc @johnnyshields
> Fix MRI Ruby vs. JRuby XML child namespace output differences (backport v1.18x)

- dependencies.yml
Forward-port #3467 to the `main` branch.
https://gitlab.gnome.org/GNOME/libxslt/-/releases/v1.1.43
> dep: update libxslt to 1.1.43 (main branch)

- .github/workflows/upstream.yml
- nokogiri.gemspec
This PR will contain fixes for recent JRuby updates, including:
* jar-dependencies unpinning
* running jruby-head builds on appropriate Java setup
* anything else I find that needs updating
> Fixes for recent JRuby updates

- lib/nokogiri/xml/node.rb
The documentation of [traverse](https://nokogiri.org/rdoc/Nokogiri/XML/Node.html#method-i-traverse) says "Yields self and all children to block recursively". I thought that means *first yield self, then recurse on children*. But actually it's the other way around: *first recurse on children, then yield self*. This PR changes the RDoc comment to clarify that.
not necessary for this PR
no
> doc: Nokogiri::XML::Node.traverse is recursively called on children first

- lib/nokogiri/xml/searchable.rb
Related to https://github.com/sparklemotion/nokogiri/issues/1534
Search function provides no indicator that it shouldn't be used for xpath selectors.
No, because it's a docs change
No
> Note that `Searchable#search` is not ideal

- ext/java/nokogiri/XmlNode.java
- test/html4/test_node.rb
- test/xml/test_node_set.rb
Fix Node#attribute in HTML documents and anything that depends on that, like NodeSet#attr.
Fixes #3487
Yes
Fixes JRuby to behave like CRuby.
> fix(jruby): Node#attribute in HTML documents

- ext/java/nokogiri/XmlNode.java
- test/html4/test_node.rb
- test/xml/test_node_set.rb
> fix(jruby): Node#attribute in HTML documents (v1.18.x)

- Gemfile
Drop Rubocop from JRuby deps, because prism won't build on the installation VMs without installing more packages, which I don't want to to do.
e.g. https://github.com/sparklemotion/nokogiri/actions/runs/14078266200/job/39443801657#step:4:236
> dep(dev): drop Rubocop from JRuby deps

- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.7
This is a bugfix release
> dep: bump libxml2 to 2.13.7

- Gemfile
- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.7
This is a bugfix release
(cherry picked from commit f51011704f6ef3d55c7fc57ff271c47b96bb38a5)
Backport of #3494
> dep: bump libxml2 to 2.13.7 (v1.18.x backport)

- CHANGELOG.md
- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.8
(cherry picked from commit 6457fe639359edda9f8817994bc4935abae3e81e and 9187f4af)
Forward port of #3509 to `main`
> dep: libxml2 to v2.13.8 (branch `main`)

- doc/xml/parsing.md
- doc/xml/parsing/parsing_strings.md
- rakelib/rdoc.rake
This new doc file aims to show how various XML text and markup are parsed into specific Nokogiri::XML::* instances.
This can be linked from the parsing methods and the parsed classes.
> [skip ci] New doc about parsing XML

- lib/nokogiri/html4/encoding_reader.rb
- test/html4/sax/test_push_parser.rb
- test/html4/test_comments.rb
- test/html4/test_document_fragment.rb
- test/test_pattern_matching.rb
- test/xml/node/test_save_options.rb
- test/xml/sax/test_push_parser.rb
- test/xml/test_node.rb
The update to standard/rubocop requires some changes. Not sure why these weren't caught in the dependabot PR?
> style(rubocop): SpaceInsideHashLiteralBraces, RedundantParentheses

- dependencies.yml
https://savannah.gnu.org/news/?id=10703
I don't know that this will fix #3519, but it's worth a shot.
> dep: update vendored libiconv to 1.18

- gumbo-parser/src/string_set.c
- test/html5/test_attributes.rb
Previously we were passing a character string of variable length, but always copying 8 bytes into the item. It's not really a problem if the length of the string is less than 8, but it's more serious if the length is longer than 8.
Fixes https://github.com/sparklemotion/nokogiri/issues/3500
Fixes https://github.com/sparklemotion/nokogiri/issues/3508
I've added test coverage that will fail under valgrind.
The issue is only with the C (gumbo) implementation.
> gumbo: Make sure to use the char* pointer as the hashmap item

- CHANGELOG.md
- patches/libxml2/0020-CVE-2025-6021-tree-Fix-integer-overflow-in-xmlBuildQ.patch
- patches/libxml2/0021-CVE-2025-6170-Fix-potential-buffer-overflows-of-inte.patch
- patches/libxml2/0022-CVE-2025-49795-schematron-Fix-null-pointer-dereferen.patch
- patches/libxml2/0023-CVE-2025-49794-CVE-2025-49796-schematron-Fix-xmlSche.patch
Address multiple vulnerabilities that are patched in libxml 2.14.4 and 2.14.5 but do not appear in an official 2.13.x release.
- CVE-2025-6021 - 17d950ae "tree: Fix integer overflow in xmlBuildQName"
- CVE-2025-6170 - 5e9ec5c1 "Fix potential buffer overflows of interactive shell"
- CVE-2025-49794 - 81cef8c5 "schematron: Fix xmlSchematronReportOutput"
- CVE-2025-49795 - 62048278 "schematron: Fix null pointer dereference leading to DoS"
- CVE-2025-49796 - 81cef8c5 "schematron: Fix xmlSchematronReportOutput"
See related GHSA-353f-x4gh-cqq8 which will be published when these patches appear in a release.
> Apply upstream patches to address multiple vulnerabilities

- ext/nokogiri/extconf.rb
Looks like It causes timeout error frequently when we access to https://ftp.gnu.org/.
When we do not use fat gems in a Windows environment,
it require to download libiconv in order to compile nokogiri,
but installation is failed  with timeout error.
So, I think it would be better to use mirror site of ft.gnu.org to solve the timeout.
Ref. https://www.gnu.org/prep/ftp.html
Fix https://github.com/sparklemotion/nokogiri/issues/3521 
> Use mirror site to download libiconv

- CHANGELOG.md
- dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.14.6
> dep: update vendored libxml2 to v2.14.6

- .github/workflows/ci.yml
Related to (and partial reversion of) ae334cd2.
Modern msys has diverged too far from Ruby 3.1 DevKit to make it worth my time to continue to support source builds.
> ci: stop testing Ruby 3.1 windows source builds

- .github/workflows/ci.yml
- dependencies.yml
- ext/nokogiri/extconf.rb
https://savannah.gnu.org/news/?id=10703
Fix #3543 on the v1.18.x branch
Related to #3519
This is a backport of #3520
Also apply a few CI improvements to try to get green, generally.
> [v1.18.x] backport libiconv upgrade to v1.18
