bin/nokogiri
=> Introduce CLI configuration and make the consile engine switchable from IRB

ext/nokogiri/xml_sax_parser_context.c
The second "if" looks like a typo.
=> Remove duplicated "if"

lib/nokogiri/xml/dtd.rb
More info at https://github.com/JuanitoFatas/fast-ruby#proc--block
=> Implicit block call instead explicit block call. Faster code.

CHANGELOG.rdoc
"a small step for a man a giant leap for mankind" -- Yukihiro Matsumoto
=> Fix typo in CHANGELOG.rdoc

lib/nokogiri/xml/node.rb, lib/nokogiri/xml/node_set.rb, test/html/test_document.rb, test/html/test_document_encoding.rb, test/test_css_cache.rb, test/test_reader.rb, test/xml/sax/test_parser.rb, test/xml/test_namespace.rb, test/xml/test_node.rb, test/xml/test_node_set.rb, test/xml/test_unparented_node.rb
This pull request contains simple mechanic changes from using blocks to symbol
to proc.
=> Using symbol to proc

lib/nokogiri/xml/node.rb
While reading the source I stumbled upon this and figured it can't hurt to
optimize a bit.
=> XML::Node#ancestors optimization

.travis.yml
This PR changes the Travis test machine to one that can install Rubinius.
=> Travis: Try changing machine to get rbx-3

lib/nokogiri/xml/syntax_error.rb, test/xml/test_entity_reference.rb, test/xml/test_xpath.rb
=> In SyntaxError, not display line and column if are zero

ext/java/nokogiri/XmlNodeSet.java, ext/java/nokogiri/internals/NokogiriHelpers.java
=> get rid of JRuby --1.8 legacy code in ext

ext/nokogiri/xml_node.c
Background: Working around a puzzling segfault when using libc strdup on a C string from Ruby. Returns a pointer that's outside the program heap entirely.
Turns out libxml2 provides its own strdup/strchr equivalents that use the mem management functions we pass it (including ruby's malloc, ruby_strdup, etc), so may as well prefer these anyway.
=> Prefer libxml2's strdup and strchr equivalents

dependencies.yml
=> upgrade libxml to 2.9.7 and libxslt to 1.1.32

CHANGELOG.md, Manifest.txt, lib/nokogiri/xml.rb, lib/nokogiri/xml/entity_reference.rb, test/xml/test_entity_reference.rb
=> issue #1238 segfault on predefined entities

ext/java/nokogiri/XmlNode.java
=> remove unecessary calls to clearCachedNode

ext/java/nokogiri/HtmlSaxParserContext.java, ext/java/nokogiri/HtmlSaxPushParser.java, ext/java/nokogiri/XmlNode.java, ext/java/nokogiri/XmlSaxParserContext.java, ext/java/nokogiri/XmlSaxPushParser.java, ext/java/nokogiri/internals/NokogiriHandler.java, ext/java/nokogiri/internals/NokogiriHelpers.java, ext/java/nokogiri/internals/ParserContext.java, ext/java/nokogiri/internals/ReaderNode.java, ext/java/nokogiri/internals/SaveContextVisitor.java, ext/java/nokogiri/internals/XmlDomParserContext.java, ext/java/nokogiri/internals/c14n/InclusiveNamespaces.java
had these lying around for a year+ ... 
got distracted elsewhere -> recall that I was preparing for deeper refactorings
... some of the .java ext code-base gets less confusing to approach
all passing with JRuby 1.7 / 9.x ... changes are patch version compatible
=>  [jruby] review/cleanup extension code

ext/nokogiri/extconf.rb, ext/nokogiri/html_element_description.c, ext/nokogiri/xml_cdata.c, ext/nokogiri/xml_document.c, ext/nokogiri/xml_namespace.c, ext/nokogiri/xml_node.c
This is a proposal for leaving -Wconst-qual in place.
=> Flavorjones fix compilation warnings

README.md
=> Close unclosed tag

ext/java/nokogiri/internals/NokogiriHandler.java, test/xml/sax/test_push_parser.rb
=> push parser shouldn't throw a NPE when it receives no input

CHANGELOG.md, Manifest.txt, patches/libxml2/0002-Fix-nullptr-deref-with-XPath-logic-ops.patch, patches/libxml2/0003-Fix-infinite-loop-in-LZMA-decompression.patch
based on USN-3739-1 and -2.
see related #1785.
=> pull in upstream libxml2 patches

lib/nokogiri/xml/node_set.rb, test/xml/test_node_set.rb
PR for https://github.com/sparklemotion/nokogiri/issues/1822
=> NodeSet#each to return self instead of zero

Manifest.txt, ext/java/nokogiri/internals/XalanDTMManagerPatch.java, ext/java/nokogiri/internals/dom2dtm/DOM2DTM.java, ext/java/nokogiri/internals/dom2dtm/DOM2DTMdefaultNamespaceDeclarationNode.java
This is a rebase of PR #1760 along with an additional commit to resolve a logical merge conflict.
@jvshahid would love your approval that my additional commit looks OK.
=> fix dom2dtm to work in j9

ext/java/nokogiri/HtmlDocument.java, ext/java/nokogiri/HtmlEntityLookup.java, ext/java/nokogiri/HtmlSaxPushParser.java, ext/java/nokogiri/XmlDocument.java, ext/java/nokogiri/XmlDocumentFragment.java, ext/java/nokogiri/XmlNode.java, ext/java/nokogiri/XmlProcessingInstruction.java, ext/java/nokogiri/XmlSaxParserContext.java, ext/java/nokogiri/XmlSaxPushParser.java, ext/java/nokogiri/XsltStylesheet.java, ext/java/nokogiri/internals/NokogiriEncodingReaderWrapper.java, ext/java/nokogiri/internals/NokogiriHandler.java, ext/java/nokogiri/internals/NokogiriXPathFunction.java
=> Replace deprecated usage of RuntimeHelpers with Helpers

.github/workflows/macos.yml
WIP to see if I can get actions working
=> Lets see if this works

Rakefile
Follow up of sparklemotion/nokogiri@06c0ca2. Fix typo.
N/A
N/A
=> Fix typo in generated metadata

appveyor.yml
- add '27-x64'
- update allow_failures to allow `head-x64`
=> ci: attempt to get appveyor green

ext/nokogiri/xml_node_set.c
=> upstream truffleruby patches

.github/workflows/macos.yml, concourse/common_prelude.rb, concourse/nokogiri-pr.yml, concourse/nokogiri-pr.yml.generated, concourse/nokogiri.yml, lib/nokogiri/version.rb, test/html/test_document_encoding.rb, test/html/test_node_encoding.rb, test/test_nokogiri.rb, test/test_version.rb
=> add macos test coverage for system libraries

lib/nokogiri.rb
=> Fix typo in comment

CHANGELOG.md
This makes the copy-and-paste section more pasteable.
No.
=> CHANGELOG: Fix Markdown formatting

Gemfile, Rakefile
Trying to address https://github.com/codeclimate/test-reporter/issues/413
=> dep: remove version lock for simplecov

ext/nokogiri/extconf.rb
mostly rubocop and removal of rdoc stopdoc/startdoc
=> format: extconf.rb

ext/nokogiri/xml_node.c, lib/nokogiri/xml/document.rb, lib/nokogiri/xml/node.rb, test/helper.rb, test/xml/test_document.rb, test/xml/test_node.rb
Improving documentation, but also added some tests and modified the NCNAME_RE regular expression.
Yarp.
Nerp.
=> documentation: Node.new/#initialize, Document#create_element, Node::NCNAME*

CHANGELOG.md, rakelib/test.rake, suppressions/nokogiri_ruby-2.7.supp, suppressions/nokogiri_ruby.supp
=> ci: fix default valgrind suppression

CHANGELOG.md, ext/nokogiri/extconf.rb, nokogiri.gemspec
Update to the latest mini_portile.
=> update to mini portile 2.7.0

rakelib/extensions.rake, rakelib/format.rake, rakelib/rubocop.rake
Narrow the set of files formatted by rubocop and astyle to avoid temporary files.
=> dev: be specific about which files are auto-formatted

CHANGELOG.md, nokogiri.gemspec
See https://guides.rubygems.org/mfa-requirement-opt-in/
Closes #2352
=> gem: opt-in to requiring MFA to publish this and future gems

rakelib/rubocop.rake, test/html4/test_document.rb, test/test_css_cache.rb
These commits are generally useful but have been sitting on a feature branch for a week or two. I'm separating them out into a PR to get them onto main.
- remove unused variables from test_css_cache.rb
- clean up some tests in html4/test_document.rb
- make sure generated CSS files have frozen string literal comments
- add rubocop:fix rake task as an alias for rubocop:check:auto_correct
=> small improvements

.github/workflows/gem-install.yml, scripts/test-gem-install
=> Backport #2425: ci: test x86-linux and aarch64-linux using qemu

test/html4/test_comments.rb, test/html4/test_document.rb, test/html4/test_document_fragment.rb, test/html4/test_element_description.rb, test/html5/test_api.rb, test/html5/test_nokogumbo.rb, test/html5/test_null.rb, test/test_css_cache.rb, test/test_nokogiri.rb, test/test_xslt_transforms.rb, test/xml/test_builder.rb, test/xml/test_cdata.rb, test/xml/test_comment.rb, test/xml/test_document.rb, test/xml/test_document_fragment.rb, test/xml/test_dtd.rb, test/xml/test_node.rb, test/xml/test_node_set.rb, test/xml/test_parse_options.rb, test/xml/test_reader.rb, test/xml/test_unparented_node.rb
rubocop-minitest Minitest/AssertPredicate autocorrects
=> style(rubocop): Minitest/AssertPredicate

lib/nokogiri/html4/document.rb, lib/nokogiri/xml/node.rb, lib/nokogiri/xml/node/save_options.rb
Note I have not tested this change.
=> doc: create link to SaveOptions

dependencies.yml, ext/nokogiri/extconf.rb
update zlib to v1.2.12
https://zlib.net/ChangeLog.txt
=> update zlib to v1.2.12 (main branch)

.github/workflows/ci.yml, CONTRIBUTING.md, lib/nokogiri/html4.rb, lib/nokogiri/html4/document.rb, lib/nokogiri/html4/encoding_reader.rb, nokogiri.gemspec, rakelib/test.rake, test/helper.rb, test/html4/bench_document_encoding.rb
HTML4 document encoding detection improvements.
Yes, there is a complete perf testing approach introduced as a benchmarking test suite.
No.
=> improve encoding reader performance

CHANGELOG.md, ext/java/nokogiri/XmlNode.java, test/helper.rb, test/namespaces/test_namespace_definitions.rb
#1247 
Yes!
This fixes a bug in JRuby and brings it closer to the C implementation. See #2543 for some remaining behavioral differences.
=> jruby: handle repeat namespace definitions

.github/workflows/gem-install.yml, nokogiri.gemspec
upgrade to rake-compiler-dock v1.2.2
Existing test feedback loops are sufficient.
No.
=> dep(dev): update rake-compiler-dock to v1.2.2

.github/workflows/generate-ci-images.yml, nokogiri.gemspec
narrow the pessimistic dev dependencies to minors, and rely on dependabot to opt into minor bumps
=> dep(dev): narrow the pessimistic dev dependencies to minors

.github/workflows/ci.yml
=> ci: update vmactions/freebsd-vm job config

test/html4/test_comments.rb
Upstream libxml2 changed how it handles conditional HTML comments, see https://gitlab.gnome.org/GNOME/libxml2/-/issues/380
Closes https://github.com/sparklemotion/nokogiri/issues/2621
Update the test suite to handle this and explain what's going on a bit. Especially since this behavior changed in 2.9.14 and is essentially changing back.
Yes
No behavioral changes other than handling the changes in upstream libxml2.
=> ci: upstream libxml2 fixed conditional html comments

scripts/test-gem-install
I *think* this is related to:
- https://github.com/rubygems/rubygems/issues/5871
- (proposed fix) https://github.com/rubygems/rubygems/pull/5875
=> ci: workaround recent bundler release bug

scripts/test-gem-install
Work around https://github.com/rubygems/rubygems/issues/5940 in CI
=> ci: work around rubygems arm problem

dependencies.yml, ext/nokogiri/extconf.rb
See #2626 for context. This change updates precompiled native gems to use zlib 1.2.13.
=> dep: update zlib to v1.2.13

rakelib/css-generate.rake
This often needlessly runs after a git checkout.
Closes #2771
=> dev: loosen the timestamp comparison for the CSS parser files

test/helper.rb
I learned recently that Simplecov supports branch coverage. Let's turn it on.
=> test: enable branch coverage in simplecov

ext/nokogiri/xml_xpath_context.c
Part of the TypedData epic described at #2808.
=> migrate XML::XPathContext to the TypedData API

ext/nokogiri/xml_encoding_handler.c
=> ext: migrate Nokogiri::EncodingHandler to TypedData API

ext/nokogiri/xml_element_content.c, ext/nokogiri/xml_element_decl.c, lib/nokogiri/xml/element_content.rb, test/xml/test_element_content.rb
=> Migrate XML::ElementContent to the TypedData API

appveyor.yml
There are no relevant changes in the new image. It's just to avoid using an outdated one eventually.
Not changed.
Only the C impl.
=> CI: Update Appveyor to latest image and ruby version

ext/nokogiri/xml_relax_ng.c
=> Migrate XML::RelaxNG to the TypedData API

ext/nokogiri/xml_schema.c
=> Migrate XML::Schema to the TypedData API

CONTRIBUTING.md, test/helper.rb
I'm getting frustrated with long CI run times, and it's been a bit since CI's valgrind caught something. Let's dial this back a bit.
=> test: make default GC behavior "normal"

CONTRIBUTING.md, dependencies.yml, test/helper.rb, test/xml/test_node.rb
https://github.com/sparklemotion/nokogiri/issues/2851 backport to the v1.14.x branch
=> dep: update to libxml2 2.10.4 (backport)

.github/workflows/ci.yml, Gemfile, oci-images/nokogiri-test/ubuntu.dockerfile, oci-images/nokogiri-test/ubuntu.erb, oci-images/nokogiri-test/ubuntu32.dockerfile, oci-images/nokogiri-test/ubuntu32.erb
See https://github.com/Shopify/ruby_memcheck/pull/16 for context
=> dep: use a fork of ruby_memcheck for the HUGE fix

Gemfile
Update to the latest rake-compiler-dock
=> dep: update rake-compiler-dock to v1.3.1

.github/workflows/downstream.yml
=> ci: add stimulus_reflex to downstream suite

.github/workflows/ci.yml, .github/workflows/generate-ci-images.yml, .github/workflows/upstream.yml, oci-images/nokogiri-test/mri-3.3.dockerfile, oci-images/nokogiri-test/mri.erb, rakelib/docker.rake, test/xml/test_node_set.rb
Let's test against Ruby 3.3.0 final.
See also https://github.com/sparklemotion/nokogiri/pull/3079
=> ci: test against ruby 3.3.0

Gemfile
Last step before shipping a v1.16.0 release, let's try RCD 1.4.0 final
=> dep: update to rake-compiler-dock 1.4.0 final

test/helper.rb
=> test: avoid verify-compaction-references in tests with older Rubies

test/xml/test_entity_reference.rb
Upstream integration test failures. e.g. https://github.com/sparklemotion/nokogiri/actions/runs/8965891987/job/24620292816
=> test: update libxml2 upstream error messages in expectations

CHANGELOG.md, dependencies.yml
forward-port of #3191 to `main`
=> dep: update libxml2 to v2.12.7

test/xml/test_entity_reference.rb
upstream integration testing with libxml2, see gnome/libxml2@4fefba4c
=> test: update tests to handle upstream libxml2

.github/workflows/ci.yml, .github/workflows/upstream.yml
Try to fix truffleruby jobs which are failing with a bundler error.
[Example of failing run](https://github.com/sparklemotion/nokogiri/actions/runs/9282422354/job/25555516804#step:6:28)
(If this goes green, I'll open an issue upstream.)
=> ci: try to fix truffleruby jobs

Gemfile
dep: update to rake-compiler-dock 1.5.1
=> dep: update to rake-compiler-dock 1.5.1

dependencies.yml
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.8
=> dep: update libxml2 to 2.12.8

.github/workflows/generate-ci-images.yml, oci-images/nokogiri-test/upstream-libxml.dockerfile, oci-images/nokogiri-test/upstream-libxml.erb, rakelib/docker.rake
Build a container for libxml2 to use in its pipeline
See:
- https://gitlab.gnome.org/GNOME/libxml2/-/issues/758
- https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/271
=> ci: build a container for libxml2 to use in its pipeline

test/xml/test_entity_reference.rb
Update tests to accept libxml2 error changes from gnome/libxml2@ec088109
=> test: update to accept libxml2 error changes

test/html5/test_tree_construction.rb
run html5lib-tests in both script-on and script-off modes, unless the test specifies one or the other.
Closes #3242
=> test: run html5lib-tests in both script-on and script-off modes

.github/workflows/ci.yml
See thread at https://github.com/sparklemotion/nokogiri/pull/3276#discussion_r1664777419
Let's roll the dice!
cc @stevecheckoway
=> ci: try to update to checkout@v4 for remaining jobs

rakelib/test.rake
move to Minitest::TestTask because it gives us some additional features, specifically displaying slow tests.
=> test: move to Minitest::TestTask

rakelib/test.rake, test/helper.rb, test/simplecov_prelude.rb
Simplecov was broken by #3280, but see
https://github.com/simplecov-ruby/simplecov/issues/1032 for discussion that led to this workaround.
=> test: restore simplecov

.github/workflows/downstream.yml
pending a fix for https://github.com/sparklemotion/nokogiri/pull/3348
=> ci: skip downstream sanitize test for now

.github/workflows/ci.yml
=> ci: simplify the "setup-ruby" ruby version config

ext/nokogiri/xml_xpath_context.c, lib/nokogiri/xml/searchable.rb, lib/nokogiri/xml/xpath_context.rb
Some cleanup and refactoring that was originally in #3378 but is generally valuable even if that PR doesn't land, so I split it out.
=> Minor cleanup

lib/nokogiri/html4/element_description_defaults.rb
Fixes https://github.com/sparklemotion/nokogiri/issues/3432
Not applicable here?
Seems like it does not.
No idea 🙂 
Should there be a changelog entry for this?
=> Drop `Struct::HTMLElementDescription` class

.github/workflows/downstream.yml, CHANGELOG.md, dependencies.yml, ext/nokogiri/extconf.rb
=> dep: update libxml2 to v2.13.6 (main branch)

.github/workflows/ci.yml
Getting CI green again after a few different kinds of build rot have set in. See commits for details.
=> Get CI green again (August 2025 edition)

ext/nokogiri/gumbo.c
Closes #3528
No tests were added. Crashes are nondeterministic and only seem to happen on macOS.
Fixes a bug in the C version.
=> Fix SIGINT during parsing crashing Ruby

CHANGELOG.md, ext/nokogiri/xml_reader.c, test/xml/test_reader.rb
Fixes #3558 
Yes.
The bug only affects the C extension; the Java extension behaves correctly.
=> Fix reader error handling
